### ISSUE TITLE
Support for ** operator

### ISSUE THREAD

**Issue by NaridaL** [jiggzson/nerdamer#100]
How do you feel about adding `**` as a synonym for `^`, to match the ES syntax?

**Comment by jiggzson** [comment]
I'm not really opposed to it. In the past I've left it to the user to decide if they want to add it. Have you looked at the Custom Operator section under the [Digging Deeper Page](http://nerdamer.com/digging_deeper.html)?

**Comment by jiggzson** [comment]
The ** operator should be supported now. Support for it is baked into the core. To solve the problem with text you just have to change **POWER_OPERATOR** setting using nerdamer.set. 
```javascript
//make nerdamer use the '**' instead of '^'
nerdamer.set('POWER_OPERATOR', '**');
var x = nerdamer('(x**y)+6**x');
console.log(x.toString());
//6**x+x**y
```
Hopefully this works as expected.

**Comment by NaridaL** [comment]
Cool.
I'm not sure it's very advisable, but it does allow for stuff like this:


```ts
function nerdamerf(f: (...args: any[]) => any) {
	const exprStr = f.toString().match(/^\s*\([^(]\)\s*=>(.*)$/)[1]
	return nerdamer(exprStr)
}
nerdamer.set('POWER_OPERATOR', '**')
console.log(nerdamer.diff(nerdamerf((x) => x ** 3 + x ** 2 + x), 'x').toString())
// 1+2*x+3*x**2
```

**Comment by jiggzson** [comment]
Cool. I guess you could also replace the operator in the string but I'm guessing you're planning on reusing it somewhere. Glad it helps.
