### ISSUE TITLE
buildFunction doesn't handle built-in constants correctly.

### ISSUE THREAD

**Issue by NaridaL** [jiggzson/nerdamer#103]
```ts
nerdamer('pi * x').evaluate({x: 2}).text('decimals') // ~= 6.28
nerdamer('pi * x').buildFunction(['x'])(0) // ReferenceError: pi is not defined
```
The function body is just `pi * x`, and pi apparently isn't bound. I'd expect Math.PI to be used.

Manually doing nerdamer.setConstant('pi', Math.PI) fixes it, but that shouldn't be necessary.

As an aside, what's the deal with `*`? Sometimes it works, othertimes you get weird errors.

**Comment by jiggzson** [comment]
I'll make sure to bind those. The quickest solution that I can think of is to evaluate the expression in an evaluate block inside the build function. e.g. 

```javascript
body = block('PARSE2NUMBER', function() {
    //evaluate and return expression here
    return _.parse(expr);
}, true);
```
This is of course off the top of my head without actually looking at the problem. This should force pi to be evaluated. What errors are you getting? Could it be related to the ** operator? Do you have any examples?

**Comment by jiggzson** [comment]
The above example now return 
```javascript
function anonymous(x
/**/) {
 return 3.141592653589793*x;
}
```

**Comment by NaridaL** [comment]
Thanks for the quick fix (and the other ones too)!

**Comment by jiggzson** [comment]
No problem. Glad to help.
