### ISSUE TITLE
Inconsistent multiplication behavior

### ISSUE THREAD

**Issue by NaridaL** [jiggzson/nerdamer#104]
```
> nerdamer('x y').evaluate({x: 2}).text('decimals')
'xy'
> nerdamer('x^2 y').evaluate({x: 2}).text('decimals')
'4*y'
```

**Comment by NaridaL** [comment]
It would be cool if this syntax worked, but if it's not going to parse it properly it should throw an error.

**Comment by jiggzson** [comment]
Nerdamer removes all white space before parsing. I suppose this syntax could be supported through some pre-processing of the string. Maybe by doing a string replace using something like
```javascript
e = e.replace(/(.)\s+(.)/g, function(str, a, b) {
    return a+'*'+b;
});
```
prior to remaining the remaining white space.

**Comment by jiggzson** [comment]
Done.

**Comment by NaridaL** [comment]
Hmm...

    nerdamer('y sin x').toString() // == '0'

**Comment by jiggzson** [comment]
You do bring up an interesting issue. It would also be nice if nerdamer understood sin x to be sin(x). This is simple enough with functions taking one argument. What happens with functions taking more than one argument? Does **diff(cos(x), x)** become **diff cos x x** or **diff cos x , x**?

**Comment by NaridaL** [comment]
I'm not sure it makes much of a difference...

Once you're parsing based on the value of a symbol, you can have your rule be:

`FunctionWith2Arguments = Expression ','? Expression`
