### ISSUE TITLE
Missing functions in documentation

### ISSUE THREAD

**Issue by NaridaL** [jiggzson/nerdamer#105]
http://nerdamer.com/documentation.html is missing links to functions `vector`, `matrix` and a bunch of others. The pages exist, but they're only accessible through http://nerdamer.com/demo.html .

**Comment by jiggzson** [comment]
I've added them. Some are deliberately left out. I guess I feel like once I document them, that I'm on the hook for them. And the paint is still drying on some of these functions. The list gets loaded directly from **Parser.functions**. I should probably remove the ones I don't want from the demo list. Good catch though. Thanks.

**Comment by jiggzson** [comment]
I'm reopening this issue as 
1) new functions were added
2) Some functions are still missing

**Comment by jiggzson** [comment]
Done!
