### ISSUE TITLE
vector derivative not working

### ISSUE THREAD

**Issue by NaridaL** [jiggzson/nerdamer#106]
```js
> nd('diff(vector(x, x^2, 3), x)').text()
'[x,x^2,3],x'
```

Expected output: `[1, 2*x, 0]`

**Comment by jiggzson** [comment]
No problem. I'll fix this. By the way, thanks for all your feedback. It's greatly appreciated.

**Comment by NaridaL** [comment]
OK, I hadn't loaded nerdamer/calculus. It should really throw an error when calling an undefined function. 

diff is still broken though.

**Comment by jiggzson** [comment]
It used to. That changed when I added support for expressions such as x(x+1). It's supposed to assume diff as a variable if not loaded as a function. I'll have to revisit this issue because it gives weird outputs with functions that take multiple arguments.

**Comment by jiggzson** [comment]
I've already fixed the diff issue. I'm currently working on adding support for some more integrals. I'll commit shortly when I'm done.

**Comment by NaridaL** [comment]
Cool. No hurry, I don't need it currently, I was just testing some stuff.

**Comment by NaridaL** [comment]
`integrate(x^2,2)` results in `2*x^2` which probably doesn't make sense...

**Comment by jiggzson** [comment]
Fixed!

**Comment by NaridaL** [comment]
Yup, looks good. Opened separate issue for the undefined functions.

**Comment by jiggzson** [comment]
Cool. Thanks.
