### ISSUE TITLE
Integrate(cos(x^2), x) returning wrong value

### ISSUE THREAD

**Issue by gksander** [jiggzson/nerdamer#110]
Running `Integrate(cos(x^2), x)` returns `sin(x^2)` which is incorrect. I poked around Calculus.js a little bit, but got a little overwhelmed. It looks like the `else if((g === FN) {` block starting on line 809 is being executed during the integration process, but it's not handling the fact that x has a power.

**Comment by jiggzson** [comment]
Yea. I hope to one day roll up my sleeves and simplify the integrate method a little bit. It's recursion heavy and I think that in few cases this can be avoided. I'd want to write a ton of unit tests before I embark on that. This was actually one of the first test set to fail in the early integration routine but I guess somehow it must have been deleted. The culprit is around line 1054 where the lines 
```javascript
var ag = symbol.args[0].group;
                                    
if(!(ag === CP || ag === S || ag === CB))
    __.integration.stop();
```
have to be swapped out with 

```javascript
var ag = symbol.args[0].group,
    decomposed = __.integration.decompose_arg(arg, dx);
                                    
if(!(ag === CP || ag === S || ag === CB) || decomposed[1].power.equals(1))
     __.integration.stop();
```
I'm going to lump this in with a few more changes. I have this issue with factor that's bugging me a bit that I hope to get to when I have a little more time. Out of curiosity, what are you using to debug? It just seems to be pretty efficient.

**Comment by gksander** [comment]
Interesting.

Honestly, I'm not doing anything fancy to debug. I have the following in an HTML file one directory about my local nerdamer git repo:
``` html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Testing</title>
	<script type="text/x-mathjax-config">
	    MathJax.Hub.Config({
	      tex2jax: {
    	        inlineMath: [['$','$'], ['\\(','\\)']],
    	        processEscapes: true
            }
	    });
    </script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML"></script>
	<script
	  src="https://code.jquery.com/jquery-3.2.1.min.js"
	  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
	  crossorigin="anonymous"></script>

	<script src="nerdamer/nerdamer.core.js"></script>
	<script src="nerdamer/Algebra.js"></script>
	<script src="nerdamer/Calculus.js"></script>
	<script src="nerdamer/Solve.js"></script>
	<style>
		body {text-align:center;}
	</style>
	<script>
		var runCalc = function(){
			var inp = $("#inp").val();
			try {
				var os = "$$";
				os += nerdamer.convertToLaTeX(inp);
				os += "=";
				os += nerdamer(inp).toTeX();
				os += "$$";
				$("#out").html(os);

				MathJax.Hub.Queue(["Typeset",MathJax.Hub,"out"]);

			} catch (err){
				console.log(err);
				$("#out").html(`<p style='color:red'>Seems to be an error</p>`);
			}
		};

		$(function(){
			$("#inp").on('keyup', function(event) {
		        if (event.keyCode == 13) {
		            runCalc();
		        } 
		    });
		});
	</script>
</head>
<body>
	<p>
		<input type="text" id="inp" value='integrate(cos(x^2),x)'> [Press Enter to Run]
	</p>
	<p id="out"></p>
</body>
</html>
```
When I'm testing some things, I run things through that file so that I can see what nerdamer is printing out (in terms of LaTeX), and if nerdamer is throwing any errors I can catch them in my Chrome Console. In terms of debugging, I've mostly just been doing old-fashioned `console.log(...)` statements in the source files and using Chrome Dev tools to add breakpoints, etc. I haven't written any unit tests or anything, just manually debugging as I come across things.

In the HTML I posted above, I'll change the value attribute of the input[type="text"] to whatever command I'm testing so that I don't have to keep typing in the command. But this has worked pretty well. (And forces me to read through the source files, which has been useful for me.)

**Comment by jiggzson** [comment]
Simple yet efficient. I'm always amazed when you pretty much tell me the problem and what you've found. It's cuts down my debugging time quite a bit. I know about Algebrite. It's a port of EigenMath. It's a pretty neat project. I never realized that that's how they integrate. I was thinking of going the same route but I quickly realized that I'd be looking up quite a few integrals so I decided to calculate them using methods we learned in Calculus class. I fixed this issue so feel free to close it whenever you're satisfied.

**Comment by gksander** [comment]
Well, I'm glad that I'm being at least a little helpful -- and not just bugging you with issues and PR's. I've only been programming for a couple years (and only recently got serious about it), so contributing (and getting advice from you) has been tremendously helpful for me. I'll close this issue now.

**Comment by jiggzson** [comment]
Thank you. Never hesitate to alert me to a bug. I greatly appreciate that. Glad to help.
