### ISSUE TITLE
Solving for velocity in relativistic kinetic energy

### ISSUE THREAD

**Issue by arve0** [jiggzson/nerdamer#112]
In physics we have [kinetic energy](https://en.wikipedia.org/wiki/Kinetic_energy#Relativistic_kinetic_energy_of_rigid_bodies) given by `E_k = m c^2 ((1 - v^2 / c^2)^-0.5 - 1)`:

![skjermbilde 2017-05-30 kl 23 14 20](https://cloud.githubusercontent.com/assets/4810521/26605333/da51703e-458d-11e7-93eb-9731b5460628.png)

I expected nerdamer to solve this, but get an empty array:

```js
$ git clone https://github.com/jiggzson/nerdamer
$ cd nerdamer
$ node
> let nerdamer = require("./")
> require("./Algebra.js")  // took me some time to figure this out
> require("./Calculus.js")
> require("./Solve.js")
> nerdamer("E_k = m c^2 ((1 - v^2 / c^2)^-0.5 - 1)").solveFor("v")
[]
> // expected non-empty array
```

The equation can be solved like this:

1. Divide by mc^2
  
![skjermbilde 2017-05-30 kl 23 27 58](https://cloud.githubusercontent.com/assets/4810521/26605787/a7b48a42-458f-11e7-98f1-efa859087177.png)

2. Plus one, power of minus two

![skjermbilde 2017-05-30 kl 23 37 26](https://cloud.githubusercontent.com/assets/4810521/26606108/f89be2ba-4590-11e7-8882-d758345e2f42.png)

4. Move terms

![skjermbilde 2017-05-30 kl 23 39 04](https://cloud.githubusercontent.com/assets/4810521/26606186/3c4023be-4591-11e7-94c9-089c8bf714f0.png)

5. Multiply by c^2, square root

![skjermbilde 2017-05-30 kl 23 41 21](https://cloud.githubusercontent.com/assets/4810521/26606247/832f2c5c-4591-11e7-8baf-0dc1041b182f.png)

Should this equation be solvable with nerdamer?

**Comment by jiggzson** [comment]
This provides an excellent opportunity to beef up Solve. It seems that just like in your example nerdamer needs to first rewrite the equation. I'm sorry that it wasn't clear that Solve depends on Algebra and Calculus (I noticed that in your comments). I'll review the documentation and try to clarify this. I'll get started on a rewrite function. This doesn't seem like it should be too difficult so I might have something pretty soon.

**Comment by jiggzson** [comment]
I've added a rewrite function to solve that deals with cases when the variable is nested as in your case. If you find any issues with this please let me know. If you have any other questions don't hesitate to ask.

**Comment by arve0** [comment]
Thanks! 🎉 

```js
> nerdamer("E_k = m c^2 ((1 - v^2 / c^2)^-0.5 - 1)").solveFor("v")[0].toString()
'sqrt(-(1+E_k*c^(-2)*m^(-1))^(-2)*c^2+c^2)'
```

Is it possible to factor out `c^2` in any way?

**Comment by arve0** [comment]
Adding a bit more.. I see that the nerdamer equation object is not of same type as a solution object:

```js
> nerdamer('x + 3').divide('x').expand().toString()
'1+3*x^(-1)'
> nerdamer("E_k = m c^2 ((1 - v^2 / c^2)^-0.5 - 1)").solveFor("v")[0].divide('c'
).expand().toString()
TypeError: nerdamer(...).solveFor(...)[0].divide is not a function
    at repl:1:69
    at realRunInThisContextScript (vm.js:22:35)
    at sigintHandlersWrap (vm.js:98:12)
    at ContextifyScript.Script.runInThisContext (vm.js:24:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:513:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
```

Differences in objects:
```js
> eq = nerdamer('x+2')
{ [String: '2+x']
  symbol:
   { [String: '2+x']
     group: 8,
     value: '2+x',
     multiplier: { [Number: 1] num: [Object], den: [Object] },
     imaginary: false,
     power: { [Number: 1] num: [Object], den: [Object] },
     symbols: { x: [Object], '#': [Object] },
     length: 2 } }
> eq.
eq.__defineGetter__      eq.__defineSetter__      eq.__lookupGetter__
eq.__lookupSetter__      eq.__proto__             eq.constructor
eq.hasOwnProperty        eq.isPrototypeOf         eq.propertyIsEnumerable
eq.toLocaleString        eq.toString              eq.valueOf

eq.add                   eq.buildFunction         eq.divide
eq.each                  eq.eq                    eq.evaluate
eq.expand                eq.gt                    eq.gte
eq.hasIntegral           eq.isFraction            eq.isInfinity
eq.isNumber              eq.isPolynomial          eq.latex
eq.lt                    eq.lte                   eq.multiply
eq.operation             eq.pow                   eq.solveFor
eq.sub                   eq.subtract              eq.text
eq.toDecimal             eq.toTeX                 eq.variables

eq.symbol

> eq = nerdamer('x+3').solveFor('x')[0]
{ [Number: -3]
  group: 1,
  value: '#',
  multiplier:
   { [Number: -3]
     num: { [Number: -3] value: -3, sign: true, isSmall: true },
     den: { [Number: 1] value: 1, sign: false, isSmall: true } },
  power:
   { [Number: 1]
     num: { [Number: 1] value: 1, sign: false, isSmall: true },
     den: { [Number: 1] value: 1, sign: false, isSmall: true } } }
> eq.
eq.__defineGetter__      eq.__defineSetter__      eq.__lookupGetter__
eq.__lookupSetter__      eq.__proto__             eq.constructor
eq.hasOwnProperty        eq.isPrototypeOf         eq.propertyIsEnumerable
eq.toLocaleString        eq.toString              eq.valueOf

eq.altVar                eq.attach                eq.clone
eq.coeffs                eq.collectSymbols        eq.combine
eq.contains              eq.containsFunction      eq.convert
eq.distributeExponent    eq.distributeMultiplier  eq.each
eq.equals                eq.fnTransform           eq.getDenom
eq.getNum                eq.greaterThan           eq.gt
eq.gte                   eq.hasFunc               eq.hasIntegral
eq.hasNegativeTerms      eq.hasTrig               eq.insert
eq.invert                eq.isCombination         eq.isComposite
eq.isConstant            eq.isE                   eq.isInteger
eq.isInverse             eq.isLinear              eq.isMonomial
eq.isOne                 eq.isPi                  eq.isPoly
eq.isSQRT                eq.keyForGroup           eq.latex
eq.lessThan              eq.lt                    eq.lte
eq.multiplyPower         eq.negate                eq.sameVars
eq.setPower              eq.sign                  eq.stripVar
eq.sub                   eq.tBase                 eq.text
eq.toArray               eq.toLinear              eq.toUnitMultiplier
eq.updateHash

eq.group                 eq.multiplier            eq.power
eq.value
```

**Comment by jiggzson** [comment]
As far as the factoring, did you have something like **(abs(c)*sqrt(E_k*(2*c^2*m+E_k)))/abs(c^2*m+E_k)** in mind? I noticed that factor throws an error when trying to factor that expression so I'll take a look at it. The problem is that multivariate factoring is a bit complicated so I'm not sure how much progress I'll be able to make on that. As for solve, it returns an array of solutions, basically Symbol[], which cannot be chained. Symbol is supposed to be a private class. It's one of those parts that I struggled with as to what to return. I guess it makes sense for it to return Expression[]. Am I understanding you correctly?

**Comment by arve0** [comment]
> As far as the factoring, did you have something like (abs(c)sqrt(E_k(2c^2m+E_k)))/abs(c^2*m+E_k) in mind?

Expected something like `abs(c) sqrt(1-(1+E_k*c^(-2)*m^(-1))^(-2))` or `sqrt(c^2 (1-(1+E_k*c^(-2)*m^(-1))^(-2)))`.

> I guess it makes sense for it to return Expression[]. Am I understanding you correctly?

Yes. If that lets you chain (`.divide`, `.multiply`, etc) / work on the solved equation.

**Comment by arve0** [comment]
Anyhow, that's another issue. Thanks for solving this 👍 Closing.

**Comment by jiggzson** [comment]
I've added factoring for sqrt. Thanks for your input. Good luck.
