### ISSUE TITLE
node.js style importing

### ISSUE THREAD

**Issue by arve0** [jiggzson/nerdamer#113]
ref #112: 

>  I'm sorry that it wasn't clear that Solve depends on Algebra and Calculus (I noticed that in your comments).

I read in the docs that those where dependencies, so the dependency was clear, but I wasn't sure how to load it. Reading the code I noticed that nerdamer object was updated when those files where required. Guess a simple example specifically for node.js should do, like explicit stating in the beginning how to require the modules. For example:

If you are in node, require nerdamer like this:

```js
let nerdamer = require('nerdamer');  // cannot be const, nerdamer object is updated below
require('nerdamer/Algebra.js');
require('nerdamer/Calculus.js');
require('nerdamer/Solve.js');
```

BTW, have you considered a more idiomatic approach? Like this

```js
const nerdamer = require('nerdamer'); // loads all modules
```

**Comment by jiggzson** [comment]
The idea was to be able to only load what you need. It's kind of silly since loading any of the  packages, currently causes all packages to be loaded. I'm going to have to play with it a bit and so some form of lazy loading.

**Comment by jiggzson** [comment]
I've added 'all.js'. Hopefully this allows something like 

```javascript
const nerdamer = require('nerdamer/all');
```
I haven't published this to npm yet.

**Comment by jackel89** [comment]
i cant get this to work in js to load anything other than the basic stuff and its driving me bonkers.
