### ISSUE TITLE
Problem with demo on homepage 

### ISSUE THREAD

**Issue by menzelths** [jiggzson/nerdamer#115]
f(x)=x^2
f(2) // 4 , ok
g(x)=diff(f(x),x) // 2x , ok
g(2) // 0 NOT OK!

I tried to use your demo as start for writing a dynamic solution sheet and could not evaluate the function in the example.

**Comment by jiggzson** [comment]
Thanks for pointing that out. I'll go ahead and fix this. The issue seems to related to the demo script and not the library itself.

**Comment by jiggzson** [comment]
@menzelths, it seems to me that you are indeed getting the correct answer. g(x) does the following. It evaluates f(x) and the pulls the derivative of that. 
In the above example:
g(x) = diff(f(x),x) where f(x) = x^2
g(2) = diff(f(2),x) = diff(4,x) = 0

**Comment by menzelths** [comment]
I see, but I would like to get 
g(2)=diff(f(x),x)(2)=2^2=4

How can I define g(x) as a new function agnostic to its history, which means simply: g(x)=x^2 ?

**Comment by jiggzson** [comment]
Let me think about it some. Out of curiosity are you planning on doing this through the demo? I'm asking this since the demo is very limited and you have a lot more options by using the library directly.

**Comment by menzelths** [comment]
[nerdamer.zip](https://github.com/jiggzson/nerdamer/files/1145165/nerdamer.zip)

Sorry for the delay, just prepared something. Unzip it and check it out. Runs best in Edge or Chrome.

**Comment by jiggzson** [comment]
No problem. I'll take a look at this shortly.

**Comment by jiggzson** [comment]
Maybe I'm a little confused but would simply evaluating the function at a point work? The output is up to you. For instance having something like
f = x^2 can still be printed to the user as 

![image](https://user-images.githubusercontent.com/4887628/28178164-0675af20-67c3-11e7-99f5-009c5447b7de.png)

You can then in your script do something like: 

```javascript
//get the input
var input = 'x^2';
var f = nerdamer(input);
//evaluate for f at a point
var p1 = f.evaluate({x: 2}).toString();
//get g(x)
var g = nerdamer.diff(f, 'x'); 
//evaluate g at point
var p2 = g.evaluate({x: 2}).toString();

console.log(p1, p2)
```
Would that help? If not please explain how the program gets its input.

**Comment by menzelths** [comment]
Sorry for creating so much confusion.
The usage of the javascript code is not the problem. I want the user to not see any javascript. This is why I want the user to be able to enter

f(x):=x^2
g(x):=diff(f(x),x)
g(2) // you know :-) , 4

This is also the reason why I chose your live demo as starting point for my experiment.

Anyway, I found a way to get around the problem: in your code you use in the "process"-function

`
nerdamer.setFunction(fnName, params, fnBody);
`
to define the new function. By simply substituting this term with
`
nerdamer.setFunction(fnName, params, nerdamer(fnBody).text());
`
I first transform the right hand side of a function definition into its textual representation. By doing so the new function works for me as it should: g(2) provides 4 as return value. Thereby it forgets about its "history" as it is just defined by g(x):=2x, not knowing that this expression originally came from the derivation of f(x). 

For me this is the expected behaviour. I don't know if this could be useful for your online demo, too.  Or how do you manage to evaluate the value of a derivate at a given position *without javascript* in your demo?

Thank you for your patience. 
I really appreciate your great library, very impressive! Kudos to your team!

**Comment by jiggzson** [comment]
Awesome! Sounds good. I'm glad you were able to resolve your issue. And thanks!
