### ISSUE TITLE
Issue regarding : http://nerdamer.com/demo.html

### ISSUE THREAD

**Issue by abhinov2** [jiggzson/nerdamer#117]
@jiggzson Why i am not able to enter question for second time for evaluation in your given text box.
Your text box is not taking any entry after first time

**Comment by jiggzson** [comment]
@abhinov2 Can you give an example please?

**Comment by abhinov2** [comment]
See this http://nerdamer.com/demo.html ...
Whenever i am entering for second time , text box is not taking entry

**Comment by jiggzson** [comment]
So if you enter **x^2+1** and hit enter and then enter **sin(x)/x** the second one won't enter? What platform are you using?

**Comment by abhinov2** [comment]
I am using this thing on your website only , give address(http://nerdamer.com/demo.html ).

**Comment by jiggzson** [comment]
@abhinov2 I understood that you're using the demo on nerdamer.com. What I'm asking is which browser are you using? Is it mobile? What expressions or equations are you entering? Please explain that a little. I tried recreating your issue but everything seems to work OK.

**Comment by jiggzson** [comment]
@abhinov2 Any update on this?
