### ISSUE TITLE
doesn't parse equations anymore

### ISSUE THREAD

**Issue by JanMP** [jiggzson/nerdamer#118]
I had been using nerdamer to clean up equations and turn them into LaTeX. That doesn't work anymore. Entering a+1=2 in demo on nerdamer.com leads to an error.

**Comment by jiggzson** [comment]
It seems that the updates done to the demo are causing problems. Is this issue strictly with the demo? Or do you have this problem with the library itself as well?

**Comment by JanMP** [comment]
> Am 08.08.2017 um 14:33 schrieb Martin Donk <notifications@github.com>:
> 
> It seems that the updates done to the demo are causing problems. Is this issue strictly with the demo? Or do you have this problem with the library itself as well?
> 
> 
Got that with the lib. It had been working with the nerdamer of 2 months ago (I think… must admit I am not testing as thoroughly as I should)

**Comment by jiggzson** [comment]
OK. I'll go ahead and take a look at it.

**Comment by jiggzson** [comment]
This should be fixed.

**Comment by JanMP** [comment]
It is.
