### ISSUE TITLE
Make divide() the / operator

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#119]
Make it when the algebra module is loaded, replace / behaviour with divide(). Does not make sense to have a separate divide() function.

**Comment by jiggzson** [comment]
I have tried to do this in the past but it gave me quite a few headaches. Divide (Algebra.divide which does polynomial long division) is pretty straightforward for univariate polynomials but gets complicated really fast for multivariate polynomials. This would force me to deal with all the edge cases in situations such as differentiation, integration, etc. for which the current divide (Parser.divide which does simplification) function does just fine. I guess I can try and give it another go at some point or make this an optional setting.

**Comment by Happypig375** [comment]
Giving you spiritual support ;)

**Comment by jiggzson** [comment]
Fixed
