### ISSUE TITLE
sqrt(i) does not evaluate

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#120]
nerdamer("sqrt(i)").evaluate().toString() returns sqrt(i).
sqrt(i) should evaluate to 0.707106781 + 0.707106781 i

**Comment by Happypig375** [comment]
Or 1/sqrt(2)+1/sqrt(2)*i

**Comment by jiggzson** [comment]
Thanks for pointing that out. I'll make sure to fix that.

**Comment by Happypig375** [comment]
Moved to #181.
