### ISSUE TITLE
Implement sech, csch, coth, asec, acsc, acot, asech, acsch, acoth

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#121]
Why not implement them when you already have sec, csc, cot?

**Comment by jiggzson** [comment]
Sounds good to me. I'll make sure to implement these.

**Comment by Happypig375** [comment]
Status as of 0.7.13:
- [ ] sech
- [ ] csch
- [ ] coth
- [x] asec
- [x] acsc
- [x] acot
- [x] asech
- [ ] acsch
- [x] acoth

**Comment by jiggzson** [comment]
Done!
