### ISSUE TITLE
solve() with variable exponent

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#122]
nerdamer("solve(10^x=y,x)") returns []
It should return [log10(y)]

Same for nerdamer("solve(e^x=y,x)"), should return [log(y)]

For variable base, nerdamer("solve(n^x=y,x)") should return [log(y)/log(n)]

**Comment by jiggzson** [comment]
This is doable. I'll account for these cases.

**Comment by Happypig375** [comment]
>nerdamer("solve(n^x=y,x)") should return [log(y)/log(n)]

Should it return [log(y, n)] as of #150 (preferred) or keep current proposal?

**Comment by jiggzson** [comment]
This should be fixed.
