### ISSUE TITLE
gcd does not like variables

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#123]
nerdamer("gcd(x+y,(x+y)^2)") returns (x+y)^2
should be x+y

nerdamer("gcd(x+y,(x+y)(x-y))") returns 1
should be x+y

**Comment by Happypig375** [comment]
Oops, wrong button. Sorry.

**Comment by Happypig375** [comment]
gcd(x^y,x) errors? Big bug here.

**Comment by jiggzson** [comment]
I think I know what's causing this issue. This will be fixed with the next update.

**Comment by jiggzson** [comment]
>gcd(x^y,x) errors? Big bug here.

x^y is not a polynomial. I've added the fixes for the two above.

**Comment by Happypig375** [comment]
I wonder if gcd(x^y,x) => x would work.

**Comment by Happypig375** [comment]
Now gcd(x,y) => x ?? This is a regression. It used to output 1 (which is also wrong). Should remain gcd(x, y) until substitution.

**Comment by jiggzson** [comment]
Returning gcd(x^y,x) is the best response since I have no guarantee that y is positive, or an integer.

**Comment by Happypig375** [comment]
Another regression! Yay! This time it is gcd(x^2+y^2,y) hanging. Nerdamer is stuck in this loop:
https://github.com/jiggzson/nerdamer/blob/5653a0eeb0c3329ba762d42671a49e626784b331/Algebra.js#L2304-L2314

**Comment by jiggzson** [comment]
This one should be fixed.

**Comment by Happypig375** [comment]
My tester complains about console not being defined... 😆 Will verify this later.

**Comment by Happypig375** [comment]
gcd(3,x) => 3 (@demo, @dev and @master)
Wow.
