### ISSUE TITLE
nerdamer thinks 0^0 == 0 and 1

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#127]
solve(x^x,x) returns [0], but 0^0 is undefined!
solve(x^x-1,x) returns [0,1], but 0^0 is undefined!
solve(x^x-x,x) returns...
[0,136521996/136521997]. I thought rounding errors are gone!

**Comment by jiggzson** [comment]
I think this one is related to issue #122. It might also be related to the fact that solve falls back to a slightly modified version of Newton's method when it can't solve the equation algebraically. I'll dig deeper into this one.

**Comment by jiggzson** [comment]
Well here you go! Remember earlier when I said that this falls back to a numerical method? 
```javascript
console.log(Math.pow(0, 0));
```
Yup. JavaScript disagrees and says it's 1 😆. I guess I'll have to keep this in mind with exponential powers. Hopefully this issue will be solved when I take care of issue #129.

**Comment by jiggzson** [comment]
Moving to #322
