### ISSUE TITLE
Euler's identity

### ISSUE THREAD

**Issue by brosnanyuen** [jiggzson/nerdamer#13]
```javascript
var e = nerdamer('e^(2*i*PI) +e^(i*PI)');
console.log(e.text());
```

**e^(3.141592653589793*i)+e^(6.283185307179586*i)**

Euler's identity could be useful in solving complex exponential. (E.g  (a+bi)^n )

**Comment by brosnanyuen** [comment]
More generally,I propose complex numbers shouldn't be in the core. Many of the functions written for real numbers don't apply the same way for complex numbers.

**Comment by jiggzson** [comment]
Why can't we write a test case for this identity? If we were to move complex numbers from the core then where would be a more appropriate place? An add-on?

**Comment by brosnanyuen** [comment]
Fundamentally, when nerdamer's parser takes in an expression. It assumes the expression is in the set of real numbers. However, it doesn't account for complex numbers.

For example:
abs(i+1) doesn't do anything
cos(i+1) doesn't do anything

I guess we have to rewrite a lot of functions to take complex numbers

Also
(-1)^x => -1

Something is wrong with exponents.

**Comment by jiggzson** [comment]
I see what you mean. Wouldn't it just be better to extend the functions in the core to deal with those cases? I can't think of a way to deal with complex numbers any other way. (-1)^x is a bug and should be addressed.

**Comment by brosnanyuen** [comment]
Ok, I agree to extend the core since Solve.js might use a lot of complex numbers.

**Comment by brosnanyuen** [comment]
var e = nerdamer('e^x',{x:6}).evaluate();
console.log(e.valueOf());
"e^6"

It doesn't evaluate exponents at all.

**Comment by jiggzson** [comment]
You never specified what e is. Unless you're looking for the mathematical constant e. In that case it's accessed using capital letters (E). Same as for pi (PI). Also regarding detecting this identity and others. I think they should be checked for as an option since the overhead for detecting them might be a bit much.

**Comment by brosnanyuen** [comment]
I made the mistake of not making capitalizing E.

I think the key for solving these bugs could be euler's identity.
Any equation (a+bi)^(f(x)) could be turned to exponential format to cartesian format.
(-1)^x => E^(i*PI*x) => cos(PI*x) + i*sin(PI*x)

**Comment by jiggzson** [comment]
Brosnan, the issue should be closed. Let me know if the latest implementation solves your issue.
