### ISSUE TITLE
factorials are not collapsing properly

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#130]
x! => factorial(x) (OK)
x!! => dfactorial(x) (OK)
x!!! => factorial(dfactorial(x)) (OK)
x!!!! => factorial(factorial(dfactorial(x))) (should be dfactorial(dfactorial(x)))
x!!!!! => factorial(dfactorial(dfactorial(x))) (OK)
x!!!!!! => factorial(factorial(dfactorial(dfactorial(x)))) (should be dfactorial(dfactorial(dfactorial(x))))
x!!!!!!! => factorial(dfactorial(dfactorial(dfactorial(x)))) (OK)
x!!!!!!!! => factorial(factorial(dfactorial(dfactorial(dfactorial(x))))) (should be dfactorial(dfactorial(dfactorial(dfactorial(x)))))

See the pattern?

**Comment by jiggzson** [comment]
I see what you mean. However implementing postfix operators with Shunting-Yard is a pain. I've thought about going to a full parser but those tend to be slow and I need parsing to be snappy if I'm to use the symbolic layer for for computationally intensive operations such as integration for instance. I don't want to be stuck using lookup tables when integrating. I'll look at this again but we may have to end up leaving this one as-is unless it's giving you a lot of headaches.

**Comment by Happypig375** [comment]
> we may have to end up leaving this one as-is unless it's giving you a lot of headaches.
Ok

**Comment by jiggzson** [comment]
@Happypig375, fixed.
