### ISSUE TITLE
Implement % (percentage) operator

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#131]
For typing fluently.

**Comment by jiggzson** [comment]
This should be easy enough _(I hope)_.

**Comment by Happypig375** [comment]
After looking at the commits, I think I was not clear enough about the title:
I did not mean the modulo operator, I meant the real percentage postfix operator: 1% == 0.01
But the modulo operator definitely has its use and I appreciate it.
The two meanings of % should not overlap (I think).

**Comment by jiggzson** [comment]
I see. And you even put **percentage** in the title.  I'll remove the modulo operator by default.

**Comment by Happypig375** [comment]
Why not % as both modulo and percentage?

1%2 => mod(1, 2) => 1
(1%)2 => (1/100)*2 => 1/50
1(%2) => ERROR

Oh wait... an operator can only be prefix, infix or postfix, not a combination of them.

**Comment by jiggzson** [comment]
I can try I guess. Try to make it behave postfix-ish. Let's give it a go. If it turns out to be too problematic then I'll keep it as the percentage operator. One thing though. I'm very strapped for time these days. I normally get 30-40 minutes a day to work on this if I'm lucky. Can you aid in writing the tests for the issues you requested? @ljacqu I don't know how busy you are so these days but your help is always appreciated. You've come to the rescue in the past so thanks as always.

**Comment by jiggzson** [comment]
Nope. Won't work. I just tried this and in the expression '5%+5%' nerdamer will treat the + as a prefix operator. So the process will be something like

**"5%+5% -> 5%5% -> undefined%0 -> error"**

So there's really no way of supporting this behavior without rewriting the parser.

**Comment by Happypig375** [comment]
>Can you aid in writing the tests for the issues you requested? 

I will, but I have never written tests before. Will look at the spec.js files.

**Comment by jiggzson** [comment]
Thanks I appreciate that. ljacqu already wrote some and he has really helped out big time in the past but you can never have too many tests. Just look at how many issues you were able to bring to light.

**Comment by ljacqu** [comment]
Hi guys, I'm always up for writing tests! You're welcome to **@mention** me anytime. I appreciate it if you could let me know what new feature is introduced that could be tested as it's hard to tell from the commits sometimes (without spending a lot of time).

**Comment by jiggzson** [comment]
No problem @ljacqu. Will do.

**Comment by jiggzson** [comment]
@Happypig375, I noticed that you added tests for both the mod function and percent. I thought we agreed on the % operator meaning percent. I cannot support both. I thought I could shoehorn something but it fails miserably. Are we agreeing on percent or mod?

**Comment by Happypig375** [comment]
>@Happypig375, I noticed that you added tests for both the mod function and percent. I thought we agreed on the % operator meaning percent. I cannot support both. I thought I could shoehorn something but it fails miserably. Are we agreeing on percent or mod?

https://github.com/jiggzson/nerdamer/blob/257712ec3bc439c186496a98c42b743a7d6719a8/nerdamer.core.js#L5155-L5160
You what? I thought this was working code! Urrrrrrrrrrggggggggghhhhhhhh.

**Comment by Happypig375** [comment]
Fine. Just percent. Mod would ideally be an infix operator itself, as in '20 mod 3' (Result: 2).

**Comment by Happypig375** [comment]
>Since %'s meaning of modulo is not there now, maybe change the meaning of '1%1' to '1%*1' and '1%1%' to '1%*1%'?

Bump...
I will submit a PR for tests containing this behaviour.

**Comment by Happypig375** [comment]
>I will submit a PR for tests containing this behaviour.

Created as #190.

**Comment by jiggzson** [comment]
@Happypig375, added. It works but still a little buggy in my opinion. I'll need to test this a bit in the future.
