### ISSUE TITLE
Implement Infinity and undefined

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#134]
When javascript allows divisions by zero by returning Infinity or undefined (0/0), nerdamer throws on divisions by zero or tan(pi/2).

**Comment by jiggzson** [comment]
Allowing division by zero is one of those things that makes for interesting debugging. It's literally hours worth of work, when division by zero causes a bug in any of the other functions. I'm not sure it's a great idea to allow this during regular evaluation. I did at some point think about implementing limits but I'm having a bit of a time crunch lately.

**Comment by Happypig375** [comment]
> interesting debugging

Maybe something like this?
nerdamer.set('ALLOW_DIVISION_BY_0', false); //Default: true

**Comment by jiggzson** [comment]
No problem. I'll add a disclaimer with this setting. Do keep in mind that this in return creates problems with the bigNumber package. It's not too fond of Infinity so I think I ended up bypassing this in order to support Infinity. Let's see how this goes.

**Comment by jiggzson** [comment]
I'll be implementing Infinity but undefined will throw.

**Comment by Happypig375** [comment]
>undefined will throw

#255:
>Accuracy is my top priority

undefined is mathematically accurate... A setting, maybe?
You can also choose to make it throw as you suggested.

**Comment by jiggzson** [comment]
I'll throw with a specific error. I prefer that. If I make it a return type then I have to support
"undefined*undefined", "2+undefined", "undefined^undefined", "Infinity+undefined", "diff(undefined)", ...

**Comment by Happypig375** [comment]
>"undefined*undefined", "2+undefined", "undefined^undefined", "Infinity+undefined", "diff(undefined)", ...

They are all undefined. Any operations with undefined is undefined.

**Comment by jiggzson** [comment]
Correct. But I'd have to update all operations to account for this. If you must have this return type I encourage you to implement this and send me an PR with passing tests.

**Comment by Happypig375** [comment]
>I encourage you to implement this and send me an PR with passing tests.

You don't like implementing this (and #233, #259) or what?

**Comment by jiggzson** [comment]
#259 Just seems strange. You'll be setting a constant to variable. Seems like setAlias or something like that might make more sense.

**Comment by Happypig375** [comment]
As of 0.7.13:
Infinity+Infinity => Infinity (GOOD)
Infinity-Infinity => Error: (Infinity)+(-Infinity) is not defined! (GOOD)
Infinity*Infinity => Infinity (GOOD)
Infinity/Infinity => Infinity (BAD)
Infinity^Infinity => (Infinity)^(Infinity) is undefined! (GOOD)
0^Infinity => Infinity (BAD)
1^Infinity => Infinity (BAD)
Infinity^0 => Infinity (BAD)

**Comment by Happypig375** [comment]
Another idea:
Instead of letting undefined pop up the calculation, a helpful error is thrown instead.

Something like:
7/sqrt(asin(0)^acos(1))+5 => Error: asin(0)^acos(1) is undefined!

**Comment by jiggzson** [comment]
@Happypig375. This should be done. Undefined throws and `UndefinedError` and the errors are stored in core.exceptions.
