### ISSUE TITLE
Documentation: mod

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#137]
Usage says it has 1 parameter.
Parameters says it has 1 parameter.
Example says it has 2 parameters.
In fact, mod() has 2 parameters.

**Comment by Happypig375** [comment]
And mod(2x+2y, x+y) should evaluate to 0 instead of not evaluating?

**Comment by jiggzson** [comment]
>And mod(2x+2y, x+y) should evaluate to 0 instead of not evaluating?

Separate issue. Not only that but I'm not ready to go down that rabbit hole at the moment.

**Comment by Happypig375** [comment]
>Separate issue.

Opened as #211.

(Wow... 211 vs 137. Sometimes it is weird to look back at how many issues I have created over the past three _weeks_ (almost the number of issues in created in the past three _years_), purely because I thought nerdamer was a library which is active enough to depend my app on.)

**Comment by jiggzson** [comment]
>(Wow... 211 vs 137. Sometimes it is weird to look back at how many issues I have created over the past three weeks (almost the number of issues created in the past three years), purely because I thought nerdamer was a library which is active enough to depend my app on.)

There are other libraries out there. You could always look into one of them. Maybe they suit your needs better.

**Comment by Happypig375** [comment]
>There are other libraries out there.

### I have looked at all of them:

#### Background Information:
I started programming with Visual Basic.NET, because that language has the word "basic" in its name and works on my Windows machine (Old memories...)
When I wanted to create a mobile app, I wanted to reuse my existing knowledge of the .NET platform.
With [Xamarin](xamarin.com), I am able to create mobile apps with .NET APIs that I know of with C#.
When I looked into Xamarin, I saw [Xamarin Forms](xamarin.com/forms). Cross-platform UI for iOS, Android, Windows Phone and Windows 10 with shared C# code? Woohoo!

#### And now...
I want to create an app with symbolic algebra calculation which can supplement my calculator.
I first looked at .NET symbolic math libraries, but there were only two of them:
- [Math.NET Symbolics](github.com/mathnet/mathnet-symbolics)
**Denied**: [It is written in pure F# which is known to not work on Windows Phone/Windows 10](https://github.com/Microsoft/visualfsharp/issues/1096)
- [Symbolism](github.com/dharmatech/Symbolism)
**Denied**: [No parser, no usefulness](github.com/dharmatech/Symbolism/issues/4)

Then I found the [Wolfram .NET/Link API](reference.wolfram.com/language/NETLink/tutorial/Introduction.html)
**Denied**: [Absolute overkill, too costly](www.wolfram.com/development-platform/pricing/)

Sigh... I could not find a symbolic math library for my app... Wait! [iOS](developer.xamarin.com/api/namespace/JavaScriptCore/), [Android](developer.xamarin.com/api/member/Android.Webkit.WebView.EvaluateJavascript/p/System.String/Android.Webkit.IValueCallback/) and [Windows Phone/Windows 10](docs.microsoft.com/en-us/scripting/chakra-hosting/reference-javascript-runtime) all support evaluating JavaScript natively!!! Yay!

When I first searched for a JavaScript symbolic math library, I stumbled upon [Algebrite](algebrite.org) which has [a list of JavaScript CAS libraries at the bottom of its home page](algebrite.org/#References).
I cannot use the Node Package Manager, because, well, I do not use Node! Node is too big to evaluate in Android phones (it is designed to be run on a server). I use git submodules.
Here is a list of them:
- [Algebrite](github.com/davidedc/Algebrite)
- [Coffeequate](github.com/MatthewJA/Coffeequate)
**Denied**: They are written in CoffeeScript.
            Yes, I know CoffeeScript can be compiled into JavaScript, but either I have to do it myself, which I do not want to do (it complicates the build process of my app), or wait for the library to compile it.
            Algebrite's [build commit](github.com/davidedc/Algebrite/commit/f9e69dec052154d286adeabb5532f2f42414d63b) and [its latest change in code](github.com/davidedc/Algebrite/commit/b3620418a5daba9e051fb84841758e53999bef5e) have a two month gap between them!
            Coffeequate does not even have its library compiled into JavaScript on GitHub!
- [javascript-cas](github.com/aantthony/javascript-cas)
**Denied**: Dead library. [Latest change](github.com/aantthony/javascript-cas/commit/d13ca4eb1a8aee3b712a8d48e06280b87bf96ed3) is from May 3 2014, which is over 3 years ago.
- [Algebra.js](github.com/nicolewhite/algebra.js)
- [Polynomial.js](github.com/infusion/Polynomial.js)
**Denied**: Too small. They do not even have the very important trigonometry functions.
- [Mathsteps](github.com/socraticorg/mathsteps)
**Denied**: Mathsteps requires Node version > 6.0.0. Did I say I do not use Node?
- [Kas](github.com/Khan/KAS)
- [Math.js](github.com/josdejong/mathjs)
**Denied**: Their code contain explicit references to the window object. I can use [a JavaScript interpreter](github.com/sebastienros/jint) in case of bugs in the native platform implementations, but it is an interprter, not a web view or a browser. It does not define a window object.

Soo... When all the others have fundamental issues, the only option left is Nerdamer.
And so I ended up with Nerdamer. 😉
