### ISSUE TITLE
Documentation: nerdamer

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#138]
The parameter option contains additional options.
Is there only 2 options ('expand', 'numer')? I can't find a list of all options.
What is the difference between the 'expand' option and surrounding the expression in expand()? 
What is the difference between the 'numer' option and calling evaluate()?

**Comment by jiggzson** [comment]
Those are currently the only two options. expand() is a convenience function. evaluate() is similar but you can pass it an optional object with known values. I'll update the documentation to reflect this.

**Comment by jiggzson** [comment]
Can this be closed?

**Comment by Happypig375** [comment]
>Those are currently the only two options. 
I'll update the documentation to reflect this.

Done this yet?
