### ISSUE TITLE
Implement arg and conjg

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#142]
arg (https://en.wikipedia.org/wiki/Argument_(complex_analysis)) and conjg (https://en.wikipedia.org/wiki/Complex_conjugate) are pretty important for complex number calculations.

**Comment by jiggzson** [comment]
I've been wanting to add these for some time but I just lacked the motivation since nobody asked :laughing:. I'll add these to the list for the next version.

**Comment by Happypig375** [comment]
Moved to #181.
