### ISSUE TITLE
fib() returns 1 for negative numbers and 0

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#143]
So the sequence is like...

fib(-4)|fib(-3)|fib(-2)|fib(-1)|fib(0)|fib(1)|fib(2)|fib(3)|fib(4)|fib(5)
-|-|-|-|-|-|-|-|-|-
1|1|1|1|1|1|1|2|3|5

Don't think it should evaluate.

**Comment by jiggzson** [comment]
You mean that it should give back a negative number. Whenever I'm unsure I use either Wolfram Alpha or Maxima for reference. In fact I use them extensively to build tests for very complex derivatives, integrals, etc before solving them by hand. Can we use their results as a base point going forward?

**Comment by Happypig375** [comment]
Wolfram Alpha and Maxima:

fib(-4)|fib(-3)|fib(-2)|fib(-1)|fib(0)|fib(1)|fib(2)|fib(3)|fib(4)|fib(5)
-|-|-|-|-|-|-|-|-|-
-3|2|-1|1|0|1|1|2|3|5

**Comment by Happypig375** [comment]
This equation would be the most appropriate:
fib(x) = (-cos(x pi)+e^(acsch(2)))/e^(0.5acsch(2)sqrt(5))

**Comment by Happypig375** [comment]
#121 would be helpful because acsch() is currently not there.

**Comment by jiggzson** [comment]
Interesting. I've never seen that formula before. It seems like acsch in the above example is not needed since it's a constant and you can use its numeric value instead. My biggest concern however with this method is the floating point issues which may arise from this.

**Comment by Happypig375** [comment]
Oh wait nevermind, I found a simpler equation: (((1+sqrt(5)/2)^x-(2/(1+sqrt(5))^x)cos(pi x))/sqrt(5)

**Comment by Happypig375** [comment]
https://github.com/jiggzson/nerdamer/compare/dev#diff-f0bc61ebf4a3fbe84b62105fdbc1b369R860

Output:
fib(-4)|fib(-3)|fib(-2)|fib(-1)|fib(0)|fib(1)|fib(2)|fib(3)|fib(4)|fib(5)
-|-|-|-|-|-|-|-|-|-
-3|-2|-1|-1|0|1|1|2|3|5

It should only be negative for negative __even__ input.

**Comment by Happypig375** [comment]
>I found a simpler equation

I just found that Wolfram Alpha supports plaintext output (facepalm):
((1/2 (1 + sqrt(5)))^x - (2/(1 + sqrt(5)))^x cos(π x))/sqrt(5)

**Comment by Happypig375** [comment]
Ok for now, but if decimal input is supported then it will be better.

**Comment by jiggzson** [comment]
I'll go ahead and add decimal input. I like the formula you provided. I'll switch to this formula when the input is a float since this one introduces floating point errors.

**Comment by Happypig375** [comment]
>I'll go ahead and add decimal input.

Version 0.7.13 says no.
nerdamer('fib(2.4)').evaluate() => 1
