### ISSUE TITLE
log with non-standard base

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#150]
My calculator does this using this syntax: log(base, number)
Alternate syntax (more consistent with log(number) but inconsistent with calculator): log(number, base)

**Comment by jiggzson** [comment]
I like. I'll add this.

**Comment by Happypig375** [comment]
Confirmed in https://github.com/jiggzson/nerdamer/commit/624b5b310c058f22f908140c190a2a5f71ba457b#diff-f0bc61ebf4a3fbe84b62105fdbc1b369R3705. However, there is a rounding error:
nerdamer('log(3,9)').evaluate().text('decimal') => 0.4999999999999999

**Comment by Happypig375** [comment]
and nerdamer('log(9,3)').evaluate().text('decimal') => 2.0000000000000004

**Comment by jiggzson** [comment]
I added a fix for this one. It basically doesn't eliminate rounding errors but pushes it way to the back. The downside is that it's pretty slow. I'll probably run some tests and see if it's worth spending some more time on or feel free to test it. Let me know if you're happy with the result.
