### ISSUE TITLE
Documentation: zscore example is showing stdev

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#151]
>var x = nerdamer('smpvar(4,2,5,4)').evaluate();
console.log(x.text());
x = nerdamer.smpvar('x', 'r+1', '21', 'tan(x)', 'r+1');
console.log(x.toString());
x = nerdamer.smpvar('11', '12', '13', '14').evaluate();
console.log(x.text());

It should be showing a zscore example

**Comment by jiggzson** [comment]
Nice catch! Thanks.

**Comment by Happypig375** [comment]
Another thing: zscore is in the demo functions list but not in documentation.

**Comment by Happypig375** [comment]
>x = x.evaluate()

Missing semicolon?

**Comment by jiggzson** [comment]
See #247
