### ISSUE TITLE
Custom operators

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#154]
#45 has a partial solution to this, but it
1. is too verbose
2. cannot add a postfix operator

Can you implement a nerdamer.setOperator (and possibly getOperator - #147) convenience function and add support for postfix operators?

I need it to support angle units (done by converting postfix operators °/ʳ/ᵍ to a specified angle unit defined by global state, then converting to radians when sin/cos/tan is enciuntered).

**Comment by jiggzson** [comment]
Yes. I can. In fact #131 already caused me take another look at this without the user needing to touch the core. Another issue that comes up is the fact that currently using this solution, the operator doesn't get retained. So for instance, after setting % as the mod operator and passing the expression '5%m' to nerdamer, it will return 'mod(5, m)' when requesting it back as a string. Additionally as per #147, getters need to make sense. What exactly do you expect to get back from getOperator? The Operator object? A string? To do what with? Please explain so I return useful information from the getter.

**Comment by Happypig375** [comment]
Something like: getOperator('+') => Operator object +
Example usage: Changing the order of + without needing to create my own function of +

Speaking of orders, the documentation of setOperator should list out the default order.

**Comment by Happypig375** [comment]
By the way, if Operator objects are the way to go, Operator's second argument should also take a function in addition to string, and an additional paraneter to declare as postfix operator.

**Comment by Happypig375** [comment]
And make Operator available as nerdamer.Operator().

**Comment by jiggzson** [comment]
> And make Operator available as nerdamer.Operator().

Are you talking about the operator class? That's already available when getting the core. 
```javascript
var Operator = nerdamer.getCore().Operator;
```

**Comment by jiggzson** [comment]
Added but no documentation or tests yet. I'll try to get to this tomorrow.

**Comment by jiggzson** [comment]
**USAGE**

```javascript

//MODIFYING AN EXISTING OPERATOR
var operator = nerdamer.getOperator('+');
operator.precedence = 9;
nerdamer.setOperator(operator);
console.log(nerdamer('1+2*3').toString());


// CREATING A NEW OPERATOR
var _ = nerdamer.getCore().PARSER;
var operator = { 
    precedence: 9,
    operator: '&',
    action: 'amp',
    prefix: true,
    postfix: false,
    leftAssoc: false
};
var action = function(a, b) {
    return _.subtract(a, b);
};
nerdamer.setOperator(operator, action);
console.log(nerdamer('5&2').toString());


//ALIASING AN EXISTING OPERATOR
nerdamer.aliasOperator('*', '×');
console.log(nerdamer('5*2×4').toString());
```
