### ISSUE TITLE
Unify the places for version history

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#156]
0.5.6 ~ 0.5.8: https://github.com/jiggzson/nerdamer/wiki/Versions
0.6.0: http://nerdamer.com/#comment-2599980644 (Wait for Disquz to load!)
0.6.6: http://nerdamer.com/#comment-3127251646 (Wait for Disquz to load!)
0.7.x: https://github.com/jiggzson/nerdamer/issues/77

Can we have a unified place for them?

**Comment by jiggzson** [comment]
The version history is mainly tracked through Github. I'll try to release code on both Github and npm from now on.

**Comment by Happypig375** [comment]
>The version history is mainly tracked through Github.
Where?

**Comment by ljacqu** [comment]
Tags in Git will show as "Releases" in GitHub; that might be an idea?

**Comment by jiggzson** [comment]
@ljacqu Sounds good. I just haven't been releasing them in sync with npm. I'll just make sure to do them both at the same time and utilize the tags as you suggested.

**Comment by Happypig375** [comment]
So this is related to #158. However the releases on Github Releases don't seem to have a change log. So they are not very helpful.

**Comment by jiggzson** [comment]
I'll add a change log going forward

**Comment by Happypig375** [comment]
0.7.13 is released, remember to tag it!

**Comment by Happypig375** [comment]
>0.7.13 is released, remember to tag it!

And also 0.7.14 when it is finished.

**Comment by jiggzson** [comment]
I've made a note of this. As stated before I'll do my best to keep up with this going forward. Closing.

**Comment by Happypig375** [comment]
Remember to tag 0.7.14 on GitHub Releases

**Comment by Happypig375** [comment]
>Remember to tag 0.7.14 on GitHub Releases

Bump

**Comment by Happypig375** [comment]
As you remember to release on GitHub, you forgot to release on npm. Argh

**Comment by jiggzson** [comment]
Yes. I'll release @0.7.15. I haven't released on npm for quite some time.
