### ISSUE TITLE
Determinant and Inverse Matrix

### ISSUE THREAD

**Issue by CesMak** [jiggzson/nerdamer#160]
Hey there,

 just wanna ask if its possible to compute the inverse of a Matrix?
    nerdamer.setVar('M', 'matrix([1, 2], [2, 3])');
    var x = nerdamer('M^(-1)');
    console.log(x.toString());

// matrix([1,1/2],[1/2,1/3])  -> which is wrong!

Also would like to have a determinant calculation function 

Best
Markus

**Comment by jiggzson** [comment]
Have you tried nerdamer('inverse(M)')?

**Comment by CesMak** [comment]
That gives me: matrix([inverse,2*inverse],[2*inverse,3*inverse])

**Comment by jiggzson** [comment]
I'm sorry I meant invert. I'm responding while on the road.

**Comment by CesMak** [comment]
Yeah sorry I just saw it here: http://nerdamer.com/functions/invert.html

nerdamer.setVar('M', 'matrix([1, 5], [4, 4])');
var x = nerdamer('invert(M)');
console.log(x.toString());

But I still cannot find a determinant feature That would also be really nice :)

**Comment by jiggzson** [comment]
Have you tried nerdamer('determinant(M)')?

**Comment by CesMak** [comment]
nerdamer.setVar('P', 'matrix([1, 2], [2, 3])');
  var u=  nerdamer('determinant(P)');
    console.log(u.toString());

matrix([determinant,2*determinant],[2*determinant,3*determinant])

I did not find determinant in your documentation as well.....

**Comment by jiggzson** [comment]
I'll take a look at this shortly.

**Comment by CesMak** [comment]
If you are on it another nice feature would be size(Matrix)

**Comment by jiggzson** [comment]
Apparently I do have some matrix functions which are in the source but were never added to the functions list. I'll go ahead and add them but I'm having a bit of a time crunch for the next few weeks so give me a few days or so. If you must have this now please add the following entry to the functions array in the nerdamer.core.js file

```javascript
'determinant'       : [ determinant, 1],
```
It starts somewhere around line 2668. I'll make sure to add the size function as well.

**Comment by jiggzson** [comment]
Added determinant, size, and imatrix.

**Comment by jiggzson** [comment]
@CesMak, did this solve your issue?
