### ISSUE TITLE
acosh(1/23.12) throws

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#161]
Sorta related to #157.
This, instead of not evaluating, throws a fat exception to my head.

**Comment by Happypig375** [comment]
Wolfram Alpha:
1.527530234207861561102705973013356806073903934950987570989... i

**Comment by jiggzson** [comment]
Update: 
I've updated the function on the dev branch. Nerdamer no longer throws but there is a rounding error at the end as result. Any investigating as to what causes this would be greatly appreciated. The acosh function uses **log(x+sqrt(x^2-1))**

**Comment by Happypig375** [comment]
Merge into #181
