### ISSUE TITLE
despite names being similar, factor does not play well with factorial

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#164]
Taking an example from Algebrite (the library linked beside the home page):

`factor(100!) => 2^97 3^48 5^24 7^16 11^9 13^7 17^5 19^5 23^4 29^3 31^3 37^2 41^2 43^2 47^2 53 59 61 67 71 73 79 83 89 97`

In contrast with nerdamer:

`factor(100!) => 17*2^474*3^3*4168434910597`

What is with the really big number at the end!?

**Comment by Happypig375** [comment]
pfactor(100!) => (11^9)*(13^7)*(17^5)*(19^5)*(23^4)*(29^3)*(2^97)*(31^3)*(37^2)*(3^48)*(41^2)*(43^2)*(47^2)*(53)*(59)*(5^24)*(61)*(67)*(71)*(73)*(79)*(7^16)*(83)*(89)*(97)

The order is a bit arbitrary...

**Comment by jiggzson** [comment]
>The order is a bit arbitrary...

Yep. Nerdamer builds directly on JavaScript objects. Because JavaScript object do not guarantee an order, neither does nerdamer. I can add a sort function for text output maybe.

**Comment by jiggzson** [comment]
I added the sort function so this issue should now be done. I'll add a note to document the sort function

**Comment by Happypig375** [comment]
Sort function... Probably can also be an option in addition to numer and expand.

**Comment by jiggzson** [comment]
Yes it could be. But remember that sort returns a vector so it might not fall in the same category.
