### ISSUE TITLE
List of functions that are in the demo supported functions list but not in documentation

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#165]
1. IF
2. div
3. gamma_incomplete
4. parens
5. setEquation
6. sign
7. zscore

1, 5, and 6 do not even have corresponding pages.
3 is missing important parameter information in the page.
Is 2 a synonym to divide like fact is to factorial?

(Reference to #151)

**Comment by jiggzson** [comment]
Some functions show up in the list because they're in the experimental stage. I should probably exclude the ones which aren't ready for use.

**Comment by jiggzson** [comment]
**div** is not a synonym for **divide**.  div return the result as [w, r] whereas divide returns the division as w+r/d, where _w = whole, r = remainder, d = divisor._

**Comment by Happypig375** [comment]
div(10, 3) => [10/3, 0] ?? Looks like a bug...

**Comment by Happypig375** [comment]
div and gamma_incomplete are still not available in documentation.

**Comment by jiggzson** [comment]
Some functions are deliberately left out of documentation because they aren't officially supported.
