### ISSUE TITLE
buildFunction

### ISSUE THREAD

**Issue by brosnanyuen** [jiggzson/nerdamer#17]
Extend buildFunction for functions outside the core.

**Comment by jiggzson** [comment]
I'm revisiting this issue. It's been a while. I know we discussed this and one of my concerns was that there was no clear way to handle functions that return symbolic values. I'm guessing you're only talking about functions that return numeric values. Am I correct?

**Comment by jiggzson** [comment]
Sorry for the super late reply but I think I finally understand the reason for this issue. I imagine this is related to the functions contained in the Special add-on. For example the sinc function. When creating function which are primarily numeric functions it's better to create them in the Math2 object. This way nerdamer will automatically connect them when the buildFunction method is called. In the case of sinc it would be something like this.

```javascript
var core = nerdamer.getCore();
core.Math2.sinc = function(x) {
    if(x === 0)
         return 1;
    return Math.sin(x)/x;
}
```
Nerdamer then automatically takes care of the symbolic part and the function now is available to the buildFunction method. I'll be refactoring the functions in the special add-on in this fashion. Hopefully that clears this issue.

**Comment by jiggzson** [comment]
I made the changes in the dev branch
