### ISSUE TITLE
@ljacqu

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#170]
#131:
>Hi guys, I'm always up for writing tests! You're welcome to @mention me anytime. I appreciate it if you could let me know what new feature is introduced that could be tested as it's hard to tell from the commits sometimes (without spending a lot of time).

Here are features added in #168:
- #3
- #121 (Partial, only asech and acoth implemented)
- #131 
- #135
- #143 
- #145 
- #149 
- #150 
- #154 
- #160

**Comment by Happypig375** [comment]
@ljacqu Response?

**Comment by ljacqu** [comment]
Thanks. Still not home long enough but managed to sift through the issues. I'll try to add tests for the following:
div #165
factor(0) #224
Invalid Solve Result #220
log with non-standard base #150
? Make solveEquations available inside nerdamer(string) #186
The real pi (π) does not evaluate to the fake pi (pi) #135
pfactor(2*sin(pi)) results in unresponsive script #124
? gcd does not like variables #123
factor regressions on dev branch #223

**Comment by Happypig375** [comment]
For #186, note #213 and #214.

**Comment by Happypig375** [comment]
Oh I see, some of them are not yet implemented and you are writing tests for them in advance. I am not used to writing tests so I might do them with a long time, usually hours, so I only write them on request (and when I have time). Opening issues are far easier and convenient, as I usually encounter bugs through my nerdamer-integrated app.

**Comment by ljacqu** [comment]
I'm afraid I can't keep up with all the changes that happened and I'd like to ask for this issue to be closed. The commits on master have no description outside of referencing a dozen of issues and I don't have the time/interest to comb through those huge commits just to write tests.

**Comment by Happypig375** [comment]
Ok
