### ISSUE TITLE
Consider support for omitting brackets with functions

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#182]
The two comments after the issue was closed is indeed interesting, but seem to have been forgotten. Reconsider it.

**Comment by jiggzson** [comment]
What's wrong with it?

**Comment by Happypig375** [comment]
I meant reconsidering *the two comments and dropping unnecessary brackets*, not the fix or issue is wrong.

**Comment by jiggzson** [comment]
So **sin x sin x**. Does the user mean sin(x*sin(x))? or sin(x)*sin(x). This would then require switching to a rule based parser.

**Comment by Happypig375** [comment]
Wolfram Alpha:
sin x sin x => sin(x)sin(x)

**Comment by jiggzson** [comment]
@Happypig375, I've been trying different ways of implementing this during the rewrite but there are two major problems.
1. close and open brackets are the same (assuming space denotes close)
2. close bracket might not exist at all

Every solution I've tried either requires me to implement a different parser/parsing algorithm which would require a complete rewrite of the library (something I'm in no position to do in foreseeable future) or works, but seems to introduce an large number of bugs (which takes away available time from more pressing issues). I'll leave this issue open and I'll keep it in mind but I'm shelving it for the time being.

**Comment by Happypig375** [comment]
It seems that Wolfram Alpha is following such a rule:
If the first non-whitespace character is not a bracket, then read until the next whitespace that is not consumed by another function and on the same bracket level.
E.g.

In|Out
-|-
sin x|sin(x)
sin x sin x|sin(x)sin(x)
sin sin x|sin(sin(x))
sin 2x|sin(2x)
sin 2 x|sin(2)x
sin x2|sin(x2)
sin x 2|sin(x) 2

**Comment by ljacqu** [comment]
Just to weigh in, I assume that the burden on the code base to support this in a long-term, maintainable way is not worth the gain.

**Comment by jiggzson** [comment]
@ljacqu, that was my point exactly. I was excited with the initial run but then all kinds of strange bugs crept in. Had the underlying parser implementation been a bit more robust I probably would have been a much easier task but making the switch at this point quite a large undertaking. @Happypig375, I have been giving it a bit more thought and I might be able to manipulate the input string a bit before actually parsing it. 

@ljacqu, I've noticed that tests don't automatically run on commit anymore. Do you know what's causing this by any chance?

**Comment by jiggzson** [comment]
@Happypig375, I know it's been a while since we discussed this issue but I'm finally having some time again and I'm revisiting the more challenging issues to see if I can tackle them. Just letting you know that this one should now be fixed.

**Comment by Happypig375** [comment]
`sin x cos x` => `x`
`sin x cos y` => `x`
?

**Comment by Happypig375** [comment]
According to Wolfram Alpha,

Input|Expected|Actual
-|-|-
sin 2x | sin(2x) | sin(2)x
sin 2 x | sin(2)x | sin(2)x

**Comment by jiggzson** [comment]
I'm not sure if I'm trying to emulate Wolfram Alpha in this case but I do agree with your expected outputs in this case. Thanks.

**Comment by Happypig375** [comment]
Wolfram Alpha is just supporting precedence. However, it usually is an good indicator of how normal humans tend to think of these features.

**Comment by jiggzson** [comment]
@Happypig375, I've addressed all of the cases you mentioned with the exception of `sin sin x`. This has to do with the fact that `sin` although discouraged, can in fact be used as a variable name. I actually vaguely recall going through great lengths to support this because it relates to recursive variable substitution (I can't recall any examples ATM). Maxima allows for the ability to use function names as variables as well so I don't think it's unreasonable. 

Wolfram Alpha for instance, returns `sin(x)^2` for `sin(x)*sin`. Where in the world did the second x come from? 

Personally, omitting the bracket should be avoided altogether IMHO since it makes expressions very difficult to read but I guess it's a preference thing.

Let me know if you can think of any more cases to test and thanks again for your help. Please close if you think this one is good to go.

**Comment by jiggzson** [comment]
@Happypig375, I think I now cover all cases. Let me know if you find anything. Thanks.
