### ISSUE TITLE
Documentation: When you document the functions, also document the operators!

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#184]
This can give users an idea of what operators nerdamer supports, not just functions.

Operators that I know of:

- \+
- \-
- \*
- /
- ^
- !
- %
- =
- :=
- (
- )
- [
- ]
- .
- ,
- <
- <=
- ==
- !=
- \>
- \>=

**Comment by jiggzson** [comment]
Moving to #183.

**Comment by jiggzson** [comment]
@Happypig375 You're right. I renamed Issue #141 so I'll be moving it there. I'll be moving all documentation related issues there.
