### ISSUE TITLE
Support for other angle units

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#185]
Initial motivation for #154.
Currently only radians are supported in functions taking/returning an angle for input/output. 
It would be better if degrees and gradians are supported as well.
Initially I thought of implementing this as custom operators,
but I think this can benefit others if it is supported directly.
Could be a global setting of angle unit:
```
nerdamer.set('ANGLE_UNIT', 'degrees');
nerdamer.set('ANGLE_UNIT', 'radians'); //current setting
nerdamer.set('ANGLE_UNIT', 'gradians');
nerdamer.set('ANGLE_UNIT', 'turns'); //maybe this as well?

**Comment by jiggzson** [comment]
See issue #230

**Comment by Happypig375** [comment]
#255: 
>#185 is for a global setting since angle units, take radians for example, is m m^-1, aka no unit.

#230:
>they should be converted to SI units where possible.

m m^-1 will equate to no unit. How will degrees be differentiated with radians? I prefer a global setting.
