### ISSUE TITLE
! is a valid infix operator!?

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#188]
Let me see...
1!1 => 1
2!1 => 2
1!2 => 1
2.3!1.4 => 2.3
x!y => x

I call it the comment operator.
What an interesting operator!
Why isn't it documented?

`</sarcasm>`

**Comment by Happypig375** [comment]
Maybe change the meaning of x!y to x!*y as in https://github.com/jiggzson/nerdamer/issues/131#issuecomment-323742308.

**Comment by jiggzson** [comment]
Interesting. #130, #131, #154 are probably all related.

**Comment by Happypig375** [comment]
From https://github.com/jiggzson/nerdamer/issues/45#issuecomment-238129495:
>//create a blank operator so the operator knows it's an operator 
//because the parser only sees one character at a time

Related?

**Comment by jiggzson** [comment]
Yep. All related. Which begs the question if it's time for a full parser.

**Comment by Happypig375** [comment]
>full parser

If you rewrite the parser, also solve #119 and #182 at the same time.

**Comment by Happypig375** [comment]
And now...
5% => 0.05
3%4 => 3
a%b => a

**Comment by jiggzson** [comment]
>And now...
5% => 0.05
3%4 => 3
a%b => a

I'll fix this with the next major parser update

**Comment by jiggzson** [comment]
Related to #130
