### ISSUE TITLE
Infix operators are okay with only the left argument

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#191]
1+ => 0
1- => 0
1* => 0
1/ => 1 (weirdly)
1^ => 0
1, => 1 (huh)

But...
*1 throws
/1 throws
^1 throws
,1 => 0

And...
\+ => 0
\- throws a weird error: TypeError: Unable to get property 'negate' of undefined or null reference
\* throws with Error: * is not a valid prefix operator
/ throws with Error: / is not a valid prefix operator
^ throws with Error: ^ is not a valid prefix operator
, => 0

Is this intended?
The error message 'not a valid prefix operator' is a bit misleading...

**Comment by jiggzson** [comment]
Fixed in 7ce9240
