### ISSUE TITLE
Bracket errors have typing errors

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#192]
nerdamer('(') throws Error: Unmatched close bracket for bracket )!
nerdamer('[') throws Error: Unmatched close bracket for bracket ]!

nerdamer(')') throws Error: Unmatched open bracket for bracket ')'!
nerdamer(']') throws Error: Unmatched open bracket for bracket ']'!

1. Quotes are missing around the brackets in the first two
2. They should be open brackets

**Comment by jiggzson** [comment]
Noted. Thanks.

**Comment by Happypig375** [comment]
This was an easy one 😆  thanks though
