### ISSUE TITLE
pfactor with complexes/variables result in 1

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#199]
pfactor(2+a) => 1

Even without the evaluate call, it still directly replaces pfactor(2+a) with 1.
It should not evaluate for variables, and pfactor(8+8i) should be pfactor(8)+pfactor(8)i, aka 2^3+2^3i.

**Comment by jiggzson** [comment]
>pfactor(8+8i) should be pfactor(8)+pfactor(8)i, aka 2^3+2^3

This would give the impression that i is a prime number.

**Comment by Happypig375** [comment]
You missed the i. It is 2^3+2^3**i**, not 2^3+2^3.

**Comment by Happypig375** [comment]
>This would give the impression that nerdamer thinks that i is a prime number.

pfactor(1) and pfactor(0) do not give correct primes either.

**Comment by jiggzson** [comment]
They give 1 and 0. What did you expect it to give?

**Comment by Happypig375** [comment]
If pfactor(1) => 1 and pfactor(0) => 0,
then pfactor(8+8i) might evaluate to 8+8i or something.
The obviously not-prime 8 can still be seen though.
So (2^3)+(2^3)i is suggested.
