### ISSUE TITLE
What will be included in the next update?

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#202]
Just asking, I will make workarounds for acsc etc. if they will not be included in the next update. And when will it be out? (Can it be in a month or so?)

**Comment by jiggzson** [comment]
I think I should be able to have those soon. A month is very doable given present circumstances. In fact it would be very helpful if we can add tests and close out some of the issues that have been handled since. Giving me an order of priority would also help. Right now we have 65 open issues. Some of them are just nice-to-haves and some are more critical.

**Comment by Happypig375** [comment]
>add tests

#206 (Took me two hours)
> close out some of the issues that have been handled since

Tests need to be added before closing them or bugs will be overseen. 
@ljacqu Where are you? You said you were always up for writing tests and I am welcome to @mention you anytime. ~(Ohh... mention only, not that you would actually show up. Now I get it.)~ (To self: Don't be mean.)
>Giving me an order of priority would also help

1. Bugfixes (Especially plain wrong results like #123), e.g.
1.0 #123 (Obviously)
1.1 #186 (I have had a few instances where I was like "hmm... I am going to use solveEquations(). Oh wait...)
1.2 #124 (Literally browser-breaking)
1.3 #197 (Easy fix?)
1.4 #161 (That throw is unexpected)
2. Important features (Would list #154 but it is almost done, just tests and docs left), e.g.
2.1 #196 (This is not just for myself but also to make nerdamer remain competitive)
2.2 #119 (I do not want my brain to choose whether to use / or divide())
2.3 #126 / #129 (They are related I think)
2.4 #181 
2.5 #121 (In progress)
3. Performance (I haven't checked on this yet, but should not be a problem for now)
4. Smaller features (there are a lot)
5. Website and Documentation (When someone is new to nerdamer, they will first look at the website. When I first saw nerdamer, I was already spotting issues like #119. Fortunately, you quickly responded, letting me know that this library is active and the issues could be fixed.)

**Comment by ljacqu** [comment]
> (Ohh... mention only, not that you would actually show up. Now I get it.) (To self: Don't be mean.)

lol :P I'm leaving for vacation _today_ so in about a month I'll contribute with the test cases. I meant it, and hopefully jiggzson can vouch for my reliability (not to confuse with speed ;)).
I also appreciate the issue you directed at me, it's on my list and I will handle it. I was hoping for a little more specific additions so it will take me some time to sift through all the changes. Nerdamer isn't my main passtime ;)

**Comment by jiggzson** [comment]
Yes, I vouch for @ljacqu. @ljacqu, enjoy your vacation. Pretty soon I'll need one myself lol.

**Comment by jiggzson** [comment]
The majority of the issues are fixed and remaining issues are part of the roadmap. Refer to roadmap or individual issues.
