### ISSUE TITLE
Bring function/variable defining from the demo to the library

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#203]
>To enter an expression just type it in the box below with the format: expression;variable=value e.g. cos(x)+1,x=PI
To define a function type in f(parameters):=function_body, e.g. f(x):=tan(x)/x^2. 
To define a variable type in variable:value, e.g. x:5 

These are demo-only features. Can they appear in the library itself?

**Comment by jiggzson** [comment]
See #247

**Comment by Happypig375** [comment]
If this were to be implemented, the syntaxes should be modified to be unified.
One possible syntax is:
```
x:=6 //Instead of x:6
f(x):=x^2 //Unchanged
cos(x)+1,x:=pi //Instead of x=pi
```
to match the new :<, :in etc.

Another possible syntax is the above but x:6, f(x):x^2 etc. are also permitted.

What do you think?

**Comment by jiggzson** [comment]
Yes. I remember us discussing this before and I'm going to reopen this. The idea was to revisit this during the parser rewrite. I'm still debating the rewrite since I strongly feel that I can still use the current algorithm with a few tweaks.

**Comment by jiggzson** [comment]
@Happypig375, added.
