### ISSUE TITLE
Demo: Where is the expand button?

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#204]
Demo Instructions:
>Check the expand button to expand the expression. 

Where is the button?

**Comment by jiggzson** [comment]
It's supposed to be checkbox. I'll fix that.

**Comment by jiggzson** [comment]
Fixed.

**Comment by jiggzson** [comment]
This is noted in #247. Closing and this will be handled there.

**Comment by jiggzson** [comment]
Sorry. This is a holdover from the old demo. Just wrap your expression in the expand function.
