### ISSUE TITLE
Permit trailing underscores in demo

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#205]
nerdamer('log_').toString() => log_

demo:
log_ => ParseError: KaTeX parse error: Expected group after '_' at position 4: log

KaTeX renders log_2 as log₂. Is this intended? It works like a normal variable: 
log_2(4) => 4*log_2

**Comment by jiggzson** [comment]
I don't think this is related to nerdamer. This has to do with KaTeX. Underscores do cause the following character to be rendered as subscript. That's just how it's rendered in LaTeX. Again nothing to do with nerdamer. I'll close this issue.

**Comment by Happypig375** [comment]
Continued at #232.
