### ISSUE TITLE
Change setVar('var', 'delete') to setVar('var', '')

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#207]
Think about this.
setVar('var', 'delet') sets var to 'delet'
setVar('var', 'deletee') sets var to 'deletee'
But setVar('var', 'delete') deletes var.
So I cannot set var to 'delete'.

What about instead of passing 'delete' to the second argument, pass '' to it? 
Passing '' to the second argument currently sets var to 0, which make no sense.
If I want to set it to 0, I would pass '0'.

**Comment by jiggzson** [comment]
This one should be done.

**Comment by Happypig375** [comment]
And document that setting the value argument will delete the variable.

**Comment by Happypig375** [comment]
Eh... fine... 'delete' for deleting the variable is for backwards compatibility. Closing this and #139.
