### ISSUE TITLE
Make nerdamer.expressions also return input expression?

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#208]
A nice to have really, filing it before it becomes forgotten.

**Comment by jiggzson** [comment]
I'm not sure I understand this one.

**Comment by Happypig375** [comment]
nerdamer.expressions returns an object or array of processed expressions (output expressions), but nerdamer does not return the raw input (input expression). Kinda like what the reload expression button in demo returns, but for all expressions nerdamer has ever processed (the not deleted ones).

**Comment by jiggzson** [comment]
@Happypig375 Can you not implement this outside of the library?

**Comment by Happypig375** [comment]
Yes I can implement this outside the library trivially, but the demo has it, and is inconsistent with the actual library not having it.

**Comment by jiggzson** [comment]
I think people confuse the library with the demo quite frequently. The demo is an entirely separate program. Implementing certain functions inside of the library means that every single call incurs the cost of that implementation vs you implementing it means that you control that cost. Remember that nothing is free.
