### ISSUE TITLE
Dedicated helper functions to get/set a row/column of a matrix (2D tensor)

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#209]
A nice to have, inspired by [this Algebrite issue](http://github.com/davidedc/Algebrite/issues/51).

**Comment by jiggzson** [comment]
If I'm understanding correctly, 
given:
M = matrix([1,2,3], [4,5,6], [7,8,9]);
getVectorColumn(M) -> [3, 6, 9];

Is that right?

**Comment by Happypig375** [comment]
You missed the second argument: getVectorColumn(M, 2) => [3, 6, 9]
where 2 is the zero-based index

I think getVectorColumn(M, 2) is too long.
Maybe matget(M, -1, 2)?
Row would be matget(M, 2, -1).

**Comment by jiggzson** [comment]
The helper functions for this have been created. I created new names since I found the negative indexing a bit confusing. Below are the examples
```javascript
nerdamer.setVar('M', 'matrix([1,2],[3,4])');
var row = nerdamer('matgetrow(M, 1)');
console.log(row.toString());
var col = nerdamer('matgetcol(M, 0)');
console.log(col.toString());
//this creates a new vector so M is not modified
var M1 = nerdamer('matsetrow(M, 0, [a, b])');
console.log(M1.toString());
//this creates a new vector so M is not modified
var M2 = nerdamer('matsetcol(M, 0, [[t], [u]])');
console.log(M2.toString());
```
The above outputs

```console
matrix([3,4])
matrix([1],[3])
matrix([a,b],[3,4])
matrix([t,2],[u,4])
```

**Comment by Happypig375** [comment]
Good. Looks amazing. :+1:

Neat detail about immutability about these functions to not set traps for people 😆

**Comment by jiggzson** [comment]
Thanks. I added the fact that it returns a new matrix to gh-pages_dev branch.
