### ISSUE TITLE
Variables remember values of other variables even after deletion

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#212]
Input:
```js
nerdamer.setVar('a', 45);
nerdamer.setVar('b', 'a*a-4');
document.writeln(nerdamer("a-b").evaluate().toString());
nerdamer.setVar('a', '');
document.writeln(nerdamer("a-b").evaluate().toString());
```
Output:
```
-1976
-2021+a
```

If `b` is set again:
Input:
```js
nerdamer.setVar('a', 45);
nerdamer.setVar('b', 'a*a-4');
document.writeln(nerdamer("a-b").evaluate().toString());
nerdamer.setVar('a', '');nerdamer.setVar('b', 'a*a-4');
document.writeln(nerdamer("a-b").evaluate().toString());
```
Output:
```
-1976
-a^2+a+4
```

**Comment by Happypig375** [comment]
Looks like an issue of eager evaluation when setting variables.
Should it be deferred?

**Comment by jiggzson** [comment]
I don't see why it should be deferred since a is known at the time of setting b. What did you expect the result to be?

**Comment by Happypig375** [comment]
After deleting a, the value of b should return to a*a-4.

**Comment by jiggzson** [comment]
Ok. I see what you mean. There's currently no easy way to do this due to how, as you mentioned, variable substitutions is performed. Let's see what I can do about this during the parser rewrite since this issue's got some hair on it.

**Comment by jiggzson** [comment]
I'm revisiting this issue so let's go over this step by step one more time
```javascript
nerdamer.setVar('a', 45);
//nerdamer now recognizes that a=45
nerdamer.setVar('b', 'a*a-4');
//nerdamer now recognizes that b=a^2-4
console.log(nerdamer("a-b").evaluate().toString());
//nerdamer substitutes a=45 and b=a^2-4
//which equals 45-(45^2-4) = -1976
//You're good with the output at this point.
nerdamer.setVar('a', '');
//nerdamer is now oblivious to any value of a.
//As far as it's concerned it's just another variable
nerdamer.setVar('b', 'a*a-4');
//nerdamer now knows that b=a^2-4
//next we call a-b 
//so we get a-(a^2-4) -> -a^2+a+4
console.log(nerdamer("a-b").evaluate().toString());
```
I don't see the problem.

**Comment by Happypig375** [comment]
Let me see...
(Not on a computer right now, so the following is just my prediction, may differ with actual output)
```
nerdamer.setVar('a', 45);
//nerdamer now recognizes that a=45
nerdamer.setVar('b', 'a*a-4');
//nerdamer now recognizes that b=a^2-4
console.log(nerdamer("a-b").evaluate().toString());
//nerdamer substitutes a=45 and b=a^2-4
//which equals 45-(45^2-4) = -1976
//You're good with the output at this point.
nerdamer.setVar('a', '');
//nerdamer is now oblivious to any value of a.
//As far as it's concerned it's just another variable
//nerdamer.setVar('b', 'a*a-4');
//no need to duplicate the call, b is already connected to a
//next we call a-b 
//but we get a-(a^2-4) -> 45-(45^2-4) -> -1976
console.log(nerdamer("a-b").evaluate().toString());

**Comment by Happypig375** [comment]
Use case:
```js
nerdamer.setVar('a','3');
nerdamer.setVar('b','4');
nerdamer.setVar('c','5');
nerdamer.setVar('d','b^2-4ac');
output(nerdamer('d'));

nerdamer.setVar('b','9');
output(nerdamer('d');
//watch d change with b

nerdamer.setVar('a','-7');
output(nerdamer('d'));
//now d changes with a too

**Comment by jiggzson** [comment]
Ok I remember now. The problem here is that a is known at the time of setting b. There is really no way around this. The substitution occurs when the expression is evaluated.

**Comment by Happypig375** [comment]
Awh:frowning:

**Comment by jiggzson** [comment]
The only solution I can think of is to implement this outside of the library and use that instead. It would definitely be more efficient since you would only check substitutions per expression. Currently substitutions are checked per token (kinda) so the overhead for doing multiple checks would be brutal.  Another problem I see is that the subs object is just that, an object. So the order isn't retained. You would be able to retain the order with some sort of wrapper by storing the substitutions in an array and then call nerdamer. I think we could create a gist similar to the stepper for this one. Would that be an acceptable solution?

**Comment by jiggzson** [comment]
@Happypig375, have you had a change to think this one over?

**Comment by Happypig375** [comment]
Something like this:
Don't substitute variables immediately when setVar is called

When an expression is parsed:
Copy all substitutions into temporary variable
For each substitution in that variable:
Substitute inside each substitution and the expression
Then read the substituted expression

E.g (using #203 syntax)
a^2+b, a:=4c, b:=2a+6c+d, c:=d/2, d:=44
(4c)^2+b, b:=2(4c)+6c+d, c:=d/2, d:=44
16c^2+14c+d, c:=d/2, d:=44
16(d/2)^2+14(d/2)+d, d:=44
16(44/2)^2+14(44/2)+44
...

If a previously substituted variable is encountered, then it is a circular reference, an error should be thrown.
Tell the user to change a variable using setVar in order to be able to parse expressions.

Now, for the substitute-on-setVar behaviour, use variable:=value #203.
aka nerdamer("x:=3"); nerdamer("y:=x"); //Now y is 3
In contrast: nerdamer.setVar("x", 3); nerdamer.setVar("y", "x"); //y is x; will change when x changes

Alternatively, use setConstant for the substitute-on-setVar behaviour, and setVar for substitute-on-parse behaviour.

**Comment by jiggzson** [comment]
@Happypig375, I went over this one again during version 0.8.0 and this introduces  quite a bit of computation for something that can be handled outside the library. I'm closing this issue and recommending that this is handled by storing the values outside of the library and then overriding them each time as needed. The amount of effort and computation to accomplish this is trivial.
