### ISSUE TITLE
solveEquations complains about allowed_args?

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#214]
nerdamer.solveEquations('x+y=2', 'x=1') => [] (empty array)
nerdamer.solveEquations('x+y=2', 'x-y=-1') => [] (empty array)
Ummm what??

**Comment by jiggzson** [comment]
As per documentation (http://nerdamer.com/functions/Solve.solveEquations.html), solveEquations expects and array.

**Comment by Happypig375** [comment]
>solveEquations expects and array.

OK, my bad.
Btw:
master:
` document.writeln(nerdamer.solveEquations(['x+y=1', '2*x=6', '4*z+y=6']).toString())` =>
`×JavaScript error: Uncaught TypeError: nerdamer.solveEquations is not a function on line 7880`

dev:
` document.writeln(nerdamer.solveEquations(['x+y=1', '2*x=6', '4*z+y=6']).toString())` =>
`×JavaScript error: Uncaught TypeError: nerdamer.solveEquations is not a function on line 7076`

**Comment by Happypig375** [comment]
master:
`document.writeln(nerdamer('solveEquations([x+y=1, 2*x=6, 4*z+y=6])').toString())` => `[solveEquations,6*solveEquations,6*solveEquations]`
dev:
`document.writeln(nerdamer('solveEquations([x+y=1, 2*x=6, 4*z+y=6])').toString())` =>
`[solveEquations,6*solveEquations,6*solveEquations]`

**Comment by jiggzson** [comment]
Strange. I get 
[ [ 'x', 3 ], [ 'y', -2 ], [ 'z', 2 ] ]
Do you have the Solve.js loaded?

**Comment by Happypig375** [comment]
:+1: Ooooh... That was what happening.

**Comment by Happypig375** [comment]
Now I get `allowed_args is not defined`.

**Comment by jiggzson** [comment]
Which branch? And how are you calling the function?

**Comment by Happypig375** [comment]
>nerdamer('solveEquations([x+y=1, 2*x=6, 4*z+y=6])')

^^^

**Comment by jiggzson** [comment]
You must be on master. Remember that this issue is only fixed on dev. I get
{ symbol: [ [ 'x', 3 ], [ 'y', -2 ], [ 'z', 2 ] ] } 
when I run this on dev

**Comment by Happypig375** [comment]
When is the merge to master from dev?

**Comment by jiggzson** [comment]
I'll merge once I knock down some of these issues and add the tests for them.
