### ISSUE TITLE
Documentation: nerdamer.set

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#215]
Current settings:
https://github.com/jiggzson/nerdamer/blob/257712ec3bc439c186496a98c42b743a7d6719a8/nerdamer.core.js#L26-L55

TypeScript declarations file:
https://github.com/jiggzson/nerdamer/blob/257712ec3bc439c186496a98c42b743a7d6719a8/index.d.ts#L174-L186

Documentation:
https://github.com/jiggzson/nerdamer/blob/703d40ebe49f81e2b782759bf24de0454e5d891a/docgen/function_docs.js#L339-L341

Both the TypeScript declarations file and Documentation are lacking a lot of Settings options.

**Comment by jiggzson** [comment]
I'm closing this one. It's enough to have it as a note in #247.
