### ISSUE TITLE
Algebrite roots vs Nerdamer solve

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#216]
Item|Input|Algebrite (using roots function)|Nerdamer (using solve function for x)
-|-|-|-
First degree|3 x + 12 + y = 24|-1/3 y + 4|[(-1/3)*(-12+y)]
Second degree|a\*x^2+b*x+c|[-1/2 (b^2 / (a^2) - 4 c / a)^(1/2) - b / (2 a),1/2 (b^2 / (a^2) - 4 c / a)^(1/2) - b / (2 a)]|[(1/2)\*(-b+sqrt(-4\*a\*c+b^2))\*a^(-1),(1/2)\*(-b-sqrt(-4\*a\*c+b^2))\*a^(-1)]
Fourth degree|x^4 + x^3 + x^2 + x + 1|[1/2 (-1/2 - 1/2 5^(1/2) - (-5/2 + 1/2 5^(1/2))^(1/2)),1/2 (-1/2 - 1/2 5^(1/2) + (-5/2 + 1/2 5^(1/2))^(1/2)),1/2 (-1/2 + 1/2 5^(1/2) - (-5/2 - 1/2 5^(1/2))^(1/2)),1/2 (-1/2 + 1/2 5^(1/2) + (-5/2 - 1/2 5^(1/2))^(1/2))]|[(125771031/132243488)*i+31622993/102334155,(-237785622/250022599)*i+31622993/102334155,(103387195/175892802)*i-260449120/321932817,(-103387195/175892802)*i-260449120/321932817]
Special polynomials|m*x^9 + n|[-cos(2/9 pi) (n / m)^(1/9) - i (n / m)^(1/9) sin(2/9 pi),-cos(4/9 pi) (n / m)^(1/9) - i (n / m)^(1/9) sin(4/9 pi),-cos(8/9 pi) (n / m)^(1/9) - i (n / m)^(1/9) sin(8/9 pi),1/2 (n / m)^(1/9) - 1/2 i 3^(1/2) (n / m)^(1/9),1/2 (n / m)^(1/9) + 1/2 i 3^(1/2) (n / m)^(1/9),cos(1/9 pi) (n / m)^(1/9) + i (n / m)^(1/9) sin(1/9 pi),cos(5/9 pi) (n / m)^(1/9) + i (n / m)^(1/9) sin(5/9 pi),cos(7/9 pi) (n / m)^(1/9) + i (n / m)^(1/9) sin(7/9 pi),-(n / m)^(1/9)]|[]
Factorable polynomials|(x^4+x^3)\*(x^4*x^2)|[-1,0]|TypeError: Cannot read property 'multiplier' of undefined

I see a lot of room for improvement here.

**Comment by Happypig375** [comment]
Item|Input|Algebrite (using nroot)|Nerdamer (using solve for x)
-|-|-|-
Even higher-degree irreducible polynomials|[-1.14355 - 0.17372 i,-1.14355 + 0.17372 i,-0.948252 - 0.539442 i,-0.948252 + 0.539442 i,-0.642275 - 0.835671 i,-0.642275 + 0.835671 i,-0.257384 - 0.999488 i,-0.257384 + 0.999488 i,0.154642 - 1.00614 i,0.154642 + 1.00614 i,0.533697 - 0.855942 i,0.533697 + 0.855942 i,0.82327 + 0.572976 i,0.82327 - 0.572976 i,0.979855 + 0.201364 i,0.979855 - 0.201364 i]|[(574427479/671105353)*i+135938837/254711549,(-574427479/671105353)*i+135938837/254711549,(232949873/278757761)*i-122393980/190563079,(-232949873/278757761)*i-122393980/190563079,(171466001/171553910)*i-32386353/125828993,(-171466001/171553910)*i-32386353/125828993,(50505789/88146490)*i+623627748025130/757500568167631,(-50505789/88146490)*i+623627748025130/757500568167631,(79113271/78630671)*i+19711339/127464527,(-79113271/78630671)*i+19711339/127464527,(142125304/263467165)*i-56254729/59324639,(-142125304/263467165)*i-56254729/59324639,(19636816/97518871)*i+87103123/88893865,(-19636816/97518871)*i+87103123/88893865,(15654959/90116066)*i-873659029/763986529,(-15654959/90116066)*i-873659029/763986529]

This item is pretty good.

**Comment by Happypig375** [comment]
Algebrite returns symbolic roots for equations of the fourth degree. Can Nerdamer do that too?

**Comment by Happypig375** [comment]
For x^4 + x^3 + x^2 + x + 1 and x^16+x^15+2, the demo result goes out of bounds. Can a line wrap be implemented?

**Comment by jiggzson** [comment]
@Happypig375, these issues are fixed. Let's place any remaining issues with solve under #322

**Comment by Happypig375** [comment]
Ok
