### ISSUE TITLE
Inverse Laplace transform function

### ISSUE THREAD

**Issue by nick4814** [jiggzson/nerdamer#218]
The current laplace() function is great but would be useful to have a function to convert back.

For example:

<p align="center">
nerdamer('laplace(t^6, t, s)').evaluate();<br>
Returns "720*s^(-7)"
</p>

Something to convert back could look like:

<p align="center">
nerdamer('inverse_laplace(720*s^(-7), s, t)').evaluate();<br>
Should return "t^(6)"
</p>

**Comment by Happypig375** [comment]
Good one! :+1:

**Comment by jiggzson** [comment]
@nick4814, this function has already been implemented through ilt. However it depends on integrate which is not yet complete so it won't solve certain transforms. I imagine this issue can be closed and the above mentioned can be added to the documentation. @Happypig375, what do you think?

**Comment by Happypig375** [comment]
Yep, closing should be ok. Any issues of this function will probably be integrate's fault.
