### ISSUE TITLE
Invalid Solve Result

### ISSUE THREAD

**Issue by richardowright** [jiggzson/nerdamer#220]
When solving the below, I'd expect  `a/c+1`, but I get `a/c`.

    const util = require("util");
    const nerdamer = require("nerdamer");
    require("nerdamer/Solve.js");

    var eq = nerdamer('a/(b-1)=c');
    console.log(eq.toString());
    var solutions = eq.solveFor('b').toString();

    console.log(solutions);
    simplSolution = nerdamer(solutions);
    console.log(simplSolution.toString());

**Comment by Happypig375** [comment]
Interestingly, `nerdamer('solve(a/b=c,b)').toString()` returns `[]`. It should return `a/c`.

**Comment by Happypig375** [comment]
`nerdamer('solve(a/b-1=c,b)').toString()` returns `[]`. Should return `[a/(c+1)]` (or with consistency with current behaviour, `[a*(c+1)^-1]`).

**Comment by jiggzson** [comment]
I totally agree. Sorry for the late reply but I've had a crazy few weeks. I pushed a fix to master for this. Thanks for the catch guys.

**Comment by richardowright** [comment]
Thanks!

**Comment by Happypig375** [comment]
Merge master to dev?
