### ISSUE TITLE
factor regressions on dev branch

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#223]
demo: GOOD
dev: BAD

**Comment by Happypig375** [comment]
Input|My Answer|Algebrite (@website)|Nerdamer (@demo)|Nerdamer (@dev)
-|-|-|-|-
factor(x^2+2x+1)|(x+1)^2|(x + 1)^2|(1+x)^2|(1+x)
factor(x^3+3x^2y+3x y^2+y^3)|(x+|(x + y)^3|(x+y)^3|(x+y)^3

**Comment by Happypig375** [comment]
Seems like a problem with numeric literals.

**Comment by Happypig375** [comment]
Input|My Answer|Algebrite (@website)|Nerdamer (@demo)|Nerdamer (@dev)
-|-|-|-|-
factor(x+x^2+x^3+x^4)|factor(x+x^2+x^3+x^4)|x (x + 1) (x^2 + 1)|(1+x)\*(1+x^2)\*(x)|1+x+x^2+x^3

**Comment by jiggzson** [comment]
I restored so I have a clean base to work off of so this issue should be closed. I can now continue to work on #219

**Comment by Happypig375** [comment]
I was going to verify this but hit #235. 😞
