### ISSUE TITLE
'E' is not converted to '\E' in Tex

### ISSUE THREAD

**Issue by umaiuma** [jiggzson/nerdamer#225]
When I write E in nerdamer demo, it is converted into 325368125​​/119696244 not 'E'

**Comment by umaiuma** [comment]
I found the reason It is the constant e=2.718. Then, How I can make the symbole E, not a constant

**Comment by Happypig375** [comment]
nerdamer.getCore().PARSER.constants['E'] = 'E'
Use this for now.

**Comment by umaiuma** [comment]
Thank you!!!!!!!!

**Comment by jiggzson** [comment]
>Use this for now.

Quite honestly I think that is the best fix for this issue overall.

**Comment by jiggzson** [comment]
@umaiuma Are you good with @Happypig375's solution?

**Comment by Happypig375** [comment]
See #244
