### ISSUE TITLE
'epsilon' is converted to ϵ but epsilon_0 is not. 

### ISSUE THREAD

**Issue by umaiuma** [jiggzson/nerdamer#226]
'epsilon' is converted to ϵ but epsilon_0 is not. 
How can I convert epsilon_0 to ϵ_0 not epsilon_0?

**Comment by Happypig375** [comment]
`nerdamer.setConstant('epsilon_0', 'ϵ_0');`?

**Comment by Happypig375** [comment]
You can do

for(var i = 0; i <= 9; i++) nerdamer.setConstant('epsilon_' + i, 'ϵ_' + i);

If you need it for all single digit numbers

**Comment by umaiuma** [comment]
Umm... That does not help me. 
var temp = nerdamer('epsilon_0') .toTex() 
I found the value of temp is 'epsilon_0'
I make it '\epsilon_0' not ''epsilon'
How can I do that?

**Comment by umaiuma** [comment]
Oh I made it.
//input is the fomula string
var make = nerdamer(input).toTeX();
    make=make.replace('epsilon_0','\\epsilon_0');
      var tex = '\\( '+ make+' \\)';

**Comment by jiggzson** [comment]
I'll make it so the LaTeX generator picks up on these as well.

**Comment by jiggzson** [comment]
@umaiuma Fixed
