### ISSUE TITLE
nerdamer demo input (1/(a*b)) return error 

### ISSUE THREAD

**Issue by umaiuma** [jiggzson/nerdamer#228]
the return is a*b not (ab)^-1

**Comment by jiggzson** [comment]
Ouch. I'll take care of this.

**Comment by umaiuma** [comment]
Also, 1/(a*b*c) return error too.

**Comment by Happypig375** [comment]
Type 1/(a\\*b\\*c) or GitHub Markdown will show it as italic

**Comment by Happypig375** [comment]
On second look, it is either the LaTeX generator or KaTeX showing wrong output. Loading output to editor correctly gives (a*b)^(-1). I doubt it is KaTeX's fault so it must be the LaTeX generator.

**Comment by jiggzson** [comment]
@umaiuma This issue is now fixed on the dev branch.
