### ISSUE TITLE
A setting for disallowing multicharacter variables

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#229]
In mathematics, you usually do not need to use multicharacter variables. Thus, `ABC` is usually interpreted as `A*B*C`. An option for disabling this (e.g. `nerdamer.set('MULTICHAR_VARS', false);`) would enable faster typing of equations.

**Comment by jiggzson** [comment]
I like. This is definitely in my top 3 favorite suggestions.

**Comment by Happypig375** [comment]
>top 3 favorite suggestions

I would like to know which three. 😃
If this is one of your favourites, you can set the priority of this higher :wink:. Removing
>P.S. The priority for this would be low.

**Comment by jiggzson** [comment]
Let me know when you've tried this.
