### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#230]
Useful for separating two values of different units.
They are kinda like in Algebrite, but they should be converted to SI units where possible.
For instance, cm => 0.01m
Syntax:
Plan A (The Algebrite syntax): `"m" "s"`
Plan B (The Algebrite syntax with spaces): `"m s"`
Plan C (Unit variables syntax): `m s` (Variables promoted to units)
Question: Use / or ^-1 ?

**Comment by Happypig375** [comment]
I prefer plan B because it saves " keystrokes.

**Comment by jiggzson** [comment]
Added to roadmap. Closing
