### ISSUE TITLE
Allow expressions in the keys of known values object

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#233]
nerdamer('y+cos(y)', {'cos(y)': '0.2'}, 'numer').text() => 1.569438406004566
--or--
nerdamer('y+cos(y)').evaluate({'cos(y)': '0.2'}).text() => 1.569438406004566
Really, really, really, really, really useful.
Internally it could use the solve function? I don't know.

**Comment by jiggzson** [comment]
Doesn't the nerdamer.sub function already do this?

**Comment by Happypig375** [comment]
What about: nerdamer('x^4+x^-4', {'x^1+x^-1': '3'})
 x^4+x^-4
=x^4+2+x^-4-2
=(x^2+x^-2)^2-2
=((x+x^-1)^2-2)^2-2
=(9-2)^2-2
=47

**Comment by Happypig375** [comment]
@jiggzson nerdamer('y+cos(y)').sub('cos(y)', '0.2') => y+0.2
It will not calculate y for me.

**Comment by jiggzson** [comment]
I don't understand what the problem is with the above example. What am I looking for? You have cos and then acos. Am I missing something?

**Comment by Happypig375** [comment]
>nerdamer('y+cos(y)', {'cos(y)': '0.2'}, 'numer').text()

sub only replaces cos(y).
What I am looking for is nerdamer should infer the value of y from cos(y), and y should be inferred as acos(0.2) from cos(y) = 0.2.

**Comment by Happypig375** [comment]
>nerdamer('x^4+x^-4', {'x^1+x^-1': '3'})

This is a representation of the question 'Given x+x^-1=3, calculate x^4+x^-4.

**Comment by jiggzson** [comment]
Go ahead and implement this and shoot me a PR with passing tests.

**Comment by jiggzson** [comment]
@Happypig375 I updated solve to take into account cases like solve(x+x^-1=3, x). You would now be able to solve for x using solve(x+x^-1=3, x) and then substitute either value into 'x^4+x^-4'.

**Comment by Happypig375** [comment]
Ok
