### ISSUE TITLE
demo: 'Load output to editor' ignores decimal and evaluate checkboxes & 3 answers are copied instead of one

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#234]
During the writing of #233, I entered 'acos(0.2)' into demo, and wanted to copy the decimal value. Although I checked decimal and evaluate boxes, the 'Load output to editor' button still gave me 'acos(1/5)'. When I copied the LaTeX output next to the buttons... I copied 1.3694384060045661.369438406004566
1.369438406004566 instead of 1.369438406004566. What???

**Comment by jiggzson** [comment]
I'll fix the fact that it doesn't load the decimal value but when I copy the LaTeX output it copies correctly. Are you sure it's not a browser issue? Have you tried it in a different browser?

**Comment by Happypig375** [comment]
>Are you sure it's not a browser issue? Have you tried it in a different browser?

Chrome : GOOD
Edge: BAD
Looks it is the case.
