### ISSUE TITLE
Infinity in Calculus

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#236]
Especially in sum. Implementing infinite series would enable arbitrary precise decimal outputs for pi, e and the (inverse) trigonometric functions. Helps implementing #221.

**Comment by jiggzson** [comment]
See #148

**Comment by Happypig375** [comment]
While #134 and #148 are closed, this is still not implemented.
sum(1/(2^x),x,1,Infinity) won't evaluate.

**Comment by Happypig375** [comment]
sum(1/(2^x),x,1,Infinity) should=> 1

**Comment by Happypig375** [comment]
Request reopen

**Comment by jiggzson** [comment]
Aren't we getting a bit into limits here?

**Comment by Happypig375** [comment]
True, but when we talk about infinite series/products/integrals, we do not write things like limit(sum(1/(2^n),n,1,x),x,Infinity), but we instead write sum(1/(2^n),n,1,Infinity).
The implementation could use some limits though.
