### ISSUE TITLE
The expand option causes an error

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#240]
nerdamer('') => 0
nerdamer('', undefined, 'expand') => Error: expand requires a minimum of 1 arguments. 0 provided!

Should not throw.

**Comment by jiggzson** [comment]
The zero is returned because that's the default return value because no parsing occurred. Nowhere in the documentation does it say that the library supports an empty string.

**Comment by Happypig375** [comment]
What is the reason to not support it?
