### ISSUE TITLE
nerdamer.expand should not call evaluate

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#241]
Input|My Answer|Algebrite (@website)|Nerdamer (@demo, expand function)|Nerdamer (@dev, expand function)
-|-|-|-|-
 4sqrt(24)|8sqrt(6)|8 2^(1/2) 3^(1/2)|8\*sqrt(6)|8\*sqrt(6)
sqrt(128/49)|8sqrt(2)/7|8/7 2^(1/2)|(1/7)\*sqrt(128)|(1/7)\*sqrt(128)
sqrt(360)/sqrt(162)|2/3sqrt(5)|2/3 5^(1/2)|158114965/106066743|158114965/106066743
3sqrt(6)+5sqrt(6)-7sqrt(6)|sqrt(6)|2^(1/2) 3^(1/2)|sqrt(6)|sqrt(6)
sqrt(252)-sqrt(28)|4sqrt(7)|4 7^(1/2)|4\*sqrt(7)|4\*sqrt(7)
sqrt(72)-sqrt(288)+sqrt(576)|-6sqrt(2)+24|24 - 6 2^(1/2)|640442977/41279703|640442977/41279703
3sqrt(2)\*2sqrt(6)|12sqrt(3)|12 3^(1/2)|759002504/36517525|759002504/36517525
sqrt(125)sqrt(18)|15sqrt(10)|15 2^(1/2) 5^(1/2)|14664406176/309152827|14664406176/309152827
sqrt(24)(sqrt(12)+sqrt(18))|12sqrt(2)+12sqrt(3)|2|316409941/8380572|316409941/8380572
(sqrt(7)+3sqrt(2))(sqrt(7)-3sqrt(2))|-11|-9 nil|-9401694170000029/8546994700000000000000000000000|-9401694170000029/8546994700000000000000000000000
(3sqrt(5)-5sqrt(2))^2|95-30sqrt(10)|95 - 30 2^(1/2) 5^(1/2)|9527289/72357218|9527289/72357218
x sqrt(x)+x^2sqrt(x^3)|x sqrt(x)+x^3sqrt(x)|x^(3/2) + x^2 (x^3)^(1/2)|x^(3/2)+x^(5/2)|x^(3/2)+x^(5/2)
sqrt(3a^3)sqrt(6a^5)|3a^4sqrt(2)|(3 a^3)^(1/2) (6 a^5)^(1/2)|(163825179/38613965)\*sqrt(a^3)\*sqrt(a^5)|(163825179/38613965)\*sqrt(a^3)\*sqrt(a^5)
(sqrt(3x)-sqrt(32y))(sqrt(3x)-sqrt(2y))|3x-5sqrt(6x y)+8y|(-nil)^(1/2)|(-1950910202312414803380011/159291150988510511085788)\*sqrt(x)\*sqrt(y)+(19295182152595801/6431727384198601)\*x+(31779555538278207/3972444442284776)\*y|(-1950910202312414803380011/159291150988510511085788)\*sqrt(x)\*sqrt(y)+(19295182152595801/6431727384198601)\*x+(31779555538278207/3972444442284776)\*y

**Comment by jiggzson** [comment]
This issue is related to the demo. The library itself doesn't do this. I honestly think that demo questions should just be part of one issue since they make if difficult to see the real issues with the library itself.

**Comment by Happypig375** [comment]
I think I will come back to this and clarify the bug later.
