### ISSUE TITLE
Is it better to leave the expand option on?

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#242]
It turns (x+1)^2 to 1+2\*x+x^2 but leaves factor(x^2+2x+1) as (1+x)^2.
Are there any disadvantages to turning this on?

**Comment by jiggzson** [comment]
Yes. This can cause tremendous swell in certain functions not to mention that people generally only want the end result expanded. I find it better to leave the symbol simplified until it's  needed.

**Comment by Happypig375** [comment]
OK. Question answered, closing.

**Comment by Happypig375** [comment]
Just remembered this question: 
>This can cause tremendous swell in certain functions 

Which functions?

**Comment by jiggzson** [comment]
I don't remember which ones exactly. It might be gcd. Additionally it also causes performance problems.
