### ISSUE TITLE
PI and E evaluate even when evaluate not called

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#244]
nerdamer('PI').text() => 3.141592653589793
nerdamer('E').text() => 2.718281828459045
nerdamer('PI').evaluate().text() => 3.141592653589793
nerdamer('E').evaluate().text() => 2.718281828459045
nerdamer('pi').text() => pi
nerdamer('e').text() => e
nerdamer('pi').evaluate().text() => 3.141592653589793
nerdamer('e').evaluate().text() => 2.718281828459045

**Comment by jiggzson** [comment]
That's the whole point of PI and E. They are the numeric values. pi and e are the symbolic placeholders.

**Comment by Happypig375** [comment]
Any option to turn PI and E to symbolic placeholders? Or more generally, any way to define new symbolic placeholders?

**Comment by jiggzson** [comment]
Can you give such an example?

**Comment by Happypig375** [comment]
>Can you give such an example?

An example of symbolic placeholder?
You literally sefined them in the previous comment.
>pi and e are the symbolic placeholders.

**Comment by Happypig375** [comment]
An example of a **new** placeholder: π (evaluates to pi)

**Comment by jiggzson** [comment]
Exactly. That's the whole point of the entire library. To define symbolic placeholders. So what's missing here?

**Comment by jiggzson** [comment]
What's stopping you from using setVar?

**Comment by Happypig375** [comment]
setVar is overridable.
PI and E are not placeholders but substituted before evaluation.

**Comment by Happypig375** [comment]
setConstant throws for nonnumerical values

**Comment by Happypig375** [comment]
nerdamer.getCore().PARSER.constants are direct substitutions and are not placeholders.

**Comment by jiggzson** [comment]
Can you give an example of such a dilemma? Why not use the numeric values if it throws for symbolic values?

**Comment by Happypig375** [comment]
nerdamer.setConstant('π', Math.PI)
Makes π-pi not result in 0 before evaluation

**Comment by Happypig375** [comment]
The whole point of this issue is that PI and E should be symbolic placeholders but are not.

**Comment by jiggzson** [comment]
That because we're talking about two completely different issues. The first sets a constant and the second compares to aliases. The second one is the exact equivalent of saying 
π=pi

**Comment by Happypig375** [comment]
And they should equate to pi and e.

**Comment by Happypig375** [comment]
>The first sets a constant and the second compares to aliases

:confused:

**Comment by jiggzson** [comment]
Yes and no. And quite honestly this is a bit of nitpicking. E and PI map back to the constant values while e and pi are the symbolic placeholders. I don't understand what the problem is with just using e and pi.

**Comment by Happypig375** [comment]
There is currently no option to disable E and PI being subatituted.

**Comment by jiggzson** [comment]
Substituted for what?

**Comment by Happypig375** [comment]
Like in #225, I want to keep E and PI as E an PI, not as constants. e and pi are far more useful to me than E and PI since I can calculate in terms of e and pi.

**Comment by jiggzson** [comment]
@Happypig375 Think about what you're asking for a second. You are asking me to make 2.718281828459045235.. = e. It's the other way around. So therefore use e. If it helps, ignore E and PI altogether.

**Comment by Happypig375** [comment]
And I would want to change the definition of pi such that pi equates to π, and π be the placeholder for Math.PI.

**Comment by Happypig375** [comment]
>You are asking me to make 2.718281828459045235.. = e

No, I just want to disable PI and E from being substituted.

**Comment by Happypig375** [comment]
Btw, this issue broke the record of most comments in one issue.

**Comment by jiggzson** [comment]
@Happypig375 I don't see the problem. e and pi are only substituted when evaluate it called. **Just use e and pi.**

**Comment by Happypig375** [comment]
I just want an option to make E and PI normies, like a, b, c, etc.

**Comment by jiggzson** [comment]
They can't because they're numeric. They have been around since the first instance of the nerdamer. That has always been their purpose. To be numeric values to be substituted once evaluate is called.

**Comment by Happypig375** [comment]
And being able to define new symbolic placeholder constants would enable me to e.g. define the golden ratio and calculate in terms of it.

**Comment by Happypig375** [comment]
>They can't because they're numeric. 

See my fix for #224

**Comment by jiggzson** [comment]
>And being able to define new symbolic placeholder constants would enable me to e.g. define the golden ratio and calculate in terms of it.

Now we're getting somewhere. Let me think about this a little.

**Comment by jiggzson** [comment]
I thought about this and I believe that what you're trying to achieve is deferring evaluation until evaluate is called. First example.
```javascript
nerdamer.setConstant('g', 9.81);
//strange example but I'm trying to illustrate the point
nerdamer.setFunction('weight', ['m'], 'm*g');
var x = nerdamer('weight(mass)');
console.log(x.toString()); //(981/100)*mass
```
The problem is that g is substituted immediately. This is one of the reasons to set the function manually. Instead do this.
```javascript
nerdamer.setConstant('g', 9.81);
var core = nerdamer.getCore();
var _ = core.PARSER;
var weight = function(mass) {
    return _.multiply(new core.Symbol('g'), mass);
}

nerdamer.register({
    name: 'weight',
    visible: true,
    numargs: 1,
    build: function(){ return weight; }
});

var x = nerdamer('weight(mass)');
console.log(x.evaluate().toString()); //(981/100)*mass
console.log(x.toString()); //g*mass
```
g will not be evaluated until evaluate is called.

**Comment by Happypig375** [comment]
I will not be using another function, but like this:
```js
nerdamer.setConstant('pi', 'π'); //eager
nerdamer.setConstant('π', Math.PI); //deferred
```
Wait... Actually I need both eager and deferred evaluations.
Maybe a new boolean parameter for this?

**Comment by jiggzson** [comment]
The solution to deferred evaluation is to use the above mentioned solution. Use nerdamer.setConstant for eager evaluation.

**Comment by Happypig375** [comment]
Can I not need to wrap the constant inside a function and register it? This is clunky.

**Comment by Happypig375** [comment]
I just recalled this issue today.
I think PI and E duplicate the purpose of pi and e.
The whole point of symbolic math is calculating exact values.
If a numeric approximation is needed, call evaluate().
Why use PI and E then?

**Comment by jiggzson** [comment]
You're right. This just shows the evolution of the library. It's slowly getting less dependent on JavaScript. I'll think about how to cleanly remove this.
