### ISSUE TITLE
How to replace builtin functions?

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#248]
During my custom implementation of #185, I needed custom implementations of sin, cos, tan, asin, acos and atan. I started with
```js
nerdamer.setFunction('sin', 'x', 'sin(x*pi/180)');
document.writeln(nerdamer('sin(pi)')); //=> 0
```
then
```js
var _ = nerdamer.getCore().PARSER;
var f = _.functions.sin;
_.functions.sin = (function sin(s){return f(_.divide(_.multiply(s,Math.PI),180),1);});
alert(nerdamer('sin(pi)').toString()); //=> 'allowed_args' is undefined
```
finally
```js
nerdamer.register({
   name: 'sin',
   numargs: 1,
   visible: true,
   build: function(){
   var _ = nerdamer.getCore().PARSER;
   var f = _.functions.sin;
   return(function sin(s){return f(_.divide(_.multiply(s.clone(),Math.PI),180),1);});
   }
});

alert(nerdamer('sin(pi)').toString()); //=> Function expected
```
How can I do this?

**Comment by Happypig375** [comment]
I am using
```js
var f = Math.sin;
Math.sin = function(x){return f(x*Math.PI/180)};
```
for now but it is a really bad solution.

**Comment by jiggzson** [comment]
There's really no way easy way to override builtin functions. The timing of your issue is a bit ironic since just yesterday I was thinking that I need to refactor the code and bundle all trig functions in a Trig object (please don't create another issue for this 😆). That said, wouldn't it be easier to just create a degree and radians function? 

```javascript
nerdamer.setFunction('radians', ['x'], 'x*pi/180');
nerdamer.setFunction('degrees', ['x'], 'x*180/pi');

var x = nerdamer('sin(radians(x))');
console.log(x.toString());
```

**Comment by Happypig375** [comment]
I waned a global switch just as in #154... 🤔

**Comment by Happypig375** [comment]
```js
var useRadians = false;
{
   var f = Math.sin;
   Math.sin = function(x){return f(x*(useRadians?1:Math.PI/180))};
}
```
Like this

**Comment by Happypig375** [comment]
Argh just implement #185.

**Comment by Happypig375** [comment]
Just noticed I referenced #154 when I wanted to reference #185. My bad 😨. Editing all of them.

**Comment by jiggzson** [comment]
Yes. #185 would indeed be the best solution but the library doesn't support units yet.

**Comment by Happypig375** [comment]
#230 😵

**Comment by jiggzson** [comment]
As discussed this one belongs under #230 and #185. Closing.

**Comment by Happypig375** [comment]
Well, those do not solve the problem of replacing builtin functions with custom implementations.

**Comment by jiggzson** [comment]
I'll reopen the issue then.

**Comment by jiggzson** [comment]
@Happypig375 Feel free to reopen any issue you feel was closed in error.

**Comment by Happypig375** [comment]
https://github.com/jiggzson/nerdamer/issues/256#issuecomment-332717835 might be of interest.

**Comment by jiggzson** [comment]
@Happypig375 I've created a method for replacing built-in functions. The syntax is as follows
```javascript
nerdamer.replaceFunction(fn_name, constructor);
//where fn_name is the name you're wishing to replace
//and the construction is a function which returns a function
```
The constructor takes as arguments, the existing function which can be used to extend the existing function, and the core. I've provided an example below. 

```javascript
nerdamer.replaceFunction('sin', function(sin, core) { 
    return function(x) {
        if(x.equals(0))
            return new core.Symbol('funny_number');
        return sin(x);
    };
});

var x = nerdamer('sin(0)').evaluate();
console.log(x.toString())
var y = nerdamer('sin(pi/2)').evaluate();
console.log(y.text())
```
The only responsibility to you would be to make sure that either a symbol, vector, or matrix is returned.
