### ISSUE TITLE
Readme: nerdamer('hyp(a, b) = sqrt(a^2 + b^2) ');

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#249]
https://github.com/jiggzson/nerdamer/blob/855db44371259e950c5aad1a3784068461b2eb33/README.md#L252-L259
I cannot get it to work. It throws 'Unrecognized function "hyp"'.

**Comment by Happypig375** [comment]
This is not in the 'docs' or 'demo' categories so I won't comment this in #247. :trollface:

**Comment by jiggzson** [comment]
It must have gotten removed by accident. I'll work on this.

**Comment by jiggzson** [comment]
To avoid ambiguity, I borrowed := from Maxima and as it is in the demo. So you would use
```javascript
nerdamer('f(x):=x^2');
console.log(nerdamer('f(9)').toString());
```
or 
```javascript
nerdamer('f(x):=x^2');
nerdamer.api();
console.log(nerdamer.f(9).toString());
```

**Comment by Happypig375** [comment]
Any chance that this could also work on variables set by setVar?
