### ISSUE TITLE
Solving Equation problem

### ISSUE THREAD

**Issue by VishalKumarMitra786** [jiggzson/nerdamer#25]
I am build a graphing system using your Library thanks a lot you made such a library helped me a lot but I am finding an issue in getting the value of y when that Equation is of the form below:

var equation = (x-1)^2 + (y-1)^2 - (4)

var   val = nerdamer(equation, { x: 4});
var   parse = val + "=0";    Where parse is "(-1+y)^2+5=0" 

var sol = nerdamer.solveEquations(parse, 'y');

Error: From Algebra , Invalid array length as in the rpSolution function the  degree parameter  is coming up as  NaN (not a number).

Please can you help me in this because I am looping though the value to get the value of 'y' to generate a circle.

The library is supporting the equation x^2 + y^2 =4,  But if i am adding the center value then its not working example  (x-1)^2 + (y-1)^2 - (4)

**Comment by jiggzson** [comment]
Hi. Thanks for your feedback. I'm glad that the library was able to help
you. 2 things. I don't have access to nerdamer right now but you should not
have to explicitly set your equation to 0. It's implied. The second thing
is that you may have to simply the equation/expression before sending it to
solve. I believe you may have just exposed a bug. Can you try

var val = nerdamer(equation, { x: 4},  'expand' );

instead of

var val = nerdamer(equation, { x: 4});

and see if that helps. Please let me know either way.

**Comment by VishalKumarMitra786** [comment]
Thanks a lot you saved my day, its working great.

But I am finding two issues now:
1)var  equation="-cot(-10)+y=0" 
   var val = nerdamer.solveEquations(equation, 'y');
  Error: "Cannot read property 'cot' of undefined"  also same goes for keywords 'ln' ,'sec' etc.

Note: When I am using sin,cos,tan,asin,acos these are working, So is it that you have not made support for the above functions ?

2) If i am looping through values 
for (var i = -10 ; i < 10 ; i = i +0.1) {
   eq = nerdamer('y-(1/x)', { x: i }, ['expand']);
   sol = nerdamer.solveEquations(eq , 'y');
}

When it is hitting i=0 is throwing the error divide by zero i.e. off course(1/0).
So is there any way to by pass the situation and the process don't stop.

Note:When i was using your Library in my demo this was working awesome, suddenly when I started in my real implementation this started throwing error and i was not getting the above error 'divide by zero'.

Could you please Help me with the above situations because I am enjoying using this library and it has solved most of problems.

**Comment by jiggzson** [comment]
I ran the above code and I get
```javascript
var equation="-cot(-10)+y=0";
var val = nerdamer.solveEquations(equation, 'y');
console.log(val.toString())
//-1.5423510453569202,-1.5423510453569202
```
What version of nerdamer are you using? As for ln this would be log.

If you want log with a base of 10 you would have to define it and then you can use it. For example

```javascript
nerdamer.setFunction('log10', ['x'], 'log(x)/log(10)');
console.log(nerdamer('log10(9)').evaluate().text());
//0.9542425094393248
```

**Comment by VishalKumarMitra786** [comment]
I am using   "version": "0.5.6"  , and i am still getting the error
![9-3-2015 5-25-19 pm](https://cloud.githubusercontent.com/assets/12175131/9657672/d3993e42-5260-11e5-81df-b68efc4dd4f0.png)


And thanks for the log one it might help me with any log  base I guess.

Thanks for developing such a power full library.

**Comment by jiggzson** [comment]
No problem I'm glad to help. The error is strange. Can you maybe try the version from master and run that one. It might be related to an bug that has been fixed since the last release.

**Comment by jiggzson** [comment]
Sorry. I accidentally closed the issue.

**Comment by brosnanyuen** [comment]
What browser and OS  are you using? (e.g. Chrome 45.0.2454.85 on Linux)

**Comment by VishalKumarMitra786** [comment]
I am using 45.0.2454.85 on windows , Okay will revert you then by taking the version directly from the master.

**Comment by VishalKumarMitra786** [comment]
Its working now thanks alot

**Comment by jiggzson** [comment]
VishalKumarMitra786 can this issue be closed?

**Comment by VishalKumarMitra786** [comment]
Yes this issue can be closed thanks alot
