### ISSUE TITLE
sign of negative values could be parsed directly

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#250]
`sign(-1)` => `sign(-1)`
Should be obvious enough to substitute directly before evaluation?

**Comment by jiggzson** [comment]
Basically it's pretty clear when the input is numeric that the sign can be returned. Agreed.

**Comment by jiggzson** [comment]
This is already the case. 
```javascript
var x = nerdamer.sign('-4');
console.log(x.toString());
```
returns -1;

**Comment by Happypig375** [comment]
You mean on dev? The demo and master still return sign(-1) when sign(-1) is entered.

**Comment by Happypig375** [comment]
Looks like sign(-1) also returns sign(-1) on dev when evaluate() not called...

**Comment by Happypig375** [comment]
Oh, `nerdamer.sign('-4')` works, but not `nerdamer('sign(-4)')`. That's why.

**Comment by Happypig375** [comment]
https://github.com/jiggzson/nerdamer/issues/248#issuecomment-331684229
I am missing the reopen button...
![image](https://user-images.githubusercontent.com/19922066/30856866-533120c4-a2ec-11e7-87d1-9b9cccd98d6c.png)

**Comment by Happypig375** [comment]
I think that the same technique used in pfactor where the symbol is cloned then calculated can be used here.
This way, min(cos(6),sin(6),4) can be calculated as sin(6) just like Wolfram Alpha.

**Comment by Happypig375** [comment]
Oops, wrong issue 🤦‍ Closing.
