### ISSUE TITLE
#193 but clarified

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#260]
() => 0
(()) => 0
The above two suggest that the empty brackets evaluate to zero.
However,
()() => Error: * is not a valid prefix operator
Implicit multiplication does not work for it.

**Comment by jiggzson** [comment]
@Happypig375 They don't evaluate. The parser finds an empty stack and returns zero. Nothing is evaluated. Why is this even needed?

**Comment by Happypig375** [comment]
The error message says that * is not a prefix operator, but there is no * in ()().
