### ISSUE TITLE
Rounding error with fraction exponents

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#269]
125^(2/3) evaluate=> 24.999999999999996
nthroot can be used here: nthroot(125,3)^2 eval=> 25

**Comment by Happypig375** [comment]
solve(x^(3/4)=125,x) eval=> [624.9999999999997,39.062499999999986*(1+1.7320508075688772*i)^4,39.062499999999986*(-1.7320508075688772*i+1)^4]
Wow... That is a lot of rounding errors.

**Comment by jiggzson** [comment]
Moving to #404
