### ISSUE TITLE
Small decimal with big exponent throws error with NaN

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#271]
1^999 => 1
2^999 => 5.357543035931337e+300
1.02^999 => Error: Invalid integer: NaN

**Comment by Happypig375** [comment]
Ooops... This actually gives correct results but I copied the wrong value lol

**Comment by Happypig375** [comment]
It is coming up again for me, reopening, don't know how it happened.

**Comment by Happypig375** [comment]
1.2^999 => Error: Invalid integer: NaN

**Comment by Happypig375** [comment]
1.2^99 works, its value is 69014978.76834545

**Comment by Happypig375** [comment]
I found a reliable way to throw:
By the definition of e (the limit of (1+1/x)^x as x approaches infinity)
(1+1/1e3)^1e3 => Error: Invalid integer: NaN

**Comment by jiggzson** [comment]
This issue is related to #247 and #221 which are already being worked on. Closing.
