### ISSUE TITLE
A bunch of functions that solve throws for

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#275]
Function (solve(function(x)=3,x))|Error
-|-
sinc, Ei|x.equals is not a function
Si, Ci, Shi, Chi|Math2 is not defined
smpvar, smpstdev|Division by zero not allowed!
variance, stdev|0 does not equal 3

**Comment by Happypig375** [comment]
Function (solve(function(x)=matrix([1,0],[0,1]),x))|Error
-|-
matrix, imatrix|rhs.isConstant is not a function
invert|invert expects a matrix
transpose|function transpose expects a matrix

**Comment by Happypig375** [comment]
solve(nthroot(x,4/3),x) => Cannot read property 'toString' of undefined

**Comment by Happypig375** [comment]
solve(x!=362880,x) => factorial not defined for negative numbers
solve(factorial(x)=362880,x) => factorial not defined for negative numbers

**Comment by jiggzson** [comment]
Not all functions are complete and it probably going to be a very long time until that happens. There's just so much to account for with every function. I'll keep this in mind.

**Comment by Happypig375** [comment]
>it probably going to be a very long time until that happens

Ok, I'll wait.
P.S. Nerdamer already has a pretty good solver. Good work.

**Comment by jiggzson** [comment]
Thanks

**Comment by jiggzson** [comment]
Creating a reference for this issue in #322 and moving issue there.
