### ISSUE TITLE
OMG INTEGRATE AND SOLVE HATE EACH OTHER!!!11!!

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#276]
Lol clickbait title :laughing: :rofl:
Solve: solve(integrate(x)=3,x) => [sqrt(6),-sqrt(6)]
Integrate: integrate(sqrt(6)) => 6*undefined
They "hate" each other.

**Comment by ljacqu** [comment]
OMG :dizzy_face:

**Comment by Happypig375** [comment]
@ljacqu Btw, good luck with writing tests on the large amount of recent issues.

**Comment by jiggzson** [comment]
@Happypig375 My message in #255 clearly ran hollow so going forward unless the issue is clearly a bug, fork the library, make a contribution and give send me a PR with passing tests.

**Comment by Happypig375** [comment]
>the issue is clearly a bug

Does 6*undefined not look like a bug?

**Comment by Happypig375** [comment]
What is up with closing issues that are clearly bugs?
