### ISSUE TITLE
Solving the half exponent/square root

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#277]
solve(x=π^(1/2),x) => [-pi]
solve(x=sqrt(π),x) => [-pi]
And
solve(π^(1/2)=x,x) => [pi]
solve(sqrt(π)=x,x) => [pi]
They give different values,
but both are incorrect, the correct answer is:
sqrt(pi)

**Comment by Happypig375** [comment]
What is wrong with closing AND COMMENTING?

**Comment by Happypig375** [comment]
If you substitute -pi or pi into the equations, they equate to sqrt(pi), which is NOT correct, and is a bug.

**Comment by Happypig375** [comment]
Fixed as of dev but no symbolic answer.

**Comment by jiggzson** [comment]
moving to #322
