### ISSUE TITLE
Numerical input for min and max can be calculated directly

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#279]
nerdamer('min(2,3,4,5)') => min(2,3,4,5)
nerdamer('max(2,3,4,5)') => max(2,3,4,5)

On the other hand, mean, mode and median are all calculated on parse, which is a bit unfair to min and max.

**Comment by Happypig375** [comment]
https://github.com/jiggzson/nerdamer/issues/250#issuecomment-346034848
>I think that the same technique used in pfactor where the symbol is cloned then calculated can be used here.
This way, min(cos(6),sin(6),4) can be calculated as sin(6) just like Wolfram Alpha.

**Comment by jiggzson** [comment]
>I think that the same technique used in pfactor where the symbol is cloned then calculated can be used here.

Not really. This would for sin(6) to be evaluated. Is that what you're looking for?

**Comment by Happypig375** [comment]
Like this:
Input: min(cos(6),sin(6),4)
🔽
Copy into vector [cos(6),sin(6),4]
🔽
Parse to number [0.96017...,-0.2794...,4]
🔽
Compare (slot 1 is smallest)
🔽
Look up value from input (slot 1 of input is sin(6))
🔽
Output: sin(6)

**Comment by Happypig375** [comment]
If things like complex numbers are encountered, then just remain being not evaluated or throw.
