### ISSUE TITLE
Factorial of matrixes and vectors throw

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#280]
[9,8,7]! => factorial([9,8,7]) eval=> Object has no method 'isConstant'
matrix([9,8,7],[a,b,c])! => factorial(matrix([9,8,7],[a,b,c])) eval=> Object has no method 'isConstant'

It should iterate over the vector/matrix and compute the factorial for each element.

**Comment by jiggzson** [comment]
Fixed.
