### ISSUE TITLE
π and e are substituted in vectors before evaluation

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#281]
[π,b,c]+[d,e] => [3.141592653589793+d,2.718281828459045+b]
They are supposed to be symbolic placeholders before evaluation. How come they are substituted before evaluation in vectors?

**Comment by jiggzson** [comment]
Interesting point. I'll look into this.

**Comment by jiggzson** [comment]
I get **[π,b,c]+[d,e]**

**Comment by Happypig375** [comment]
Hmm, good point. Will look at this later.

**Comment by jiggzson** [comment]
@Happypig375 Have you looked into this? Can this be closed?

**Comment by Happypig375** [comment]
Merge into #311
