### ISSUE TITLE
Large numbers throw

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#284]
22222222222222222222.1 => Error: Invalid integer: 22222222222222222222.1
22222222222222222222.1e0 => 222222222222222230000

LOL What??

**Comment by Happypig375** [comment]
Note:
22222222222222222222.1e0 => 222222222222222230000 is demo only. The actual library returns 222222222222222222221.

**Comment by jiggzson** [comment]
Moving to #247
