### ISSUE TITLE
Solve with decimal exponents = Invalid results

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#286]
solve(3^pi-y^0.23=1,y) => Error: Invalid integer: NaN (@demo) / TypeError (@master / @dev)

**Comment by Happypig375** [comment]
solve(a^pi-y^b=1,y) => [(-a^pi+1)^b^(-1)]
solve(a^pi-y^0.23=1,y) => [] should=> [(-a^pi+1)^(100/23)]

**Comment by jiggzson** [comment]
moving to #322
