### ISSUE TITLE
Factor is not factoring properly

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#287]
factor(x^5-x^4-x+1) => -(-1+x)\*(1+x)\*(1+x^2)
That is -x^4+1.
The input should factorize to -(-1+x)**^2**\*(1+x)\*(1+x^2).

**Comment by Happypig375** [comment]
And also
factor(x^5-y^5) => -y^5+x^5 should=> (x - y) (x^4 + x^3 y + x^2 y^2 + x y^3 + y^4)

**Comment by jiggzson** [comment]
@Happypig375 This issue should be fixed. Keep in mind that factor is a work in progress. Try to keep all issues that you find with factor in issue #219. I'll be going down that list when I tackle factoring. When you keep issues grouped and in logical order it allows me to better schedule myself.

**Comment by Happypig375** [comment]
:ok: :ok_hand:
