### ISSUE TITLE
log(a,a) is part of a result of log

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#290]
log(a^x,a) => log(a,a)*x

log(a,a) is 1, so it can just return x.

**Comment by Happypig375** [comment]
Also log(-2,2) explodes.
log(-2,2) => 199952529166524919968532228982456542372282611811919580563445051818274654665893911159022727197411389766640164164124665122446400534156424598474842480790013910171293147288756660436916321448065342822974666658989080091/1342747117352244142241331479545853859765814028897328589561194257072559162744216412274450370376990170714806603234294879807832669177051544909

**Comment by Happypig375** [comment]
log(-2,2) case should be merged into #181. Close this?

**Comment by jiggzson** [comment]
Sure let's move it there.
