### ISSUE TITLE
gcd throws for negative powers of variables

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#292]
gcd(x^-1,x) => Error: Polynomial Expected! Received x^(-1)
With reference to #123:
>Returning gcd(x^y,x) is the best response

It should evaluate to gcd(x^-1,x).

**Comment by Happypig375** [comment]
Note:
https://github.com/jiggzson/nerdamer/issues/123#issuecomment-333855255
>gcd(3,x) => 3 (@demo, @dev and @master)
Wow.

**Comment by Happypig375** [comment]
Oh, you are following Wolfram Alpha's result (x^(-1)) I see.
However, gcd(x^-2,x^-0.5) => Error: Polynomial Expected! Received x^(1/2) should=> 1/x^2.5 according to Wolfram Alpha.

**Comment by jiggzson** [comment]
I wasn't actually. I wrote out the denominator for both and then pulled the gcd. I then put back the denominator. I'll look into that. You're getting that answer because as stated it expects a polynomial.

**Comment by Happypig375** [comment]
>I wasn't actually.

Oh, my bad.
>I'll look into that.

Thanks in advance
