### ISSUE TITLE
Setting the USE_MULTICHARACTER_VARS setting to false causes numbers with more than one digit to be recognized as a product of individual digits

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#293]
Wow, such a long title. The problem is here: 
20 => 0 eval=> 0
23 => 6 eval => 6
29 => 18 eval=> 8
42 => 8 eval=> 8
98 => 72 eval=> 14
777 => 343 eval=> 36
etc.

**Comment by Happypig375** [comment]
Is omitting capital characters in the regex matching intentional?
This makes:
(nerdamer.set("USE_MULTICHARACTER_VARS",false),nerdamer('sa sAsBC').text()) => a*s*sAsBC

**Comment by jiggzson** [comment]
Not intentional. I'll make the regex case insensitive.

**Comment by jiggzson** [comment]
@Happypig375 this should be fixed.

**Comment by Happypig375** [comment]
👌 :+1:
