### ISSUE TITLE
pfactor(15!-1) => 1

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#294]
Obviously incorrect. It should be (1510259)\*(17)\*(31^2)\*(53).

**Comment by Happypig375** [comment]
@jiggzson Did you mistakenly reference this issue from that commit? It is still not fixed.

**Comment by jiggzson** [comment]
Yes I did. Good catch

**Comment by Happypig375** [comment]
YES!!! nerdamer.pfactor("15!-3"), nerdamer.pfactor("15!+1") and nerdamer.pfactor("15!+11!") all give the same output as Wolfram Alpha. Thanks a lot!
