### ISSUE TITLE
Evaluate cannot be called on coeffs

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#296]
nerdamer('coeffs(x,x)').evaluate().text() => TypeError: this.symbol.text is not a function

**Comment by jiggzson** [comment]
I see. This should probably wrapped in a vector.

**Comment by Happypig375** [comment]
Omg. Thank god you are finally back. Was worried about the serious bugs (#300) not being fixed in time.

**Comment by jiggzson** [comment]
You're right. Fixing

**Comment by Happypig375** [comment]
Thanks for fixing 👍
