### ISSUE TITLE
solveEquations have empty output (not even an empty vector)

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#297]
```js
nerdamer('solveEquations(x=8,x)').text()
```
Output:
```
```

**Comment by jiggzson** [comment]
It does. Just console.log x.
```javascript
var x = nerdamer('solveEquations(x=8,x)');
console.log(x);
//{ symbol: [] }
The output just happens to be wrapped in an Expression object
```

**Comment by Happypig375** [comment]
>It does.

I can't infer what you are saying...?
>The output just happens to be wrapped in an Expression object

The output should be 8?

**Comment by jiggzson** [comment]
Lol. Yup. I got too focused on the empty string. I'll fix it.

**Comment by Happypig375** [comment]
nerdamer("solveEquations(x+y=8)") => [-(-8+y)]
Should the negative sign be expanded into 8+y?

---
Input:
```js
nerdamer("solveEquations(x+y=8,x)")
```
Output:
```
```
🤣

**Comment by jiggzson** [comment]
Moving to #322
