### ISSUE TITLE
pfactor regression: hangs on PI

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#298]
pfactor(PI)
0.7.12 / demo: ((2)\*(29)\*(4238809))\*((3)\*(53)\*(577)\*(853))^(-1)
0.7.13 / master / dev: (Hangs)

**Comment by jiggzson** [comment]
This should probably return pi since it cannot be factored.

**Comment by jiggzson** [comment]
@Happypig375 Fixed
