### ISSUE TITLE
Ceiling function it's not being parsed

### ISSUE THREAD

**Issue by DouglasdeMoura** [jiggzson/nerdamer#30]
I've tried on demo and in the javascript console:

```javascript
var e = nerdamer('ceiling(2.4)', null, 'numer');
console.log(e.text());
//returns ceiling(2.4), expected 3
``` 

It's not working. I didn't detect the issue on the code. Maybe you guys can take look?

**Comment by jiggzson** [comment]
Can you try ceil instead of ceiling?

**Comment by DouglasdeMoura** [comment]
Returns
```
Error: ceil is not a supported function.
```

**Comment by jiggzson** [comment]
Functions from the Math object should be able to be accessed by the name of
the method. So Math.ceil becomes ceil

**Comment by jiggzson** [comment]
Ok. Because the link was not created. I'll fix that shortly.

**Comment by jiggzson** [comment]
It's fixed in master. See if that does the trick?

**Comment by DouglasdeMoura** [comment]
It did. Thanks.
