### ISSUE TITLE
solve(-5*sqrt(14)-14x-10,x) ends up in an infinite loop

### ISSUE THREAD

**Issue by menzelths** [jiggzson/nerdamer#300]
Substituting sqrt(14) with a normal number like 3.9 works fine.

The example given does not run in your demo.

**Comment by Happypig375** [comment]
It loops in the actual library too.

**Comment by Happypig375** [comment]
https://github.com/jiggzson/nerdamer/blob/c419f2d1547e4939b5123d524df030c60d30d2fd/Solve.js#L474-L488
This function calls itself infinitely many times.

**Comment by Happypig375** [comment]
If I add `return symbol;` between line 485 and 486 nerdamer returns [-79372967/38707344] which is correct. Submitting as PR and see if any tests fail.

**Comment by Happypig375** [comment]
Surprisingly, all tests passed! Wow. 😮

**Comment by Happypig375** [comment]
Don't have time to make symbolic output, that is just a workaround by giving numeric answers.

**Comment by jiggzson** [comment]
This is no good. @Happypig375 thanks for the PR. I haven't had a chance to check it yet but keep in mind that correct_denom (hey I had to call it something) function attempts to write out the denominator out of either side. So for instance (x^2+7)/x=x+5 will be rewritten to x^2+7=x(x+5). Somehow it's getting confused with the sin function. I'll take a look at the PR and hopefully it fixed this.

**Comment by jiggzson** [comment]
@Happypig375 Thank for taking a swing at this one. I really appreciate the effort. I fixed this on the dev branch. It's failing 4 tests but not because the answers are wrong. @menzelths thanks for the reporting this error and providing the solution along with it.

**Comment by Happypig375** [comment]
@jiggzon Thanks for finally fixing this! 👍

**Comment by Happypig375** [comment]
But this removed symbolic answers for solve... 😞

**Comment by jiggzson** [comment]
Can you give me a few examples? I desperately need to add more tests for Solve.

**Comment by Happypig375** [comment]
Using Wolfram Alpha:

Equation|Solution(s)
-|-
-5 sqrt(14)x-14x^2 sqrt(83)-10=0|[ -(i (sqrt(5 (8 sqrt(83) - 5)) - 5 i))/(2 sqrt(1162)), (i (sqrt(5 (8 sqrt(83) - 5)) + 5 i))/(2 sqrt(1162))]
-5\*sqrt(14)x-14x^2\*sqrt(83)-10x=0|[0, (-5/7 - 5/sqrt(14))/sqrt(83)]
sqrt(97)x^2-sqrt(13)x+sqrt(14)x+sqrt(43)x^2+sqrt(3)\*sqrt(101)=0|[ (sqrt(13) - sqrt(14) - i sqrt(-27 + 2 sqrt(182) + 4 sqrt(13029) + 4 sqrt(29391)))/(2 (sqrt(43) + sqrt(97))),(sqrt(13) - sqrt(14) + i sqrt(-27 + 2 sqrt(182) + 4 sqrt(13029) + 4 sqrt(29391)))/(2 (sqrt(43) + sqrt(97)))]
sqrt(x^3)+sqrt(x^2)-sqrt(x)=0|[0,1/2 (3 - sqrt(5))]

**Comment by jiggzson** [comment]
@Happypig375 enlighten me, did any of these test ever pass before? That would be strange since the library didn't even recognize them as polynomials before (not the last one). Either way this has been fixed. The last one gets solved numerically because of the sqrt(x^3)+ |x|.

**Comment by menzelths** [comment]
I can confirm that the bug is fixed. I leave this thread open for further discussion.
