### ISSUE TITLE
(k-1)^2+(k-1)^2=(2k-2)^2

### ISSUE THREAD

**Issue by menzelths** [jiggzson/nerdamer#303]
This is obviously wrong :-(

**Comment by jiggzson** [comment]
Agreed. Easy fix and I'll make sure to take care of this. Thanks @menzelths

**Comment by jiggzson** [comment]
@menzelths. Fixed on the dev branch. There are 4 failing tests but those are related to rounding issues and order of the solutions in solve.

**Comment by jiggzson** [comment]
Fixed

**Comment by menzelths** [comment]
Confirmed!
