### ISSUE TITLE
A rather special bug

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#305]
To celebrate @jiggzon being back, here is a rather special exception.

acsc(π/4)+acos(π/2) eval=> RangeError: Maximum call stack size exceeded

**Comment by jiggzson** [comment]
@Happypig375 I get **acos((1/2)*pi)+asin(4*pi^(-1))**. Which version are you using?

**Comment by Happypig375** [comment]
Remember to call evaluate to get this error.

**Comment by jiggzson** [comment]
You're getting this because trig and inverse functions don't do complex yet. You wouldn't by any chance have a neat little list handy would you? That would definitely help speed up implementation.

**Comment by jiggzson** [comment]
Related to #181 (Complex numbers). Moving there.
