### ISSUE TITLE
Please expose solveEquations to the demo

### ISSUE THREAD

**Issue by menzelths** [jiggzson/nerdamer#306]
In the demo you show "solveEquations" in the list of possible funcions to use.
In the documentation you only show something like

nerdamer.solveEquations(["x+y","3x-2"]);

but for the demo something like

nerdamer("solveEquations(['x+y','3x-2']");

would be necessary. Could you please provide this functionality? Would be very important for my project. I would also offer a beer or two.
I use your library on a daily base in "production" and it is running really well. Thank you for sharing your project with the community.

**Comment by Happypig375** [comment]
Or alternatively update the demo to 0.7.13 as #186 is now implemented. 
The demo is stuck at 0.7.12.
nerdamer("solveEquations[x+3=y,x*2=y]") can be executed as of 0.7.13 but not 0.7.12.

**Comment by menzelths** [comment]
Thank you for the information.
