### ISSUE TITLE
Problem with toTeX()

### ISSUE THREAD

**Issue by menzelths** [jiggzson/nerdamer#307]
In 0.7.12 the following code ran without issues:

`
var a=nerdamer("vector(1,2,3)");              
console.log(a.toTeX());
` 

Using 0.7.13 it returns an error: 

`nerdamer.core.js:5820 Uncaught TypeError: symbol.clone is not a function
    at Object.latex (nerdamer.core.js:5820) ...
`

**Comment by jiggzson** [comment]
Yes. I noticed. That issue popped up in several functions. I'll take a look at this shortly. @Happypig375 just reported the same issue.

**Comment by Happypig375** [comment]
>@Happypig375 just reported the same issue.

➡️https://github.com/jiggzson/nerdamer/issues/247#issuecomment-345404606⬅️

**Comment by Happypig375** [comment]
Is this related to https://github.com/jiggzson/nerdamer/issues/194?

**Comment by jiggzson** [comment]
@menzelths this should be fixed.

**Comment by menzelths** [comment]
Thank you, this is working now.

Now I tried

`
nerdamer("vector(1,2,3)").toTeX() 
`

and I get the error

`
TypeError: symbol.clone is not a function 
` 

This is due to an error around line 6770 in nerdamer.core.js (commit 0be51b8). The code is:

`
 latex: function(option) { 

            var tex = [];
            for(var el in this.elements) {
                tex.push(LaTeX.latex.call(LaTeX, this.elements[el], option));
            }
            return '['+tex.join(', ')+']';
        } 
`
but I suppose it should be:

`
latex: function(option) {

            var tex = [];
            for(var i=0;i<this.elements.length;i++) {
                tex.push(LaTeX.latex.call(LaTeX, this.elements[i], option));
            }
            return '['+tex.join(', ')+']';
        } 
`

I am at work right now and have no access to my IDE, so maybe you could change it just like that.

**Comment by menzelths** [comment]
PR is merged and seems to work. Closing issue.
