### ISSUE TITLE
#195 but different results

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#311]
Using the examples from #195.
divide(3e,e) => 0.3333333333333333+0.3333333333333333*0
eval=> 0.3333333333333333
Evaluating cancels out the part with the multiplication with 0.

divide(3π,π) => TypeError: this.symbols[x].power.multiply is not a function

**Comment by jiggzson** [comment]
I can't reproduce this issue. I get 3. Even after calling evaluate.

**Comment by Happypig375** [comment]
>I can't reproduce this issue.

So I suspect that that this is an Android WebView issue (this is what I am using). If you don't want to continue to investigate, close this.
