### ISSUE TITLE
#276 reworded

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#312]
This returns an undefined from nowhere: integrate(sqrt(6)) => 6*undefined
Wolfram Alpha: integrate(sqrt(6)) => sqrt(6) x

Clearly a bug

(Reference to #276)

**Comment by jiggzson** [comment]
Correct. But you never specified with respect to what. I guess it should throw when it's a constants or assume x as Wolfram Alpha does. When I do specify it gives back 6*x and that is definitely wrong. I'll fix this.

**Comment by Happypig375** [comment]
Ayy, now the result of integrate(sqrt(8)*6^(1/2)) is on par (not quite actually, see https://github.com/jiggzson/nerdamer/issues/210#issuecomment-346027346 ) with Wolfram Alpha. Great!
