### ISSUE TITLE
All variables lost after solveEquations

### ISSUE THREAD

**Issue by menzelths** [jiggzson/nerdamer#313]
After applying solveEquations() to a linear equation systems also all other variables are lost. 

I saw that in the routine for solveEquations (line 157 in solve.js) you call clearVars(): I see the point for doing that but it should be restricted only to the variables used in the equation system. Elsewise all other variables in a calculation get lost :-(

**Comment by menzelths** [comment]
Solution:

no clearVars() in line 157 but inserting 
             
            for (var i=0;i<vars.length;i++){
                nerdamer.setVar(vars[i],"");
            }
after line 176 does the trick. Hope that helps :-)

**Comment by Happypig375** [comment]
Can you submit a PR and see if any tests fail?
(I am on a phone right now, inconvenient to send PRs)

**Comment by menzelths** [comment]
I am closing this, too. Bugfix seems to work.
