### ISSUE TITLE
Integral with abs/sign goes crazy

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#324]
integrate(abs(-2+e^x)) => integrate(abs(-2+e^x),x)
Unsolved!

integrate((e^x-2)/sign(e^x-2)) => integrate(-2*sign(-2+e^x)^(-1),x)+integrate(sign(-2+e^x),-2+e^x)
What!?

(Ref: https://github.com/tranleduy2000/ncalc/issues/23)

**Comment by Happypig375** [comment]
Wait... That should be defint lol
First one is now invalid but the second one still stands.

**Comment by jiggzson** [comment]
Moved to #334
