### ISSUE TITLE
gcd(gcd(a,b),c) => 1

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#332]
This is blocking me from implementing #329.

**Comment by jiggzson** [comment]
How is that not the answer?

gcd(a,b) = 1
gcd(1, c) = 1

**Comment by Happypig375** [comment]
Because you don't know what a and b even are yet.
Refer to https://github.com/jiggzson/nerdamer/issues/123#issuecomment-326306729.

**Comment by Happypig375** [comment]
Plus, 
gcd(a,b) => gcd(a,b)
gcd(gcd(a,b),c) => 1
it is inconsistent.

**Comment by Happypig375** [comment]
Ref: Wolfram Alpha
gcd(gcd(a,b),c) => gcd(a,b,c) //My example
gcd(a*x,b*x) => x //Your example
gcd(1,c) => gcd(1,c) //Yourexample
gcd(8x, 12x) => 4x //Your example
gcd(a,b) => gcd(a,b) //My example

**Comment by jiggzson** [comment]
@Happypig375 Honestly, this is not an option. Mucking around this definition of gcd breaks other algorithms such as integration. If you're having trouble implementing #329 then just don't worry about it. I'll take care of it.

**Comment by Happypig375** [comment]
@jiggzon So Wolfram Alpha is wrong?

**Comment by jiggzson** [comment]
I never said that. It looks to me that they're using two sets of assumptions vs sticking to one. With gcd(a,b) they might be assuming 2 univariate polynomials. With gcd(ax, bx) they're probably assuming 2 multivariate polynomials. Odds are that they're choosing based on the parameters of the problem but I can't know for sure.

**Comment by Happypig375** [comment]
Ok. Understood.
