### ISSUE TITLE
Circle Equations

### ISSUE THREAD

**Issue by VishalKumarMitra786** [jiggzson/nerdamer#34]
The library has helped me a lot in building a graphing system, I am stuck at one place , Can you people design a way where if I can  detect any equation of the form (x-a)^2 + (x-b)^2 = r^2 (i.e. is a generalized circle equation) and  can let me know that its a circle (i.e. I want to know if any user types in this type of circle equation i want to know its a circle )

**Comment by jiggzson** [comment]
Will a, b,  and r be known?

**Comment by VishalKumarMitra786** [comment]
Ya it will be known like if eq is of the form
((x+2)-3)^2 + ((y+6-3)+4)^2 = 4 ... Or any circle. Equation like x^2 + y^2 = 4 etc

If you can help me out in detecting a circle that would be great!

**Comment by brosnanyuen** [comment]
I think nerdamer needs a better factoring algorithm.

**Comment by jiggzson** [comment]
Agreed. I'm working on it.

**Comment by jiggzson** [comment]
As Brosnan mentioned if the equation is in expanded form then you need to factor and that's still being worked on. However if it's in factored form then something like this:

```javascript
//get the core
var core = nerdamer.getCore();
core.Symbol.prototype.isSquare = function() {
    return this.power === 2;
};
//check if the symbol is in the form of (x-h) or (y-k)
core.Symbol.prototype.isXhOrYk = function() {
    //if it's just a simple variable then it's already in that form
    if(this.group === core.groups.S) return true;
    //it's going to be composed of two variable x and x^0 so all we have to do is
    //check for x^1
    if(this.group === core.groups.CP) {
        if(this.length === 2) {
            for(var x in this.symbols) {
                if(x !== '#' && this.symbols[x].group === core.groups.S) return true; 
            }
        }
        return false;
    }
};
core.Symbol.prototype.isCircle = function() {
    //it's going to have the (y-k)^2 term the (x-h)^2 term and r^2 term
    if(this.group === core.groups.CP && this.length === 3) {
        var c = 0;
        for(var x in this.symbols) {
            var symbol = this.symbols[x];
            if(symbol.isSquare() && symbol.isXhOrYk) c++;
            if(c > 2) return false;
        }
        return true;
    }
    return false;
};
//Link the isCircle function to the wrapper
core.Expression.prototype.isCircle = function() {
    return this.symbol.isCircle();
};

var x = nerdamer('(x^2-1)+(y^2+z)+4');
console.log(x.isCircle());
```

Of course this is a quick and dirty way of checking and might still needs some work but hopefully you get the idea. Forgive me if I'm overlooking something.

**Comment by VishalKumarMitra786** [comment]
First of all thanks for such fast response, The above solution helped me  in detecting a circle equation but i guess there is some issue in the equation of the form:
(x+3)^2 + (x+4)^2 + 4  this is a circle equation and what is happening that you are checking the group as well as length so what is happening that in this case I am getting the "Length as 4 and not 3"
so the conditions fails , more over the below equation which was resulting to false also holds the length as 4 so its correct it will result to false but the above equation i suggested is also a circle equation so it has to be  true but i am getting it false as Length is 4
 `var x = nerdamer('(x^2-1)+(y^2+z)+4');
console.log(x.isCircle()); 
//false

**Comment by VishalKumarMitra786** [comment]
I have updated the code you provided to me  its working fine for me now if you can provide a better way would be appreciated, Thanks once again for helping me out.

' core.Symbol.prototype.isCircle = function() { 
if (this.group === core.groups.CP && this.length>2) {
                var c = 0;
                var r;
                var terms=[];

                for (var x in this.symbols) {
                    var symbol = this.symbols[x];
             
                    if (x !== "#") {
                        terms.push(symbol.toString());
                        if (symbol.isSquare()) {

                        } else {
                            return false
                        }

                        if (symbol.isXhOrYk) {
                            c++;
                        }
                    } else {
                        r = symbol.multiplier;
                    }
                    if (c > 2) return false
                }
                return true
            }
            return false
}  '

**Comment by jiggzson** [comment]
No problem. Thanks.
