### ISSUE TITLE
Update the wiki dependency image

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#342]
Calculus.js actually depends on Algebra.js.
However, the dependency graph does not show that.

**Comment by jiggzson** [comment]
This was started by @brosnanyuen. If it helps you, by all means update it.  I may have to reorganize this at some point since you made a good point when you mentioned that it would be better for laplace to be in Calculus.js. Line could be in the core or Geometry.js etc. Or maybe I'll just roll everything back into one bundle. I'm open for discussion on this one.

**Comment by Happypig375** [comment]
>If it helps you, by all means update it.

@bronsnanyuen Do you have the original image file?
>it would be better for laplace to be in Calculus.js. Line could be in the core or Geometry.js etc. Or maybe I'll just roll everything back into one bundle.

I will list out the pros and cons:

Option|Sorting every function into their respective module|Rolling everything back
-|-|-
Pros|More organisation of code and tests|Don't need to care about sorting everything; no need to have different files
Cons|Harder to maintain (more files)|GitHub will cease to display files that are too large, harder to view the file online; Harder to maintain (Easier circular dependencies)

@menzelths @ljacqu Can you comment on this?

**Comment by Happypig375** [comment]
@brosnanyuen (Correct spelling)
Do you have the original image file of the wiki dependency image?

**Comment by jiggzson** [comment]
@Happypig375, Seeing as @brosnanyuen is not responsive do you want to just take down or replace the image?

**Comment by Happypig375** [comment]
Take a look at the new home page 😄

**Comment by Happypig375** [comment]
I think that https://github.com/jiggzson/nerdamer/wiki/nerdamer.core.js should be moved to the nerdamer website. It will be totally forgotten if it is left in the wiki.

**Comment by jiggzson** [comment]
Nice. Probably a little easier to maintain.

**Comment by Happypig375** [comment]
And https://github.com/jiggzson/nerdamer/wiki/Versions...
That is very outdated.
Should it be updated or something?

**Comment by Happypig375** [comment]
Oops

**Comment by jiggzson** [comment]
Do we still need this one?

**Comment by Happypig375** [comment]
https://github.com/jiggzson/nerdamer/issues/342#issuecomment-355249452:
>I think that https://github.com/jiggzson/nerdamer/wiki/nerdamer.core.js should be moved to the nerdamer website. It will be totally forgotten if it is left in the wiki.

This one is still not yet done.

**Comment by jiggzson** [comment]
@Happypig375, It was Brosnan's intent to document the internal's of nerdamer hence the reason for that wiki page. However I already provide the user a list of reserved names with nerdamer.reserved() and err is already covered under #353 so there's no reason to keep this issue open.
