### ISSUE TITLE
undefined with getCore().Frac

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#343]
While implementing #329, I came along this:
`new nerdamer.getCore().Frac(1)` => `undefined`
`nerdamer.getCore().Frac.create(1)` => `1`

~~This results in `nerdamer.getCore().PARSER.divide(new nerdamer.getCore().Expression("(x^8+4*x^7+4*x^6+3*x^5+12*x^4+12*x^3)"), new nerdamer.getCore().Expression("(x^8+4*x^7+4*x^6+3*x^5+12*x^4+12*x^3)"))` => `undefined`, one of the failing tests in #337 where the test threw for undefined.~~ Edit: Not this

**Comment by Happypig375** [comment]
Here is `new Frac(1)` being used in the Symbol constructor:
https://github.com/jiggzson/nerdamer/blob/4efe6de91758cf08540ced33b9672234f3375a86/nerdamer.core.js#L1916
And here the undefined occurs:
https://github.com/Happypig375/nerdamer/blob/22d631c8cbd714ddf8d40e7f63cb922119dec4ef/Algebra.js#L2370

**Comment by jiggzson** [comment]
You're calling new on the wrong function. What you're essentially doing is 
```javascript
var core = new nerdamer.getCore();
var x = core.Frac(1);
console.log(x); 
//undefined
```
What you're looking for is

```javascript
var core = nerdamer.getCore();
var x = new core.Frac(1);
console.log(x);
//{ [Number: 1]
//  num: { [Number: 1] value: 1, sign: false, isSmall: true },
//  den: { [Number: 1] value: 1, sign: false, isSmall: true } }
```

**Comment by jiggzson** [comment]
@Happypig375 I think the undefined occurs in the getDenom method. I got bit by this as well when doing the **inverse laplace** function. I'm updating it to return **1** instead of _undefned_

**Comment by jiggzson** [comment]
@Happypig375 Can you let me know if this issue still applies? The getDenom method should no longer return _undefined_.

**Comment by Happypig375** [comment]
Latest dev:
```js
var core = nerdamer.getCore();
var x = new core.Frac(1);
document.writeln(x.getDenom());
```
```
TypeError: x.getDenom is not a function
```
Wut?

**Comment by jiggzson** [comment]
Frac does not have getDenom. Only Symbols do. Objects of the Frac class are already split into numerator and denominator. 

```javascript
var core = nerdamer.getCore();
var x = new core.Frac(0.625);
var denominator = x.den;
var numerator = x.num;

console.log(numerator.toString(), denominator.toString());
```

**Comment by Happypig375** [comment]
Oh, OK.
I think this can be closed now.
