### ISSUE TITLE
calculation bug with cross productin the demo (probably also in the library)

### ISSUE THREAD

**Issue by menzelths** [jiggzson/nerdamer#344]
P:vector(9,-4,1)

S:vector(-1,1,-1)

R:vector(3,-8,2)

PR:R-P

SP:P-S

d1:cross(PR,SP)

d2:cross(vector(6,-4,1),vector(10,-5,2)) 

d2 gives back [-3,-2,10], which is correct, d1 results to [-3,22,70]. In the second two rows of d1 the subtraction has some problem with negative numbers.

**Comment by Happypig375** [comment]
I can CONFIRM this on dev branch.
```js
nerdamer.setVar('P','vector(9,-4,1)');
nerdamer.setVar('S','vector(-1,1,-1)');
nerdamer.setVar('R','vector(3,-8,2)');
nerdamer.setVar('PR','R-P');
nerdamer.setVar('SP','P-S');
nerdamer.setVar('d1','cross(PR,SP)');
nerdamer.setVar('d2','cross(vector(6,-4,1),vector(10,-5,2))');
nerdamer("d1"); //[-3,22,70] 
nerdamer("d2"); //[-3,-2,10] 
```

**Comment by jiggzson** [comment]
@menzelths thanks. From your example it seems that you're expecting PR to equal [6, -4, 1]. However subtraction would be [9-3, -8--4, 1-2] = [6, -4, -1]. Correct? The last one item should be negative. Correct? I'll have this fixed soon.

**Comment by menzelths** [comment]
Sorry, my fault. I did a calculation error on my own. It must be: [3-9,-8--4,2-1]=[-6,-4,1].
With this result nerdamer is doing everything the correct way.
Thank you for your time :-)

**Comment by jiggzson** [comment]
@menzelths No problem.
