### ISSUE TITLE
solve(((x+1)*((x+1)+1))/2=n,x) gives wrong result

### ISSUE THREAD

**Issue by jiggzson** [jiggzson/nerdamer#345]
Expected: +/-(sqrt(8*n+1)+3)/2
Gives: +/-(sqrt(4*n+1)+3)/2

**Comment by Happypig375** [comment]
Cross-ref: #322

**Comment by Happypig375** [comment]
Compacted reproduction:
solve((x+1)(x+2)/2=n,x) => (±sqrt(4n+1)+3)/2
solve((x+1)(x+2)=2n,x) => (±sqrt(8n+1)+3)/2

I guess that this has something to do with correctDenom from earlier.
