### ISSUE TITLE
Column number in ParseError

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#347]
I would be able to locate the error faster.
Aside from peoviding it in the error string, provide a property in ParseError so that it is easier to retrieve.

**Comment by jiggzson** [comment]
Agreed. This is one of those things that I keep meaning to get to but I  keep putting off. It would help me in the demo as well since I currently just use a catch-all method for alerting the user that something went wrong.

**Comment by jiggzson** [comment]
@Happypig375, added.

**Comment by jiggzson** [comment]
You're right. I'll check this out in a bit.

**Comment by jiggzson** [comment]
@Happypig375, I remember this issue being fixed with 0.8.x but I never closed it or checked back with you. Can this be closed?

**Comment by Happypig375** [comment]
```
sin(x^2)\3
```
```
TypeError: _[e.action] is not a function
```

**Comment by Happypig375** [comment]
```
1+x√π
```
```
InvalidVariableNameError: x√π is not a valid variable name
```

**Comment by jiggzson** [comment]
@Happypig375, Thanks. I think there's one more error that I have to tack on to this, and that's the fact that errors involving functions provide the wrong column number. For instance, `cot(` gives `ParityError: Missing closed bracket for bracket at 1`,  which is the wrong column number.

**Comment by Happypig375** [comment]
```
*243
```
```
OperatorError: Not a prefix operator
```
```
1?
```
```
Error: Invalid integer: NaN
```
`243+*` Actual:`OperatorError: A prefix operator was expected at 5` Expected: `OperatorError: A prefix operator was expected at column 5`

**Comment by jiggzson** [comment]
@Happypig375, I expect some ambiguity to remain and this goes back to the discussion we had in #130. `1?` is one of those.
