### ISSUE TITLE
coeffs: ambigious to use

### ISSUE THREAD

**Issue by peey** [jiggzson/nerdamer#352]
`nerdamer.coeffs` returns a nerdamer object which looks like an array when you apply `.toString()` on it and also has a `.each` which for a second led me into think that it returns an array. 

I later learned that nerdamer also has vector support and this above returned value is likely a vector. Please update the documentation to say that it returns a vector and corresponding entries can be accessed by `nerdamer.vecget`

**Comment by Happypig375** [comment]
This is because #296 is fixed while the documentation is not updated.
With the bugfix of #296, the return type of coeffs has changed from JavaScript array to nerdamer vector.
So, I am cross-referencing this with #141.

**Comment by jiggzson** [comment]
@peey This has been updated on the dev branch and coeffs always returns a vector. I've also updated the documentation on the gh-pages_dev branch. Thanks for reporting.
