### ISSUE TITLE
Issue with multiplication in nested square roots

### ISSUE THREAD

**Issue by peey** [jiggzson/nerdamer#360]
Basically the issue is that if I have an expression which looks like `sqrt(2*sqrt(5))` then it's being wrongly simplified to `sqrt(sqrt(5))`. Same for `sqrt(2*sqrt(5))` which is being simplified to `sqrt(sqrt(5))`.

```
> b = nerdamer("2*sqrt(2*sqrt(5))")
> b.toString()
'2*5^(1/4)' // incorrect
> b = nerdamer("2*sqrt(2 + sqrt(5))")
> b.toString()
'2*sqrt(2+sqrt(5))' // this is correct
> b = nerdamer("sqrt(3* sqrt(5))")
> b.toString()
'5^(1/4)' //incorrect
> b = nerdamer("sqrt(sqrt(3)* sqrt(5))")
> b.toString()
'3^(1/4)*5^(1/4)' // correct
> b = nerdamer("sqrt(sqrt(sqrt(3))* sqrt(5))")
> b.toString()
'3^(1/8)*5^(1/4)' // correct
> b = nerdamer("sqrt(k*sqrt(5))")
> b.toString()
'5^(1/4)*sqrt(k)' // correct
> a = b.sub("k", 3)
> a.toString()
'5^(1/4)*sqrt(3)' // correct
```

Current workaround I'm using until this is fixed is to use `b = nerdamer("sqrt(k*sqrt(5))")` and then use `.sub` to substitute my value of `k`. Or simply avoid writing nested `sqrt` and manually expand it to top-level `term1^power1 * term2 ^ power2`

Some more neurotic results. I think the issue is in the code which simplifies nested powers, it's working incorrectly.

```
> b = nerdamer("(2*sqrt(5))^(1/2)")
> b.toString()
'5*sqrt(2)' // incorrect, should be "sqrt(2)*((5)^(1/4))"
> b = nerdamer("(sqrt(5))^(1/2)")
> b.toString()
'5' // incorrect, should be "(5)^(1/4)"
> b = nerdamer("(5^(1/2))^(1/2)")
> b.toString()
'5'  // incorrect, should be "(5)^(1/4)"
```

**Comment by peey** [comment]
I first posted this as a comment to https://github.com/jiggzson/nerdamer/issues/239, but I decided to make a separate issue since nerdamer is actually giving correct results in that issue, albeit not simplifying it as much as it could. 

In this issue the computation by nerdamer is incorrect

**Comment by jiggzson** [comment]
Fixed! Thanks. It's crazy how long this one has been in there.

**Comment by peey** [comment]
Awesome!
