### ISSUE TITLE
nthroot becomes nthpower

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#362]
nthroot(2,2) => 4
nthroot(3,3) => 27

¯\\\_(ツ)\_/¯

**Comment by jiggzson** [comment]
Fixed.

**Comment by Happypig375** [comment]
Wow didn't expect you at this time :smiley:
Anyways nerdamer.com is down so maybe later I will verify this.

**Comment by Happypig375** [comment]
Yup, fixed.
But, can nthroot only evaluate when numer option or evaluate method is used?
This makes nthroot in line with sqrt.

**Comment by jiggzson** [comment]
No problem.
