### ISSUE TITLE
pfactoring a product of factorials

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#366]
pfactor(product(n!,n,1,10)) => (2^12)\*(5^12)\*(733)\*(9084047181589) should=> (2^38)\*(3^17)\*(5^7)\*(7^4)

**Comment by jiggzson** [comment]
Both this one and #285 are more than likely related. Both functions fall back to JavaScript when the expression contains 1 variable. I'll just stick to using the symbolic layer of nerdamer.

**Comment by jiggzson** [comment]
Fixed on dev branch.

**Comment by Happypig375** [comment]
pfactor(product(n!,n,1,30)) => Error: 79959631528770670600322037454897824976792430707106611658531105568420623057823058204406300276129173697769238298117257446827525920399207590372612824866949329475045338094293229818656245740234951168513312204538663055609170465072773314478245835098717506292940800000000000000000000000000000000000000000000000000000000000000000000 is not a valid variable name

**Comment by jiggzson** [comment]
Partially fixed. I need a better algorithm for factoring numbers this big. This would also fall under big numbers.

**Comment by jiggzson** [comment]
moving to #221
