### ISSUE TITLE
Partial fraction not evaluated

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#367]
partfrac((4k-1)/(k(k+2))) should=> -1/k+9/(k+2)

**Comment by jiggzson** [comment]
This was specified in c25cad9f280b29647c73945b89a163d799d1a702 but I specified the wrong issue number in the commit message.

**Comment by Happypig375** [comment]
c25cad9: Rolling back solve
I think you referenced the wrong commit.

**Comment by Happypig375** [comment]
It is still fixed though. Closing.
