### ISSUE TITLE
Symbolic factorials

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#369]
https://youtu.be/dBmApl6gkII
(1/2)! can=> sqrt(pi)/2

Two possible implementations:
A. Detect special values in factorial function
Pro: Simple to implement
Con: Need to add new value in code every time a new symbolic answer is found

B. Override factorial function in Calculus.js to use integration
Pro: Answer will be as symbolic as possible
Con: Implementation will be complex, need to wait until definite integrals with infinite limits are implemented

Both have their pros and cons. Thoughts?

**Comment by jiggzson** [comment]
I don't mind detecting special values. If integrate was complete I wouldn't mind relying on it but there's still plenty of work to be done on it. A list of those special values would be very helpful.

**Comment by Happypig375** [comment]
So far I have only found a formula for half factorials on Wikipedia... Might still worth implementing.

**Comment by Happypig375** [comment]
I see that only the (1/2)! is implemented. By the formula for half factorial*s*, I refer to this formula:
![Wiki image](https://wikimedia.org/api/rest_v1/media/math/render/svg/b0bfcd4677abc8eb0581785f2241f8cb1643573a)

**Comment by jiggzson** [comment]
I see. I'll dig into this a little deeper at a later date. Thanks.
