### ISSUE TITLE
Can't parse big integers

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#375]
nerdamer("10^400") => Infinity
nerdamer("1e400") => Uncaught Error: 10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 is not a valid variable name

**Comment by jiggzson** [comment]
This is already on the roadmap. This and several of the other issues previously discussed are part of the movement to incorporate big numbers.
