### ISSUE TITLE
Sort returns same value for multiplication and addition

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#379]
sort(a+b) => [a,b]
sort(a*b) => [a,b]
Maybe unintended?

P.S. What was the use case for sort again?

**Comment by jiggzson** [comment]
Yes that is intentional. It was supposed to give the ability to sort factors, coeffs, and vectors but it's not very well thought out. I'm going to disable it in the demo for now until I can give it a bit more thought.

**Comment by jiggzson** [comment]
I'll be abandoning sort function with the upcoming version. This function serves no purpose.
