### ISSUE TITLE
nerdamer("(x+1)*(x+2)").latex() = "x+1 \cdot x+2" 

### ISSUE THREAD

**Issue by TenobaalTotenamsel** [jiggzson/nerdamer#39]
When using the latex method, the parentheses are not correctly applied, if two or more terms are multiplied in brackets.

**Comment by jiggzson** [comment]
Thanks for pointing that out. I'll look into that right away

**Comment by jiggzson** [comment]
Many thanks Tenobaal. I always appreciate great input. I've pushed a fix to
master. Just a reminder in case you weren't aware. If you file a bug report
on github, you get added to the contributors list.

**Comment by jiggzson** [comment]
By the way, nerdamer switched to rational coefficients. Your floating point
issue should be resolved. Please let me know if that's not the case.

**Comment by TenobaalTotenamsel** [comment]
Yes the problem is resolved. Thank you very much! Also, the floating point error is corrected. Great thing!
