### ISSUE TITLE
Question on order of parameters of logarithm

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#390]
Currently nerdamer uses log(number, base).
However, both my calculator and Wolfram Alpha use log(base, number).

Should we switch?

**Comment by jiggzson** [comment]
@Happypig375, I think the reason I chose that order is because the base is optional. Making the base the first parameter would require me to check the number of arguments and then proceed accordingly. I think the best way forward is to leave this one as-is.
