### ISSUE TITLE
Problem with demo

### ISSUE THREAD

**Issue by menzelths** [jiggzson/nerdamer#392]
B2(a,b,c):=(factorial(a)/factorial(c)/factorial(a-c))*b^c *(1-b)^(a-c)   
sum(B2(20,0.1,k),k,0,10) 

does not work properly and results to 0. Choosing another value for the probability than 0.1 doesn't make any problems.

?

**Comment by Happypig375** [comment]
For me, demo gives 0.999999291139366127200939483377813072286. So I cannot verify this.

However, I also encountered a bug:
sum(B2(20,0.01,k),k,0,10) => 1.000000000000000888178419700125232338905

I suspect that this should not exceed 1.

**Comment by Happypig375** [comment]
Also, a Combination function would be useful here.

Maybe I will write an issue about implementing combinatorics later.

**Comment by jiggzson** [comment]
@menzelths, I get 0.999999291139366127200939483377813072286 as well. Are you running with any custom settings? 

>sum(B2(20,0.01,k),k,0,10) => 1.000000000000000888178419700125232338905
I suspect that this should not exceed 1.

@Happypig375. I'll have to look into this.

**Comment by Happypig375** [comment]
@menzelths Also is your nerdamer up-to-date?

**Comment by menzelths** [comment]
Now it is and the error does not occur any more.
Thanks.
