### ISSUE TITLE
Precision of pi and e

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#394]
In demo:
pi eval=> 3.141592653589793160283277184204067484045
should=> 3.141592653589793238462643383279502884197

e eval=> 2.718281828459045047395137979434007971044
should=> 2.718281828459045235360287471352662497757

In master/dev:
pi eval=> 3.141592653589793
e eval=> 2.718281828459045

My guess:
text() calls valueOf() when decimals are requested, but valueOf() returns a JavaScript Number.
So, Settings.PRECISION is not respected.
In the demo, the renderer attempts lengthen the decimals to fit Settings.PRECISION by looking at the fraction output, which is inaccurate for pi and e.
toDecimal(40) has the same issue.

**Comment by jiggzson** [comment]
Good catch! Thinking back, I remember this exact problem being the reason I didn't want to go to variable precision decimals. The solution would probably be to carry a higher precision value of pi and e, and calculate and cache it once this number is exceeded.

**Comment by Happypig375** [comment]
I think I suggested using infinite sums internally a while ago.
That can also help, not just pi and e, most functions can benefit from this too.

**Comment by jiggzson** [comment]
moving to #404
