### ISSUE TITLE
integrate and defint drop multiplicative constants outside of parentheses

### ISSUE THREAD

**Issue by colehaus** [jiggzson/nerdamer#396]
At http://nerdamer.com/demo.html, `integrate(x+1)` results in `x^2/2 + x` which is all fine and good. However,`integrate((x+1)/100)` also results `x^2/2 + x`. The same problem occurs with `defint`.

**Comment by Happypig375** [comment]
integrate(x/100+1/100) works though.

**Comment by colehaus** [comment]
Correct, but that behavior was certainly surprising to me.

**Comment by jiggzson** [comment]
@colehaus, thanks for bringing this to my attention. I'll fix this.

**Comment by jiggzson** [comment]
@colehaus, fixed.

**Comment by Happypig375** [comment]
@jiggzson This change is not reflected in the demo though. Should the demo be made to track the master branch?

**Comment by jiggzson** [comment]
@Happypig375, we can go that route too. Have the demo pull directly from master instead of manually updating it. Similar to how's it's done with the dev demo.
