### ISSUE TITLE
nerdamer.convertToLaTeX(exp) and nerdamer(exp) seem to expect defint arguments in different orders

### ISSUE THREAD

**Issue by colehaus** [jiggzson/nerdamer#397]
It seems like `nerdamer.convertToLaTeX('defint(x, x, 0, 1)')` is the only acceptable argument order for `convertToLatex` while `nerdamer('defint(x, 0, 1, x)')` is the only acceptable argument order for `nerdamer`. Notice that the `x` specifying the variable of integration comes before the integration limits in the first case and after in the second case.

**Comment by jiggzson** [comment]
@colehaus, I'll look into this. Thanks.

**Comment by jiggzson** [comment]
Fixed.
