### ISSUE TITLE
Latex generator broken

### ISSUE THREAD

**Issue by jiggzson** [jiggzson/nerdamer#4]
When the expression is requested as latex, often brackets aren't added when there should be. For example when the expression has a non-unit multiplier or power. This issue is strictly related to the latex generator as expression values are correct when the text method is called.

**Comment by jiggzson** [comment]
Latex generator still returning incorrect results in some cases, primarily with rationals.

**Comment by brosnanyuen** [comment]
In renderSubSymbolsLatex

When I comment out this
abs = abs || i > 0;

LaTeX generator produces correct results.

**Comment by jiggzson** [comment]
Fixed in version 0.6.0
