### ISSUE TITLE
Is there any way to create multiple instances of nerdamer?

### ISSUE THREAD

**Issue by Alzy** [jiggzson/nerdamer#403]
I'm trying to create multiple instances of nerdamer so I can evaluate and store expressions in separate objects. This way both objects contain separate histories and variables; ie: if I assign variable **x** as 5 in one instance and **x** as 7 in the other, one will not overwrite the other.

I've tried using 

`var a = new nerdamer`

and

`var a = new nerdamer()`

but neither solution works.

**Comment by Happypig375** [comment]
I think you will have to run the script twice for now; nerdamer is not designed for parallel usage.

like this:
```html
<script src="nerdamer.core.js" />
<script>
var nerdamer2 = nerdamer;
</script>
<script src="nerdamer.core.js" />
```

**Comment by jiggzson** [comment]
@Alzy, the solution provided by @Happypig375  is more than likely your best bet. The other alternative is to keep two objects with know variables and pass those for nerdamer to process. Consider the example below.

```javascript
var vars1 = {x: 5};
var vars2 = {x: 7};
var e = 'x+1';
console.log(nerdamer(e, vars1).toString()); //6
console.log(nerdamer(e, vars2).toString()); //8
```
Would something like that work?
