### ISSUE TITLE
Problem with sum() and vecget()

### ISSUE THREAD

**Issue by OJIEHb** [jiggzson/nerdamer#408]
Hi, I tried to calculate sum of vector part. 
For example:
`const nerdamer = require('nerdamer/all');`

`nerdamer.setVar('x', 'vector(4,1,6,3,1)');`
`let e = nerdamer('sum(vecget(x, i), i, 1, 3)');`
But I receive 

> Error:, is not a valid postfix operator

Is it possible to do this operation via using nerdamer?

**Comment by jiggzson** [comment]
@OJIEHb, thanks for reporting this. Your example should work so this is a bug. I'll look into this. I'm hoping to resume development at the beginning of next month so I'm hoping to get this shortly after that.

**Comment by jiggzson** [comment]
@OJIEHb, this bug seems to be related to the parser. I'm in the process of rewriting the parser and I hope to be done with that soon. I'll be addressing this issue in the process of doing so.

**Comment by OJIEHb** [comment]
@jiggzson , thanks))

**Comment by jiggzson** [comment]
@OJIEHb, fixed.
