### ISSUE TITLE
BigInteger.js needs to be updated

### ISSUE THREAD

**Issue by Yaffle** [jiggzson/nerdamer#409]
`factor(3825123056546413051)` returns incorrect result because the `isPrime` was buggy in the dependency - https://github.com/peterolson/BigInteger.js/pull/151

**Comment by jiggzson** [comment]
@Yaffle, thanks for bringing that to my attention. I'll make sure to update this. Going forward I would like to provide the ability to use your own BigInteger library by overriding the default one. This is one of the items on my TODO list for the next update.

**Comment by Yaffle** [comment]
@jiggzson , peterolson/BigInteger.js is pretty good, popular and provides `isPrime`, also JavaScript has native `BigInt` now ans so js libs become needless.

by the way, I was searching for the integer factorization in js - thanks for the code

**Comment by jiggzson** [comment]
@Yaffle, no problem. I noticed that you have a BigInt library as well. How similar is it (mostly the API) to the one that nerdamer is currently using? I noticed that you have some benchmark tests but I'm having hard time interpreting the layout.

**Comment by Yaffle** [comment]
Yaffle/BigInteger provides only the +,-,*,/,%, conversion from and to string;
while you are using the `isPrime` from peterolson/BigInteger.js, and, may be, something else.
The benchmark values are comparable.

**Comment by jiggzson** [comment]
I see. I'm probably going to have to write my own `isPrime` function in the near future, especially since JavaScript is getting native `BigInt` and maybe even `BigDecimal` support in the near future. I doubt they'll have an `isPrime` function built in. Speaking of which, it doesn't seem to be officially supported at the moment. Do you know anything about that?

**Comment by Yaffle** [comment]
I have "extracted" their implementation and converted to use native `BigInt`:
```
function modPow(base, exponent, modulus, accumulator) {
  accumulator = accumulator == undefined ? 1n : accumulator;
  return exponent == 0n ? accumulator : modPow((base * base) % modulus, exponent / 2n, modulus, exponent % 2n == 1n ? (accumulator * base) % modulus : accumulator);
}

function min(a, b) {
  return a < b ? a : b;
}

function isPrime(n) {
  // isPrime implementation is from https://github.com/peterolson/BigInteger.js
  // https://en.wikipedia.org/wiki/Miller%E2%80%93Rabin_primality_test#Deterministic_variants
  if (n < 2n) {
    throw new RangeError();
  }
  if (n === 2n) {
    return true;
  }
  if (n % 2n === 0n) {
    return false;
  }
  let s = 0;
  let d = n - 1n;
  while (d % 2n === 0n) {
    d /= 2n;
    s += 1;
  }
  function test(x0, n, s) {
    for (let r = 0, x = x0; r <= s - 1; r += 1, x = (x * x) % n) {
      if (x === n - 1n) {
        return false;
      }
    }
    return true;
  }
  for (let a = min(n - 1n, (ilog2(n) + 1n)**2n); a >= 2n; a -= 1n) {
    let x = modPow(a, d, n);
    if (x !== 1n && test(x, n, s)) {
      return false;
    }
  }
  return true;
}
```
Not sure if it is not buggy.

**Comment by jiggzson** [comment]
@Yaffle, thanks!

**Comment by jiggzson** [comment]
@Yaffle, I know it's been a while but I'm just now getting around to checking this out. Again thanks for this port. One question, what is this is `ilog2` function?

**Comment by Yaffle** [comment]
@jiggzson 

```
function ilog2(n) {
  return BigInt(Number(n) < 1 / 0 ? Math.floor(Math.log(Number(n)) / Math.log(2)) : 1023n + ilog2(n >> 1023n));
}
```

**Comment by jiggzson** [comment]
@Yaffle,

Thanks a million!!!
