### ISSUE TITLE
Incorrect Multiplying of -1

### ISSUE THREAD

**Issue by CosmoVibe** [jiggzson/nerdamer#411]
Attempting to multiply -1 to something like x-1 should result in some form of 1-x.

nerdamer('expand(-1*(x-1))').toString()
// "-1+x"

I've tested this with both the imported library as well as on the demo page on your website. In addition, I've also checked with various other forms, such as:
(-1+x)\*(-1)
-2\*(x-1)/2
These all output "x-1" or "-1+x".
It should be noted that amusingly, -2\*(x-1) expands fine, but it's the dividing by 2 that reverts it to a wrong answer.

I also suspect this may be the reason why some of my fractions aren't evaluated or simplified correctly. For instance, the following two fractions are equal:
x/(x-1)
-x/(1-x)
However, the following command gives a wrong result:
nerdamer('x/(x-1)').eq('-x/(1-x)')
// false

**Comment by jiggzson** [comment]
@CosmoVibe. Its sounds like it's an issue with the expand function. I'll look into this. Thanks for reporting.

**Comment by jiggzson** [comment]
Fixed in 0.8.0
