### ISSUE TITLE
Unable to correctly evaluate inverse denominators

### ISSUE THREAD

**Issue by CosmoVibe** [jiggzson/nerdamer#413]
I opened the issue with multiplying with -1, so I'm currently testing these from the 0.8.0 version.

The multiplication with -1 now works, but it still doesn't expand properly when evaluating these in the denominators.

Some examples:

nerdamer('x/(x-1)').eq('-x/(1-x)')
// false, should be true
nerdamer('expand(x/(x-1))').eq('expand(-x/(1-x))')
// false, should be true
nerdamer('expand(1/(x-1))').eq('expand(-1/(1-x))')
// false, should be true
nerdamer('1/(x-1)+1/(1-x)').toString()
// "(-1+x)^(-1)+(-x+1)^(-1)", should be "0"
nerdamer('(x-1)/(1-x)').toString()
// "(-1+x)*(-x+1)^(-1)", should be "-1"

At first I thought the issue was the script recognizing that x cannot be -1 in this case, and simplifying these factors would remove these holes in the domain. However, x/x properly resolves to 1, and while that might account for the last two cases, it doesn't account for the first three.

**Comment by jiggzson** [comment]
@CosmoVibe, the denominator is currently simply evaluated. It's not factored at all. I supposed that a simplify function would help in cases such as this. Ironically I popped in `nerdamer('factor(-x/(1-x))')` expecting it to give the desired output instead it gave `-(-1)*(-1+x)^(-1)*(x)`. This `nerdamer('factor(-x/(1-x))').evaluate();` however does give the desired output. I'll keep this in mind when preparing a simplify function as raised in #210.

**Comment by jiggzson** [comment]
@CosmoVibe, I've started the long overdue simplify function so the issue you raised should currently be fixed. It does require you to call the simplify function. @Happypig375 already provided some suggestions so I'll be working on that list. Feel free to add to it under the discussion at issue #210.
