### ISSUE TITLE
Possible typo in Calculus.js

### ISSUE THREAD

**Issue by yosuke** [jiggzson/nerdamer#417]
Tried to use Javascript code analyser (SonarJS) to detect conditional related errors like in #414.

Most of the result seems OK.

But the following result may be of your interest:
https://sonarcloud.io/project/issues?id=yosuke_nerdamer&open=AWcqrb9Qd6oxh3R41saa&resolved=false&severities=MAJOR&types=BUG

The code
```
else if(g1 === FN && g1 === FN) {
```
May be possible typo of
```
else if(g1 === FN && g2 === FN) {
```
https://github.com/jiggzson/nerdamer/blob/dev/Calculus.js#L629

**Comment by jiggzson** [comment]
@yosuke, thanks. Looks like some long overdue cleanup is needed as well :laughing:
