### ISSUE TITLE
defint(1, 0, 1) returns 0

### ISSUE THREAD

**Issue by titus-pinta** [jiggzson/nerdamer#424]
Hey!
It seems like defint does not integrate constants well.
defint(1, 0, 1) returns a 0 instead of a 1.
I tried some combinations of constants and different intervals of integration and the answer always was 0.

And may I also suggest having a variable of integration parameter in defint?
defint(x^2, x, 0, 1) for instance?

**Comment by jiggzson** [comment]
@titus-pinta, the variable of integration is more than likely undefined. `defint` should either assume `x` or throw. If you do this `defint(1, 0, 1, x)` however, you do get 1. I'll look into this. Thanks for pointing it out.
