### ISSUE TITLE
Problems with convertToLaTeX

### ISSUE THREAD

**Issue by CosmoVibe** [jiggzson/nerdamer#425]
There are a few issues and suggestions I have.

The suggestion is pretty straightforward:

`nerdamer.convertToLaTeX('2*x')`
`"2 \cdot x"`

`nerdamer.convertToLaTeX('2*sqrt(15)')`
`"2 \cdot \sqrt{15}"`

When we have a numerical coefficient in front of certain tokens, can we not have the "\cdot"? That way it looks like 2x instead of 2*x.

The issue is the bigger problem:
`nerdamer.convertToLaTeX('2*(sqrt(3)+sqrt(2))')`
`"2 \cdot"`

It seems that in general, the convertToLaTeX function breaks when there are parentheses involved. However, the demo works fine and I remember at one point this worked and now it doesn't. Perhaps I'm missing something silly?

**Comment by jiggzson** [comment]
>Perhaps I'm missing something silly?

Not at all. I was the one missing something silly. I was forgetting to add brackets back to the output and I never had a test for it so I didn't realize I broke it. Thanks. Good catch! Fixed.

As for the omitting the `\cdot` for coefficients, unfortunately it's not so simple. `convertToLaTeX` is a pretty dumb function and has no concept of coefficients. It's all or nothing. I've added to ability to just override it by passing in a config object. So for example

```javascript
var x = nerdamer.convertToLaTeX('2*(sqrt(3)+sqrt(2))-a*x', {
    cdot: ''
});
console.log(x);
```
now produces `2  \left(sqrt \left(3\right) + sqrt \left(2\right)\right) - a  x`

As you can see, 'a*x' will also produce 'ax' which can be a problem if you're using multi-letter variables but shouldn't be a problem if all your variables are single letters. Hopefully that somewhat helps.
