### ISSUE TITLE
Almost fixed the convertToLaTeX issue, missing backslash

### ISSUE THREAD

**Issue by CosmoVibe** [jiggzson/nerdamer#428]
New issue from related #425:

`nerdamer.convertToLaTeX('sqrt(2)')`
`"\sqrt{2}"`

`nerdamer.convertToLaTeX('(sqrt(2))')`
`"\left(sqrt \left(2\right)\right)"`

There's a missing backslash before the "sqrt" when you add parentheses.

EDIT: It also doesn't process the asterick for multiplication. I think it just missed processing everything inside of the parentheses.

`nerdamer.convertToLaTeX('(2*sqrt(3))')`
`"\left(2 * sqrt \left(3\right)\right)"`

_Originally posted by @CosmoVibe in https://github.com/jiggzson/nerdamer/issue_comments#issuecomment-452577050_

**Comment by jiggzson** [comment]
@CosmoVibe, Fixed.
