### ISSUE TITLE
Add Support for Simplifying Factored Expressions

### ISSUE THREAD

**Issue by mjkaufer** [jiggzson/nerdamer#43]
Hello!
If I enter `nerdamer('(x+4)(x+3)')` or something along those lines, the expression does not get simplified. Could we implement a fix for this?

**Comment by jiggzson** [comment]
Did you want the expression in expanded form? If that's the case use this
```javascript
var x = nerdamer('(x+4)(x+3)', undefined, ['expand']);
console.log(x.toString()); //12+7*x+x^2
```

**Comment by mjkaufer** [comment]
When I try that code, it throws the following error
```
TypeError: Cannot read property 'expand' of undefined
    at libExports (/home/ubuntu/workspace/node_modules/nerdamer/nerdamer.core.js:3653:36)
```

**Comment by jiggzson** [comment]
That's because you're using 0.5.7. You would need the Algebra add-on loaded if that's the case. The latest version from master, 0.6.0, has expand included in the core.

**Comment by mjkaufer** [comment]
Awesome - it works if I expand something simple, such as `(x+5)(x-3)`, but if I throw in `(x+5)(x-3)-x^2`, it just returns `(-3+x)*(5+x)-x^2`

**Comment by jiggzson** [comment]
You're right. I'll upload a fix for this soon.

**Comment by mjkaufer** [comment]
Thanks!

**Comment by jiggzson** [comment]
I pushed a fix for this.

**Comment by mjkaufer** [comment]
Thanks! You're the best

**Comment by jiggzson** [comment]
You're welcome. Thanks.

**Comment by jiggzson** [comment]
Hey mjkaufer. Can this issue be closed?
