### ISSUE TITLE
Testing & Linting

### ISSUE THREAD

**Issue by tecosaur** [jiggzson/nerdamer#437]
Quick diversion from me:

Let me know if you'd be interested in me sending a PR that separates out the tests like so:

![image](https://user-images.githubusercontent.com/20903656/51425270-98f7c400-1bd1-11e9-8eec-a9ed7d7f0e13.png)

https://travis-ci.com/tecosaur/nerdamer

Also let me know if you'd like me to make a PR to add eslint & eslint testing, as that can easily be done and would ensure a consistent style.

**Comment by jiggzson** [comment]
Yes that would very nice. Keep in mind that Calculus fails because you don't have `Calculus.js` loaded. Please make sure they pass since them failing is a very big issue.

Thanks @tecosaur.

**Comment by tecosaur** [comment]
I will make a PR at some point, I swear.

**Comment by jiggzson** [comment]
@tecosaur, no worries. I'm somewhat tied up myself at the moment so I know how it goes.
