### ISSUE TITLE
nerdamer.factor('4677271') returns 4677271, not 2089*2239

### ISSUE THREAD

**Issue by Yaffle** [jiggzson/nerdamer#438]
P.S.
Probably, unrelated to this issue, but https://github.com/peterolson/BigInteger.js was updated again.

**Comment by Happypig375** [comment]
Did you mean `pfactor`?

**Comment by jiggzson** [comment]
@Yaffle. Thanks. I'll take care of this.

**Comment by jiggzson** [comment]
@Yaffle, thanks again for catching this and fixing this. If you're happy with the fix feel free to close this.

**Comment by Yaffle** [comment]
@jiggzson , I have stolen the `ifactor` code from your lib, thank you

**Comment by jiggzson** [comment]
@Yaffle, anytime.
