### ISSUE TITLE
Is there a way to format return values ?

### ISSUE THREAD

**Issue by Saikedo** [jiggzson/nerdamer#439]
I was wondering if nerdamer have any ways to format the way that answers are returned.

One example that comes to mind is this.

If the answer to some calculations like integral is x^(-1), is it possible to request this to be displayed as 1/x ?

**Comment by jiggzson** [comment]
@Saikedo, there's no way to get the output requested at the moment. Generally you get the output put as LaTeX and then feed it to something like Mathquill, MathJax, or KaTeX. Can you give me a case that the formatted text would be preferable to LaTeX?

**Comment by ibreaker14** [comment]
Hi @jiggzson we're currently writing an web application where we'd like to display answers to equations using Guppy (where answers displayed in fractions are preferred). However, Guppy doesn't support latex insertion. If there was a way to display the answers in formatted asciimath (using fractions, of course), that'd be great.

**Comment by jiggzson** [comment]
@ibreaker14, as I mentioned before to @Saikedo, there currently exists no way to accomplish this. The structure of the output is predictable and discussed [here](https://nerdamer.com/digging_deeper.html) so creating this shouldn't be too hard. The `Symbol` class has two methods called `getNum` and `getDenom` which can be called to get the numerator and the denominator for group `N` and `S`. All other groups can be transformed using recursion and using the aforementioned as the base case.
