### ISSUE TITLE
a+b - (a+b) = 2*(a+b)

### ISSUE THREAD

**Issue by JanMP** [jiggzson/nerdamer#44]

**Comment by jiggzson** [comment]
Oh wow. That's a bad one. I'll push a fix soon.

**Comment by JanMP** [comment]
Yeah, that's the type of bug that is so bad, that you never think about testing for it ;-)

**Comment by jiggzson** [comment]
Again thanks for pointing out this bug. I've added a fix for this. Please let me know if this issue can be closed.

**Comment by JanMP** [comment]
It's working fine now. Thanks for the quick fix.
