### ISSUE TITLE
sqrt(2/a) returns 1/(2^(1/2)*a^(1/2))

### ISSUE THREAD

**Issue by selairi** [jiggzson/nerdamer#442]
Hello,
I have just found that if you write sqrt(2/a), nerdamer returns:
\frac{1}{\sqrt{2} \cdot \sqrt{a}}  == 1/(2^(1/2)*a^(1/2))

The right output should be:

\frac{\sqrt{2}} {\sqrt{a}}  == 2^(1/2)/a^(1/2)

It fails if it founds sqrt(number/x).

Thank you for your amazing tool.

**Comment by jiggzson** [comment]
@selairi, looks like this was an oversight on my behalf when fixing #401. It's a fairly simple fix. Let me know if this is a showstopper for you.

**Comment by selairi** [comment]
I have just sent a PR (pull request) fixing this bug. Could you be so kind to merge in main branch?

Thanks for your work.
