### ISSUE TITLE
Cannot solve x to the negative powers, log, and trig functions

### ISSUE THREAD

**Issue by AlienKevin** [jiggzson/nerdamer#443]
Hi, I have looked for an equation solver written in Javascript for a long time but found none that has enough features and reliable at the same time. My needs are relatively simple: A solver that is able to symbolically solve a single equation containing logaritms, trigs, and negative powers. A couple solvers that can do some of those tasks like MathPapa and quickMath are close-sourced so they are not my options. I would really appreciate it if nerdamer solver can support more functions. As of currently, I see that the results outputted are very close to the final answers so I wonder if improvements are easy enough to implement.
For example:
1. Solving equations with trig functions
Input: `solve(2/a*sin(x)+a*b=a*b^2,x)`
Output: `[-a^2*b^2+2*sin(x)+a^2*b]`
Real Answer: `x=arcsin(a^2*b^2/2-a^2*b/2)`

2. Solving equations with log functions
Input: `solve(c^2*log(x)=c/a*b,x)`
Output: `[-a^(-1)*b*c^(-1)+log(x)]`
Real Answer: `x=e^(a^(-1)*b*c^(-1))`

3. Solving equations with negative powers
Input: `solve(1/x=a,x)`
Output: `[]`
Real Answer: `x=1/a`

From the patterns I observed above, for equations containing trig and log functions, I only need to manipulate the current result in three steps to produce the correct answer:
1. Remove the term containing the variable being solved
2. Divide the rest of the terms by the coefficient of the term containing variable
3. Negate and surround the rest of the terms with appropriate inverse functions

As for equations with negative powers, I think you can raise the both sides to 1/(negative power) to yield the correct result.

The above are all my personal speculations and I believe that there are a lot more nuances and difficulties in implementing those functions that I may never thought about. So sorry if I underestimate the difficulty.

**Comment by jiggzson** [comment]
@AlienKevin, thank you for the detailed description of the issue. You're absolutely correct. It's not very hard at all. The next 3 major issues on my agenda are #239, #322, #426. #322 is more than likely going to require a complete rewrite of the solve function and in order to do so I'll need a reasonable amount of tests to make sure I don't break anything which currently works. If you already have a broad range of currently passing test and want to share, I'd greatly appreciate that. If not no worries. Having those tests ready to go would just help to speed things up.

**Comment by AlienKevin** [comment]
I don't have any but I'm happy to help generate some. I don't know how this works. Do you have any guidelines for generating test cases?

**Comment by AlienKevin** [comment]
I also have an issue when trying to override the builtin log() function using the replaceFunction method recommended in #248:

```
// replace builtin natural log function with base 10 logarithm
nerdamer.replaceFunction('log', function (log, core) {
    return function (x) {
        var _ = core.PARSER;
        var Symbol = core.Symbol;
        return _.multiply(log(x.clone()) , new Symbol(Math.LOG10E));
    };
});
```
The output is very bizzare:
\>nerdamer("log(e)").evaluate().text()
"0.43429448190325176"
\>nerdamer("log(10)").evaluate().text()
"0.43429448190325176"

\>nerdamer("log(10^2)").evaluate().text()
"0.8685889638065035"
\>nerdamer("log(e^2)").evaluate().text()
"0.8685889638065035"

\>nerdamer("log(23892.5792)").evaluate().text()
"1.9014554761168245"

Not only are they not equal to the real results of base 10 logarithm, they are not equal to natural log results. I want to find a temporary workaround for #395. Is it possible as of right now?

**Comment by jiggzson** [comment]
@AlienKevin, I'm not too sure what's going on with the above code but if simply change the base then it yields the correct result
```javascript
// replace builtin natural log function with base 10 logarithm
nerdamer.replaceFunction('log', function (log, core) {
    return function (x) {
        var _ = core.PARSER;
        var Symbol = core.Symbol;
        return _.divide(log(x.clone()), log(new Symbol(10)));
    };
});

console.log(nerdamer("log(10)").evaluate().text()); //1
console.log(nerdamer("log(100)").evaluate().text()); //2
```

**Comment by AlienKevin** [comment]
We have essentially the same procedure, you divide `loge(x)` by `loge(10)` which is the same as I multiply `loge(x)` by `log10(e)`. (`log10(e) = 1 / loge(10)`). I tried your approach and it works for the two examples you give but fails again for `log(e)` and `log(e^2)` and other values close to powers of `e` like `log(e^2 + 2)`. I also observed that the new function is executed three times which I don't get why.

**Comment by AlienKevin** [comment]
I looked at the spec, so what types of tests/functions are you looking for now? Do I just come up with some functions and plug them into Wolfram Alpha and document the result? And how can I make edits to the spec file?

**Comment by jiggzson** [comment]
@AlienKevin, I see what you mean. The `replaceFunction` method needs some polishing. I do notice that if you evaluate `x` that this fixes the issue. I need to look into this some more.
```javascript
// replace builtin natural log function with base 10 logarithm
nerdamer.replaceFunction('log', function (log, core) {
    return function (x) {
        var _ = core.PARSER;
        var Symbol = core.Symbol;
        return _.divide(log(core.Utils.evaluate(x)), log(new Symbol(10)));
    };
});
```
But that's probably not what you're looking for. As far as the function being called multiple times, remember that this method is now somewhat recursive since you're reusing the existing `log` function. If you decided to go the strict numerical route 

```javascript
// replace builtin natural log function with base 10 logarithm
nerdamer.replaceFunction('log', function (log, core) {
    return function (x) { 
        var _ = core.PARSER;
        var Symbol = core.Symbol;
        return new Symbol(Math.log10(core.Utils.evaluate(x)));
    };
});
```
then it only gets called once. By doing so you're again relying on the JavaScript builtin `Math` object so you won't benefit from any future improvements to the nerdamer `log` function.
>I looked at the spec, so what types of tests/functions are you looking for now?

I'm not looking for any particular tests. I just know that the current tests don't cover quite a few cases so if you notice any then point it out. If not it's no biggie. You can edit the `spec` file on your branch and then send me back a pull request with the edits.

**Comment by AlienKevin** [comment]
Thank you for your detailed reply. The new `log` replacement does work as expected. However, do you know any ways to set up `ln` (natural log) and `log` (base 10) at the same time? I don't see a way to rename built-in functions. The new `log` replacement calls the builtin `log` (natural log) and then divide it by a constant, but the expression still displays `log` instead of `ln`.

**Comment by jiggzson** [comment]
@AlienKevin, the `ln` issue seems to come up quite a bit. Going forward, I've decided to add the option of using `ln` for `log` and `log` for `log10`.

**Comment by AlienKevin** [comment]
I'm looking forward to the improvement :)

**Comment by jiggzson** [comment]
@AlienKevin, I remember adding these a little while back. Let me know if I missed anything?
