### ISSUE TITLE
nerdamer.simplify not working for functions containing two or more variables

### ISSUE THREAD

**Issue by AlienKevin** [jiggzson/nerdamer#445]
Sample problems:
1. `nerdamer.simplify("4*sqrt(2+a*b)").toString()` => `"sqrt(2+a*b)"` (notice the `4` is dropped)
2. `nerdamer.simplify("4*sin(2+a*b)").toString()`    => `"16*sin(2+a*b)^2"` (the whole expression is squared) This happens for many other functions as well, like `abs`, `cos`, `tan`, `log`.

Interestingly, the above two errors don't happen when the coefficient is a variable, 
like `nerdamer.simplify("c * sqrt(2 + a * b)")` => `"sqrt(2+a*b)^2*c"`. In addition, the above don't happen when the `a*b` (two or more variables) is replaced with something like `0.23*a` (just one variable).

Noticeable Pattern:
The problems happen usually when the expression cannot be expanded or simplified, like `sqrt(2+a*b)` (addition under square root). While other separable expressions with two variables like `"3*sqrt(a*b)"` => `"3*sqrt(a)*sqrt(b)"` works fine.

**Comment by AlienKevin** [comment]
I'm also not so sure about whether I should post these minor errors or not since I feel there may be more urgent/important things for nerdamer developers. Please stop me if you feel this is annoying.

**Comment by Happypig375** [comment]
It's very good that you reported a bug. If you don't report it, it might go unnoticed! You should do this more often instead of feeling bad about it. If there are more important things to be developed, this issue will just stay open, but as a todo item.

**Comment by jiggzson** [comment]
@AlienKevin, as @Happypig375 pointed out, please do report bugs. In the spirit of open source it benefits you as a user of the library to have it as stable as possible, which involves you reporting pretty much every bug you find. My only request is not to open up unnecessary issues by checking first if there's already an existing issue. If there is one then report it under that one. Too many scattered issues make it difficult to come up with a plan of action.

**Comment by AlienKevin** [comment]
Thank you guys for being friendly and welcoming to me. Your works are amazing! I really love Nerdamer.:heart:

**Comment by jiggzson** [comment]
You're welcome @AlienKevin and thank you as well.

**Comment by Kreijstal** [comment]
how can I contribute to this project if I want to fix those bugs?

**Comment by jiggzson** [comment]
@Kreijstal, sorry for the late reply. I'll gladly take a PR with a bug fix. It's typically preferable for PR's to go to`dev` but because of time constraints a PR directly to `master` will do. Just make sure to include a test case for the bug you're fixing and that all tests are passing. If you have any questions I'll be more than happy assist. Just keep in mind that I'll be a little slow to respond for the next 4-5 weeks.

**Comment by jiggzson** [comment]
@AlienKevin, fixed.

**Comment by jiggzson** [comment]
No problem. Let me know if I missed anything? Thanks.
