### ISSUE TITLE
simplify returns NaNs

### ISSUE THREAD

**Issue by Kreijstal** [jiggzson/nerdamer#448]
if you do the following 
nerdamer("simplify(diff((a k+ b k^2)/k^4,x))",{k:"2x+5"})
diff appears to work just fine, but simplify returns a mess somehow

It seems to differentiate OK!
![grafik](https://user-images.githubusercontent.com/2415206/53641471-580eb880-3c2f-11e9-88da-ec2238737648.png)

here is working with the complete simplify
![grafik](https://user-images.githubusercontent.com/2415206/53641403-1978fe00-3c2f-11e9-9212-a828424f1d37.png)

seems this has to do nothing with substitution or differntiation, hopefully (i have not checked if the provided simplifaction is accurate)
![grafik](https://user-images.githubusercontent.com/2415206/53641577-b9cf2280-3c2f-11e9-8d98-8f4643dbc02e.png)

Original code:
```
nerdamer("simplify((2*a+4*(2*x+5)*b)*(2*x+5)^(-4)-8*((2*x+5)*a+(2*x+5)^2*b)*(2*x+5)^(-5))")
```

**Comment by jiggzson** [comment]
@Kreijstal, thanks for reporting. Keep in mind that `simplify` was just started although I suspect this bug to be related to `factor` rather than simplify. Even discounting this bug, `simplify`, at least in the manner you're attempting to use it, still has a long way to go. I'll look into this.

**Comment by jiggzson** [comment]
@Kreijstal, fixed.
