### ISSUE TITLE
bitwise operators?

### ISSUE THREAD

**Issue by starfishmod** [jiggzson/nerdamer#45]
Does this library support bit shifting and bitwise operators?
As this is something I can really use :)

Thanks

**Comment by jiggzson** [comment]
At the moment no. I would like to point out that adding custom functions if quite easy. It's just a matter of extending the Math2 object in the core and then creating a link in the Parser object. For example let's say we wanted to add bitwise and operator functionality and  we'll call the function "bitand"

```javascript
//extend the Math2 object
Math2 = {
    ...
    bitand: function(a, b) {
        return a & b;
    }
}

//create a link in the Parser object. This accepts an array containing the mapped function 
//and the number of arguments it expects. Leave the first blank to use the default name
function Parser() {
    ...
    functions = this.function = {
        ...
        bitand: [ , 2] //2 because it expects 2 arguments
    }
}

//then just call it
nerdamer('bitand(5.7)');
```

Would this solution suffice?

**Comment by starfishmod** [comment]
I guess I'm looking for the ability to do x & y and x<<7 without having to
make them functions :-)

**Comment by jiggzson** [comment]
This would require a little more effort since this would be a modification to the parser itself. I'm hoping to add the ability to add custom operators in future versions but that functionality isn't there at the moment.

**Comment by jiggzson** [comment]
I think this might actually solve your issue. A few minor modifications allows for support for additional operators. In your case this might help. Note that your compound operator limit is two characters. Anything above will have to be a function. Also it's up to you to define the handling of symbolic types.
This goes after loading nerdamer.

```javascript
var core = nerdamer.getCore();
var _ = core.PARSER;
//see core source code for full explanation or parameters. In this case just know
//The first param is the operator character so the parser can recognize it
//The second is the name of the parser function that it maps to
//The third is the order of precedence 
//The third is if it's left associative. And the last is if it's a prefix operator
var Operator = core.Operator;
//create a blank operator so the operator knows it's an operator 
//because the parser only sees one character at a time
_.operators['<'] = new Operator('<', undefined, 1, true, false);
//create the operator you want and we'll name it bitleft. It's up to you. Just make
//sure you call it the same as the function defined below
_.operators['<<'] = new Operator('<', 'bitleft', 1, true, false);
//define the function
_.bitleft = function(a, b) {
    if(!a.isConstant() || !b.isConstant()) {
        //do something with symbolic types
    }
    return a << b;
};
```
