### ISSUE TITLE
Polynomial Fraction form

### ISSUE THREAD

**Issue by FilipeAC** [jiggzson/nerdamer#457]
I'm working with process control problems and we usually represent our functions as a ratio of polynomials. I tried several commands from the documentation such as .evaluate() or .expand() or even try to force the final form of an expression collecting the numerator and denominator and using .divide command, but the results are not always successful.
For example, 3+1/x I'd like (3x+1)/x as the final result, how can I archive this? 
Is there a way to force nerdamer to show the result as a fraction of polynomials?
I'm rendering the results with KaTeX and sometimes the results endup like this:

![Untitled](https://user-images.githubusercontent.com/40698226/55112637-c4a89600-50bb-11e9-92a0-d74da56a38fc.png)

This is the result of .numerator(), .denominator() and .divide() operations from the original equation.

**Comment by jiggzson** [comment]
@FilipeAC, I'll look into this.

**Comment by FilipeAC** [comment]
I discovered the function "rationalize" from Algebrite that does what I previously described. WolframAlpha also has a rationalize command (for instance, rationalize (1+x)/(x+3) +9+1/x). I guess you are working on a simplify command for the future, so having a "rationalize" command might help with that.

**Comment by jiggzson** [comment]
I've added some improvements to the `dev` branch but I haven't really tested them yet. Hopefully they accomplish this. I'll keep trying to improve on it. Feel free to drop some examples here but in text form.

**Comment by jiggzson** [comment]
@FilipeAC, fixed.
