### ISSUE TITLE
Some definite integral functions freeze and never return causing the program to hang.

### ISSUE THREAD

**Issue by Saikedo** [jiggzson/nerdamer#458]
I noticed that some definite integral functions cause nerdamer to get into an infinite loop or something and that causes the program to hang after calling nerdamer. One of those integrals is this 

nerdamer("defint(x^x^2,0,5)").evaluate().toString()

**Comment by Saikedo** [comment]
Note: I also just realized that some other functions besides integral also freeze nerdamer. One example of this behavior is this.
nerdamer("sqrt(1-(3.3333333550520926e-7)^2)").evaluate().text()

**Comment by jiggzson** [comment]
@Saikedo, the second issues seems to be related to pfactor
