### ISSUE TITLE
BuildFunctions that contain error throws crash when error is thrown.

### ISSUE THREAD

**Issue by Saikedo** [jiggzson/nerdamer#459]
I noticed that using BuildFunction can sometimes return functions that contain error throws such as throw new UndefinedError and so on. There is a problem here since these errors will not be defined outside nerdamer, especially if the result from build function is fed into 3rd party library for calculation.

One way to reproduce this bug is as follows.

```
let factorialFunc = nerdamer("factorial(x)").buildFunction();
console.log(factorialFunc(-1));
```

Instead of returning NaN or undefined, this function crashes with the following error message.

```
Uncaught ReferenceError: UndefinedError is not defined
    at factorial (eval at build (nerdamer.core.min.js:9168), <anonymous>:5:2)
    at eval (eval at build (nerdamer.core.min.js:9168), <anonymous>:9:13)
    at <anonymous>:2:13
```

I temporarily fixed the issue on my side by modifying the library and returning NaN instead of throwing an error for factorials but that seems like a bad idea. I think a better way would be to modify the buildFunction pipeline and replace all throw errors with NaN or undefined returns. Any ideas about what can we do here?

**Comment by jiggzson** [comment]
Maybe a try...catch block and then return an error related to build? Something like `BuildError`. I'm just shooting from the hip here. I haven't actually looked into this yet.

**Comment by Saikedo** [comment]
@jiggzson That was my first intuition as well and what I did was to build a wrapper function with a try-catch block that surrounds the functions created by nerdamer`s buildFunction. This is a terrible idea unfortunately because try catch reduces the execution speed by a substantial amount. 

We use the return of BuildFunction in graphical libraries a lot and the execution time of the repeated call of build function`s return gets like 100 times slower if it has to pass through try-catch block.

**Comment by jiggzson** [comment]
Wow. I might be wrong here since I'd expect some overhead however 100 times slower sounds like a lot. More importantly, why is the try-catch block being triggered so often for it to cause that kind of slow down. How often is the code above being executed? I would think that you'd call `buildFunction` once then then keep reusing that function.

**Comment by jiggzson** [comment]
@Saikedo, this was closed automatically on commit. I think it's fixed but let me know if it's not.
