### ISSUE TITLE
(x^(1/2)*x^(1/3))-x^(5/6) should be 0

### ISSUE THREAD

**Issue by JanMP** [jiggzson/nerdamer#46]
the nerdamer output for this is correct, but not helpful

**Comment by jiggzson** [comment]
Agreed. Thanks for pointing that out.

**Comment by JanMP** [comment]
Can you give a quick estimate when this may get resolved?

**Comment by jiggzson** [comment]
I already looked into it and thought I had a solution but it turns out that some tests fail. I'll take another look at it later today.

**Comment by jiggzson** [comment]
Issue fixed. Turns out that I was on the right track after all.The reason my tests were failing was rather silly. Again thanks for you feedback.
