### ISSUE TITLE
Wrong Calc: x^2 + x = x^3 on dev branch

### ISSUE THREAD

**Issue by CosmoVibe** [jiggzson/nerdamer#461]
Disclaimer: This is from the version on the dev branch, not sure if I'm supposed to be making issues here like this, let me know if I should put dev issues elsewhere or not post them at all.
```
nerdamer('x^2 + x').toString()
"x^3"
```
```
nerdamer('x + x^2').toString()
"x+x^2"
```

**Comment by jiggzson** [comment]
No that's fine. Just indicate in the title that it's on the `dev` branch. Good catch. Thanks.

**Comment by jiggzson** [comment]
Fixed.
