### ISSUE TITLE
Problem with pow functons that come from BuildFunction.

### ISSUE THREAD

**Issue by Saikedo** [jiggzson/nerdamer#464]
So it seems like JavaScript always returns NaN when you raise a negative number to decimal power.

So for example Math.pow(-5,1/3) returns NaN when it should have gave us −1.7099759466.

Nerdamer is actually capable of handling this and the operation

`nerdamer("(-5)^(1/3)").evaluate().text()`

does successfully return "-1.7099759466766968".

When I try to build a function however like this,

```
let ourFunc = nerdamer("(x)^(1/3)").buildFunction()
ourFunc(-5)
```

The function call return NaN as expected due to Mat.pow behaviour.

Any ideas how we can address this and fix this behavior so that buildFunction and nerdamer both will have the same value for pow`s ?

**Comment by jiggzson** [comment]
@Saikedo, unfortunately there's no easy solution. Technically this is more of a JavaScript issue. One solution is to override the behavior of `Math.pow`. Since nerdamer doesn't touch native objects outside of polyfills, you'll have to preform this override yourself. You could for instance do something like this:
```javascript
(function() {
    /*global NaN*/
    var toFraction = function( dec ) {
        var done = false;
        //you can adjust the epsilon to a larger number if you don't need very high precision
        var n1 = 0, d1 = 1, n2 = 1, d2 = 0, n = 0, q = dec, epsilon = 1e-13;
        while(!done) {
            n++;
            if( n > 10000 ){
                done = true;
            }
            var a = parseInt(q);
            var num = n1 + a * n2;
            var den = d1 + a * d2;
            var e = (q - a);
            if( e < epsilon) {
                done = true;
            }
            q = 1/e;
            n1 = n2; d1 = d2; n2 = num; d2 = den;
            if(Math.abs(num/den-dec) < epsilon || n > 30) {
                done = true;
            }
        }
        return [num, den];
    };
    var f = Math.pow;
    Math.pow = function(n, p) {
        var test =  f(n, p); //pull the power
        var e = 1e-9;
        //if it's NaN then it might be negative. Try the negative of the abs
        if(isNaN(test) && n < 0) {
            var frac = toFraction(p);
            if(frac[1] % 2 === 0) //return since there aren't any real roots
                return NaN;
            var x = Math.abs(n); //absolute value
            var ans = f(x, p); //get the power of the absolute value
            var t = -f(ans, 1/p); //invert the power so we can test it
            //if the inverse equals the original number then bingo. Return that
            if((t - n) <= e)
                return -ans;
        }
        return test;   
    };
})();

var x = Math.pow(-5, 1/3);
console.log(x);
//-1.7099759466766968
```
In this case we're converting the decimal power to a fraction. This allows us to detect if the denominator in the power is even so we're not taking the square root of a negative number. Of course I recommend testing this a bit since I haven't done so. 

As far as additional overhead, I'm sure there's some but the `toFraction` function converges fairly quickly so it shouldn't be too bad. 

Just be careful with irrationals when using `toFraction`. You'll have to either decide if the error introduced   when converting to a fraction(|error| ~ 2.220446049250313e-14 for Math.PI on my machine) is acceptable for your purposes, or find a way to detect them.

**Comment by Saikedo** [comment]
That is a good solution actually and I have been using something similar but what can we do about the cases such as (-5)^(2/3). Should the answer here be -2.924017738212866 as returned by this approach or 2.92401773821 since -5 is being squared in this case?

**Comment by jiggzson** [comment]
@Saikedo, as I mentioned earlier, this might need some tweaking and testing but you're right. I forgot about those. Since your already have the power in fraction form, then only negate if it's odd. Building on the previous example:
```javascript
(function() {
    /*global NaN*/
    var toFraction = function( dec ) {
        var done = false;
        //you can adjust the epsilon to a larger number if you don't need very high precision
        var n1 = 0, d1 = 1, n2 = 1, d2 = 0, n = 0, q = dec, epsilon = 1e-13;
        while(!done) {
            n++;
            if( n > 10000 ){
                done = true;
            }
            var a = parseInt(q);
            var num = n1 + a * n2;
            var den = d1 + a * d2;
            var e = (q - a);
            if( e < epsilon) {
                done = true;
            }
            q = 1/e;
            n1 = n2; d1 = d2; n2 = num; d2 = den;
            if(Math.abs(num/den-dec) < epsilon || n > 30) {
                done = true;
            }
        }
        return [num, den];
    };
    var f = Math.pow;
    Math.pow = function(n, p) {
        var test =  f(n, p); //pull the power
        var e = 1e-9;
        //if it's NaN then it might be negative. Try the negative of the abs
        if(isNaN(test) && n < 0) {
            var frac = toFraction(p);
            if(frac[1] % 2 === 0) //return since there aren't any real roots
                return NaN;
            var x = Math.abs(n); //absolute value
            var ans = f(x, p); //get the power of the absolute value
            var t = -f(ans, 1/p); //invert the power so we can test it
            //if the inverse equals the original number then bingo. Return that
            if((t - n) <= e)
                //only negate if the numerator is odd
                return (frac[0] % 2 === 0 ? 1 : -1) * ans;
        }
        return test;   
    };
})();
```
Please go ahead and close this issue if this resolves it.

**Comment by Saikedo** [comment]
@jiggzson The solution had a small bug in toFraction function. Are you using this toFraction function in nerdamer? It had an issue with negative numbers. For example toFraction(-1/2) was returning [0,1] instead of something like [-1,2]. Here is my fixed version of that function.

```
var toFraction = function( dec ) {
  let signOfDec = 1;
  if(dec < 0) {
    signOfDec = -1;
    dec = -1*dec;
  }
  var done = false;
  //you can adjust the epsilon to a larger number if you don't need very high precision
  var n1 = 0, d1 = 1, n2 = 1, d2 = 0, n = 0, q = dec, epsilon = 1e-13;
  while(!done) {
    n++;
    if( n > 10000 ){
      done = true;
    }
    var a = parseInt(q);
    var num = n1 + a * n2;
    var den = d1 + a * d2;
    var e = (q - a);
    if( e < epsilon) {
      done = true;
    }
    q = 1/e;
    n1 = n2; d1 = d2; n2 = num; d2 = den;
    if(Math.abs(num/den-dec) < epsilon || n > 30) {
      done = true;
    }
  }
  return [signOfDec * num, den];
};
```
