### ISSUE TITLE
evaluating log(x^even number) uses an inaccurate identity.

### ISSUE THREAD

**Issue by Saikedo** [jiggzson/nerdamer#465]
So we know the identity log(x^2) = 2*log(x) right? That is all fine and accurate up until the point where our x becomes negative unfortunately. For example,

nerdamer("log(x^2)").evaluate().text() returns 2*log(x) but this is not correct for the following reason.

log(x^2) where x = -2 is equal to 0.602
2*log(x) where x = -2 is undefined(or imaginary)

Any easy fixes for this issue?

**Comment by jiggzson** [comment]
Interesting point. One solution I can think of is to return a*log(|x|) for log(x^a) where a is even. This can be achieved by adding that condition after performing the transformation right after [this](https://github.com/jiggzson/nerdamer/blob/1fa6c5cbcd9b1f93f76ab68ba9d0573839801167/nerdamer.core.js#L6520) line. You could add the following bit of code

```javascript
if(even(s))
    arguments[0] = abs(symbol);
```
I don't know if modifying the `arguments` object is good practice however nor do I know if this is a valid solution for all cases. I can't think of any reason why this wouldn't be the case.

**Comment by Saikedo** [comment]
@jiggzson That is a great solution actually. I can`t see any issues with that approach either. Are you planning to add this to the source code?

**Comment by jiggzson** [comment]
Yeah. We can do that. Let's leave this issue open for now until I get a chance to do so.

**Comment by Saikedo** [comment]
@jiggzson `arguments[0] = abs(symbol);` is not working as expected. I am assuming that it just applies absolute value to numeric values? Because when I do abs of symbol x for example, I just get x back.

**Comment by jiggzson** [comment]
@Saikedo, can you give an example? Are you talking about in the context of the `log` function?

**Comment by Saikedo** [comment]
Well, following the example that you provided above,
```
if(even(s))
    arguments[0] = abs(symbol);
```

It seems like the symbol actually contains "x^2" and doing abs("x^2") just returns "x^2" Which I am assuming is intentional.

**Comment by Saikedo** [comment]
@jiggzson Any updates on this issue ?

**Comment by jiggzson** [comment]
@Saikedo, I don't have any updates. This issue is very closely related to #350 IMO. That way we can respond accordingly based on the provided input. The problem with incorporating assumptions is that it requires major rewrite of the core which I can't seem to find time for lately.

**Comment by jiggzson** [comment]
@Saikedo, I've consulted several math packages to see how they handle this issue and they all seem to handle it the same way that we're already doing it. As I've stated before, all values are assumed to be positive. Accounting for all scenarios is extremely difficult if not impossible. I'm going to leave this one as-is.
