### ISSUE TITLE
Bug for sqrt(nx) when n is negative.

### ISSUE THREAD

**Issue by Saikedo** [jiggzson/nerdamer#468]
I just realized that nerdamer encounters numerous bugs when you try to evaluate or build a function for roots such as 

sqrt(nx) where n is negative. I understand that sqrt of a negative number can be undefined but sqrt(nx)  n < 0 is well defined for all x <= 0.

**Comment by jiggzson** [comment]
I don't know if I've mentioned before but as with most symbolic packages, all symbolic values are assumed to be positive. This greatly simplifies our assumptions. Your above example addresses negative values for x but what about negative coefficients? What about a*b*c*x where a, b, c, x can have a combination of negative values? See where I'm going with this? This is where issue #350 would be super helpful. You would be able to state all your assumptions at the beginning.
