### ISSUE TITLE
Error adding an expression

### ISSUE THREAD

**Issue by roy77** [jiggzson/nerdamer#472]
nerdamer("x ^ 3 + 23.80952380952381 * x ^ 2 + 1.4705882352941178e+5 * x")

RangeError: invalid array length
nerdamer.core.js:240:46
    scientificToDecimal file:///D:/XAMPP/App/xampp/htdocs/nerdamer-0.8.4/nerdamer.core.js:240
    e file:///D:/XAMPP/App/xampp/htdocs/nerdamer-0.8.4/nerdamer.core.js:4897
    RegExpGetFunctionalReplacement self-hosted:4956
    RegExpGlobalReplaceOptFunc self-hosted:5054
    Symbol.replace self-hosted:4842
    replace self-hosted:5731
    prepare_expression file:///D:/XAMPP/App/xampp/htdocs/nerdamer-0.8.4/nerdamer.core.js:4896
    parse file:///D:/XAMPP/App/xampp/htdocs/nerdamer-0.8.4/nerdamer.core.js:5474
    e file:///D:/XAMPP/App/xampp/htdocs/nerdamer-0.8.4/nerdamer.core.js:9285
    block file:///D:/XAMPP/App/xampp/htdocs/nerdamer-0.8.4/nerdamer.core.js:786
    libExports file:///D:/XAMPP/App/xampp/htdocs/nerdamer-0.8.4/nerdamer.core.js:9284

**Comment by jiggzson** [comment]
Thanks for bringing this to my attention. I'll look into this.
