### ISSUE TITLE
latex output with decimal

### ISSUE THREAD

**Issue by roy77** [jiggzson/nerdamer#473]
The text function accept a parameter "decimal"  to get back numers as decimals. Same should be possible in latex function.

Also a parameter to define the shown digits would be nice.

**Comment by jiggzson** [comment]
@roy77, sounds good.

**Comment by jiggzson** [comment]
This was erroneously auto-closed. Not completed since a parameter showing digits is still not fixed.

**Comment by jiggzson** [comment]
@roy77, fixed on `dev`
