### ISSUE TITLE
solveFor failing for long expressions

### ISSUE THREAD

**Issue by FilipeAC** [jiggzson/nerdamer#474]
I noticed a while ago that trying to solve some expressions using solveFor return the following error:

**Uncaught RangeError: Maximum call stack size exceeded
    at toString (nerdamer.core.js:1802)
    at text (nerdamer.core.js:1898)
    at Symbol.collectSymbols (nerdamer.core.js:3615)
    at text (nerdamer.core.js:1930)
    at nerdamer.core.js:1940
    at Symbol.collectSymbols (nerdamer.core.js:3615)
    at text (nerdamer.core.js:1933)
    at Symbol.collectSymbols (nerdamer.core.js:3615)
    at text (nerdamer.core.js:1930)
    at Parser.add (nerdamer.core.js:7145)**

I imagined that the expression was too complex to be numerically solved, like the following one:
(-K^2/(-K+24)-448/(-K+24)+24*K/(-K+24))^(-1)*(-24-3136*(-K+24)^(-1)-7*(-K+24)^(-1)*K^2+168*(-K+24)^(-1)*K+K)=0

but when I simplify to this one

8*(K^2 - 27K + 464)/(K^2 -24K + 448) = 0

Nerdamer stops showing the error. It seems that the form of the expression is crashing solveFor function. I used the evaluate function to test the long expression for different values of K and it worked fine, so it seems to be a solveFor problem.

**Comment by jiggzson** [comment]
@FilipeAC, looking into this.

**Comment by jiggzson** [comment]
The ironic part is that this error wasn't related to `solveFor` at all but was a super old bug deep in the core. Your issue does illustrate the need for having a simplify function but that's a separate issue.

**Comment by FilipeAC** [comment]
Yeah, I confess I do miss a simplify function for Nerdamer. My workaround here was the Algebrite's simplify function to make expressions smaller. I'm glad that you identified the problem!

**Comment by jiggzson** [comment]
Sounds good. Currently working on wacking some bugs, simplify, and beefing up solve a bit.
