### ISSUE TITLE
Weird bug when using negative numbers and pi in Sin function.

### ISSUE THREAD

**Issue by Saikedo** [jiggzson/nerdamer#476]
I just noticed that equations such as sin(-2*pi/180) produce a bug where the negative sign is ignored. The strange thing is that if I use the value of pi instead of pi, then the equation returns the expected answer. Any ideas what might be going wrong here?

**Comment by Saikedo** [comment]
Ok, I think I zeroed in on a possible solution. Take a look at this code. 

`sin: function (symbol) {
                if (Settings.PARSE2NUMBER) {
                    if (symbol.isConstant()){
                        return new Symbol(Math.sin(symbol.valueOf()));
                    }
                    if (symbol.isImaginary())
                        return complex.evaluate(symbol, 'sin');
                }

                if (symbol.equals(0))
                    return new Symbol(0);

                var retval,
                        c = false,
                        q = getQuadrant(symbol.multiplier.toDecimal()),
                        sign = symbol.multiplier.sign(),
                        m = symbol.multiplier.abs();
                symbol.multiplier = m;
                if (symbol.equals('pi'))
                    retval = new Symbol(0);
                else if (symbol.isPi() && symbol.isLinear()) {
                    //return for 0 for multiples of pi
                    if (isInt(m)) {
                        retval = new Symbol(0);
                    } else {
                        var n = m.num, d = m.den;
                        if (d == 2) {
                            retval = new Symbol(1);
                            c = true;
                        } else if (d == 3) {
                            retval = _.parse('sqrt(3)/2');
                            c = true
                        } else if (d == 4) {
                            retval = _.parse('1/sqrt(2)');
                            c = true;
                        } else if (d == 6) {
                            retval = _.parse('1/2');
                            c = true;
                        } else
                            retval = _.symfunction('sin', [symbol]);
                    }
                }

                if (!retval)
                    retval = _.multiply(new Symbol(sign), _.symfunction('sin', [symbol]));

                if (c && (q === 3 || q === 4))
                    retval.negate();

                return retval;
            }`

Shouldn`t we use the sign of the symbol at this block 

`else
                            retval = _.symfunction('sin', [symbol]);
                    }`

so that instead of `retval = _.symfunction('sin', [symbol]);` it should be

` retval = _.multiply(new Symbol(sign), _.symfunction('sin', [symbol]));`

**Comment by jiggzson** [comment]
You sir are correct. Thanks for catching that.
