### ISSUE TITLE
csc returns a wrong sign for negative numbers

### ISSUE THREAD

**Issue by Saikedo** [jiggzson/nerdamer#477]
It seems like a negative vale of the csc is ignored and we have a bug where csc(x) = csc(-x) for all x.

By looking at the code I noticed that we apply absolute value on the symbol but I am not sure why. Any idea why?

**Comment by Saikedo** [comment]
@jiggzson Nevermind. Already fixed the issue and will push soon.

**Comment by jiggzson** [comment]
Fixed with #499
