### ISSUE TITLE
Solvable linear equation but getting "Division by zero not allowed!" error

### ISSUE THREAD

**Issue by matt-mert** [jiggzson/nerdamer#478]
I am trying to solve this equation;
2*a+5*b=9
2*a+3*c=7
3*c-5*b=2
a=b+c
But I am getting "Division by zero not allowed!" error.
However, it can solve this below example equation at nerdamer quick start page with no errors.

```
var sol = nerdamer.solveEquations(['x+y=1', '2*x=6', '4*z+y=6']);
console.log(sol);
//[ [ 'x', 3 ], [ 'y', -2 ], [ 'z', 2 ] ]
```

Here is my code:

```
var sol = nerdamer.solveEquations(['2+5*b=3*c', '7-2*a=3*c', '9-2*a=5*b']);
console.log(sol);
//should give [ [ 'a', 2 ], [ 'b', 1 ], [ 'c', 1 ] ] but instead gives error.
```

And the picture of the error:

https://i.ibb.co/J5jbzsx/issue.jpg

**Comment by jiggzson** [comment]
@matt-mert, did you resolve your issue?

**Comment by jiggzson** [comment]
@matt-mert, I get `matrix([0,5,-3],[-2,0,-3],[-2,-5,0])` for the coefficient matrix which has a determinant of 0. I don't think your system has a distinct solution. I do think the error message can use some work.

**Comment by Happypig375** [comment]
For systems of equations that have infinite solutions, it may be useful to output parametric equations, e.g. in terms of `t`.
