### ISSUE TITLE
Sortorder of polynomials on Safari

### ISSUE THREAD

**Issue by JanMP** [jiggzson/nerdamer#48]
The sort order of polynomials is backwards in Safari.

In Node and Chrome: nerdamer("x^2+2x+1").toTeX() = x^{2}+2 \cdot x+1
In Safari it's 1+2 \cdot x+x^{2}

see also https://www.reddit.com/r/javascript/comments/4q4i9d/arraysortcallback_arguments_all_screwed_in_safari/

**Comment by jiggzson** [comment]
Interesting. I'll look into this. Thanks.

**Comment by jiggzson** [comment]
Besides the order of output for LaTeX does this cause any other issues? I'm not exactly in love with the idea of browser/environment detection inside of nerdamer but maybe a parameter can be passed into the the toTeX function to request polynomials in reverse.

**Comment by JanMP** [comment]
No, it just bothers me in the LaTeX output. And It's actually not reverse order. That just seems to be the case for 2nd degree polynomials (most of the time, i just noticed there are exceptions). On higher degree polynomials it just seems pretty much random order.

**Comment by JanMP** [comment]
any news on this one?

**Comment by jiggzson** [comment]
I briefly looked into it but I was caught up with something else. I'll try
to get to it shortly.

**Comment by jiggzson** [comment]
One solution I'm thinking of is to pass in a reverse parameter. Something like,
```javascript
var reverse = true;
nerdamer.toTeX(undefined, reverse);
```
How does that sound?

**Comment by JanMP** [comment]
That sounds really, really inconvenient. That is one parameter that has to be set once during runtime and then doesn’t change. It’s browser dependent, and the browser doesn’t change in between calls to toTeX.

I know you don’t want to check for the browser. I am just looking into that and yeah: it’s a frigging mess, and I’d rather prefer If you do it instead of me ;-P

Seriously though, the sort order should just be correct out of the box without the user having to check if it may or may not have to be corrected.

But I got an idea (and it’s so stupid simple and obvious, I don’t know why neither of us came up with that in the first place lol): don’t check what browser nerdamer is running on. Instead test if the sorting is done wrong.

**Comment by jiggzson** [comment]
That's actually kind of what it already does. The ordering happens with this particular piece of code
```javascript
var collected = symbol.collectSymbols().sort(
    group === CP || previousGroup === CP ? 
     function(a, b) { return a.group < b.group;}:
     function(a, b) { return a.power < b.power;}
)
```
Consider this example x^2+2*x+1. The group is as follows [[x^2+2*x]+1]
To make the generating of the LaTeX somewhat simple I step through the expression and generate "x^2"+"2*x" -> "x^2+2*x" and later "x^2 +2* x" + "1" -> "x^2+2*x+1".

It seems that the checking of the group and power needs to be reversed for some reason in Safari. I haven't really had a chance to fully investigate this issue since I develop on Ubuntu and I need to install a copy of Safari. I'll investigate this some more.

**Comment by JanMP** [comment]
switching it around like this (that’s what you meant, right?) breaks it on chrome (on first sight that now looks like the messed up sorting on safari) but doesn’t fix it on safari…

var collected = symbol.collectSymbols().sort(
                        group === CP || previousGroup === CP ?
                        function(a, b) { return a.power < b.power;}:
                        function(a, b) { return a.group < b.group;}
                    ),

**Comment by jiggzson** [comment]
No what I meant to say was that in the current nerdamer.core.js file (line: 3781) in the master branch to switch this:
```javascript
                  var collected = symbol.collectSymbols().sort(
                        group === CP || previousGroup === CP ? 
                        function(a, b) { return a.group < b.group;}:
                        function(a, b) { return a.power < b.power;}
                    ),
```
with this:
```javascript
                    var collected = symbol.collectSymbols().sort(
                        group === CP || previousGroup === CP ? 
                        function(a, b) { return b.group - a.group;}:
                        function(a, b) { 
                            var x = isSymbol(a.power) ? -1 : a.power;
                            var y = isSymbol(b.power) ? -1 : b.power;
                            return y-x;
                        }
                    ),
```
I can't verify if this works at the moment but I have a feeling that that should be the source of the bug.

**Comment by JanMP** [comment]
I just checked it out and it's working ;-)

**Comment by jiggzson** [comment]
Awesome. The fix for this was merged to master.
