### ISSUE TITLE
Calculus module initialization issue

### ISSUE THREAD

**Issue by yuliapi** [jiggzson/nerdamer#493]
Hi, 
I noticed, that Calculus module initialization differs from Algebra.
This is from Calculus: 
`if((typeof module) !== 'undefined' && typeof nerdamer === 'undefined') {
    nerdamer = require('./nerdamer.core.js');
    require('./Algebra.js');
}
`
Here is from Algebra module:
`if((typeof module) !== 'undefined') {
    var nerdamer = require('./nerdamer.core.js');
    require('./Calculus.js');
}
`

In Calculus module the "var" is missing before nerdamer. This causing issues when nerdamer is running within node.js environment in tests.
I've created a PR to address this if it there is not hidden logic behind that:
https://github.com/jiggzson/nerdamer/pull/492

**Comment by jiggzson** [comment]
@yuliapi,

Thanks. There's no special logic behind it. Just a regular good ol' fashioned oops :laughing:
