### ISSUE TITLE
What is happening with branches? :) 

### ISSUE THREAD

**Issue by Saikedo** [jiggzson/nerdamer#494]
Hi, I am planning to make a push to Nerdamer in the next few days that will contain couple of fixes and I was wondering what is happening with the branches.

I see that master was updated recently but the dev branch is 5 commits ahead and 8 commits behind the master. Is it possible to synchronize these branches? If there are no plans for doing that, should I pull from the master or dev branch before I push?

Thank you.

**Comment by jiggzson** [comment]
@Saikedo, I'll do some cleaning in the next couple of days or so, hopefully this weekend the latest.  I don't even remember where I left off :rofl:. I know I just closed a PR which seemed somewhat important but I'll merge `dev` to `master`. Will that timeframe work?

**Comment by Saikedo** [comment]
I am all too familiar with the notion of forgetting what is contained in what branch :) Yeah, timeframe is perfect. Thank you very much.

**Comment by jiggzson** [comment]
@Saikedo, just target `master` and I'll sort it all out later. I'm in the process of converting solve to big numbers so that's partly the blame.

**Comment by Saikedo** [comment]
Awesome. Do we have any eta on when the big numbers will be ready?

**Comment by jiggzson** [comment]
I'm hoping to get back to big numbers after the holidays but I'm unsure as to when this should be done at the moment.

**Comment by Saikedo** [comment]
Ok, @jiggzson I made a pull request in the meantime with couple of fixes. Please take a look and accept it or let me know what needs to be changed whenever you have the time.

**Comment by Saikedo** [comment]
@jiggzson By the way, I think it is super easy to pull the dev into master as of now so I would highly suggest handling that as soon as possible since dev does contain fixes that master does not.

I tried pulling master into dev and then merging dev into master and had no issues at all.
