### ISSUE TITLE
93222357 is OK,  93222358 is broken  why?

### ISSUE THREAD

**Issue by blueken** [jiggzson/nerdamer#495]
```
var solve1 = nerdamer('(93222357/131836323)*(-2*y+549964829/38888386)=10').solveFor('y')

console.log('===>', solve1[0].toString());
```

output:   ===> -183321609/2416844668563868 .  GREAT!

```
var solve1 = nerdamer('(93222358/131836323)*(-2*y+549964829/38888386)=10').solveFor('y')
console.log('===>', solve1[0].toString());
```

output: 
`nerdamer.core.js:227 Uncaught E {name: "InvalidVariableNameError", message: " is not a valid variable name", stack: "InvalidVariableNameError:  is not a valid variable…rs~main.9b6ee5566f68ff5d4346.bundle.js:117748:26)"}`

WHY?

**Comment by blueken** [comment]
Maybe, It has no solve result when the number changed to 93222358

**Comment by jiggzson** [comment]
@blueken, I'll take a look at this anyway. I wonder if it's somewhat related to #491.  I'm moving this to #322.

**Comment by blueken** [comment]
> @blueken, I'll take a look at this anyway. I wonder if it's somewhat related to #491. I'm moving this to #322.

ok， thank you @jiggzson

**Comment by jiggzson** [comment]
Fix as of ... (not sure when). But tested in 1.1.10
