### ISSUE TITLE
solve equations to find a tangent line to 2 circle return wrong answers

### ISSUE THREAD

**Issue by hyukiiii** [jiggzson/nerdamer#498]
hi,  the codes is as follows.

let eq1 ="x^2+y^2=1",
eq2 ="x+y=1";
nerdamer.solveEquations([eq1, eq2]);

And you will find it comes out as  "Division by zero not allowed!"
is this kind equations will never be solved in nerdamer?

**Comment by hyukiiii** [comment]
let eq1 = "x^2+y^2=1",
eq2 = "135*x+226*y=-3.075";
let res = nerdamer.solveEquations([eq1,eq2]);

solving these equations comes out only one answer, but if you image them as 1 circle and 1 line, there should have 2 or 1 or 0 answers

**Comment by jiggzson** [comment]
> is this kind equations will never be solved in nerdamer?

I wouldn't say never. I'm always trying to make the library better so this is just another case to consider. 


> solving these equations comes out only one answer, but if you image them as 1 circle and 1 line, there should have 2 or 1 or 0 answers

I don't know of an easy way to tell how many solutions a set of nonlinear equations has, which is why as stated in the documentation, the function returns the first solution that satisfies all constraints.  In fact it's just Newton's method under the hood. There might very well be a very good method for determining this. I'm open to suggestions on how to test how solutions to expect. If you know of any literature, by all means, do share.

**Comment by Happypig375** [comment]
>I don't know of an easy way to tell how many solutions a set of nonlinear equations has

Can't substitution be done? http://www.mrferrante.com/algebra2/final_review/chapter3/3.6.1.html

**Comment by jiggzson** [comment]
@Happypig375, my first approach was just that but it got unwieldy quickly and it was somewhat slow. The truth is that the current implementation was somewhat slow as well but I was able to make is usable by converting to a JS function. Maybe I can take that approach.

> 2 nonlinear equations with two variables: https://www.physicsforums.com/threads/number-of-solutions-of-a-nonlinear-system.971862/#post-6178851

This one seems like it might just work. I'll give it a go when I get some time.

**Comment by drawtheliner** [comment]
I see above a Fix has been made, but I'm not sure if the newest version is already supposed to have it. I just tested this in the demo (1.1.10) and it gives only one result.

![image](https://user-images.githubusercontent.com/24493271/117355121-0ff01e00-aeaa-11eb-891a-8caa8337bb4c.png)

How to proceed if I want to get both results (10 and -10 as well)? Thanks!

**Comment by jiggzson** [comment]
@drawtheliner, 

`solveEquations` is generally used with systems of equations. With a system of non-linear equations, the answers returned will be the first set of solutions that satisfies the system. If you want to solve for all the answers as in your case then use [solve](https://nerdamer.com/functions/solve.html).

**Comment by drawtheliner** [comment]
@jiggzson thanks for the reply.

I am actually trying to find the intersection between a line and a sphere, like so:
![image](https://user-images.githubusercontent.com/24493271/117371117-45ebcd00-aebf-11eb-9adf-f9177a302737.png)

Is there anyway to get the 10 and the -10 in this case?

**Comment by jiggzson** [comment]
@drawtheliner,

Correct me if I'm wrong but it appears you already know both x and z. Why not just substitute and solve. Something like this:

```javascript
var point = {x: 0, z: 0};
var solutions = nerdamer('x*x+y*y+z*z=100', point).solveFor('y');
console.log(solutions.toString()); // 10,-10
```
You can repeat this for any other known points on your line. Am I understanding your problem correctly?

**Comment by jiggzson** [comment]
@drawtheliner,

I see. You're trying to extend this solution to three dimensions since the current fix for this issue is limited to two dimensions. 

>Do you think it would be possible to achieve that using your library? If not, any alternative you'd suggest?

Unfortunately not at the moment but I can look into this. It would be nice to be able to solve these types of systems in a more generic way but I haven't had much luck finding publications on this topic. I don't know of any library which does this at the moment but if you find any, please do share.

**Comment by drawtheliner** [comment]
Cool. Yeah, every now and again I look around for this and usually can't find much about it. I wonder if this is one of those problems that don't have a general solution (I'm not a mathematician, so I can only guess).

I sometimes find websites/tools that do 3d plotting of functions, like the one linked below. Maybe you can find some resources within the libraries they use?

However I'm not sure what is their approach... I often feel these tools are a bit sluggish, which makes me think they could be simply doing it brute force (going through all points in 3d space, checking against the equations, and drawing). That wouldn't be performant enough for my purposes (real-time rendering, collision-testing etc. - I don't need it to be lighting-fast, but it can't be sluggish either).

https://www.geogebra.org/3d

![image](https://user-images.githubusercontent.com/24493271/117449205-9b63c080-af37-11eb-804b-68cb9f6a3fc2.png)
