### ISSUE TITLE
nerdamer("(x^2+2*x+1)/(x+1)") should be (x+1)

### ISSUE THREAD

**Issue by JanMP** [jiggzson/nerdamer#50]
hmm, this might be related to #40?

**Comment by jiggzson** [comment]
Presently this is achieved using the divide function in the Algebra module. 
```javascript
var x = nerdamer('divide((x^2+2*x+1),(x+1)');
```

**Comment by JanMP** [comment]
I haven't actually got to the case where I need this division, yet. I just stumbled on this while trying random bits of math to test something else. I am working on a web app that generates math practice exercises and will eventually get to this problem, but then I probably rather work my way back from the result and use expand instead of divide. But It's good to know how to do this ;-)

Changing the result with remainder from "2+x, -1" to "x+2-(x+1)^-1" is a really good Idea. I use nerdamer to compare the answers to the solutions of the problems, and the notation with the "," would have nerdamer throw an error at me when I feed it back into it.

**Comment by jiggzson** [comment]
Sounds good. I'll rename the current divide function to something like **div** and have that one return an array and have **divide** return a Symbol object. I need at a function to return quotient & remainder since this is needed for certain algorithms.

**Comment by jiggzson** [comment]
Done.
