### ISSUE TITLE
Bug with certain random calulations involving powers and multiplication

### ISSUE THREAD

**Issue by Saikedo** [jiggzson/nerdamer#500]
The following expressios returns 0, which is false

`nerdamer("5*(1.05)^(33.5)").evaluate().text()`

But when I do

`nerdamer("5*(1.05)^(33)").evaluate().text()`

It works as expected.

Also doing

`nerdamer("(1.05)^(33.5)").evaluate().text()` works as expected. We might have a parser bug here ?

**Comment by jiggzson** [comment]
@Saikedo, I'll work on this. Let me know if you find anything else.

**Comment by jiggzson** [comment]
@Saikedo, this issue has a temporary fix but some tests are failing due to rounding errors. No idea if the new values are more accurate. I'll keep working on this when I get some more time. I also committed to the wrong branch. I accidentally pushed to master.

**Comment by jiggzson** [comment]
@Saikedo, Fixed. This one was somewhat related to #497. I've added an explanation there.

**Comment by jiggzson** [comment]
`nerdamer("20^(-330.4)*21^330.4").evaluate().text();` still gives `0`
