### ISSUE TITLE
Mod (%) operator

### ISSUE THREAD

**Issue by MuhammadAbdelsalam** [jiggzson/nerdamer#504]
Mod has precedence issue. It appeared in case using it with with another operator on same level of precedence.
EX: 3*3%9
Expected result: 0
Actual result: 9

Explanation: if equation has more than one operator with same precedence left proceed first.
                    Expected result based on 3*3 = 9, 9%9 = 0 so result = 0
                    Actual result based on 3%9 = 3, 3*3 = 9 so result = 9

Root cause: Mod operator override with percentage operator but not override leftAssoc property when override action. You should add new property overloadLeftAssoc to replace leftAssoc in case action is replace with overloadAction.

**Comment by jiggzson** [comment]
@MuhammadAbdelsalam, awesome catch! I have no idea why the original precedence was used but simply lowering it seems to fixed it. Not only that but 3 test were actually wrong. Check it out and let me know if it's correct. Thanks.

**Comment by MuhammadAbdelsalam** [comment]
@jiggzson, I handled the the issue and opened pull request, but the pull request failed 3 test cases, I expect we should open the pull request on master not dev branch because i tried the test case and worked correctly on local.

**Comment by jiggzson** [comment]
@MuhammadAbdelsalam, can you explain why the precedence has to be 4? When changing it back to 4, 10%4*8 not evaluates to 16 which is incorrect. The correct value is 10. The tests on `dev` are actually the correct values. I'm really curious which expressions give the incorrect output with the precedence being 3.

**Comment by MuhammadAbdelsalam** [comment]
I can't change precedence  to be 3 because *   /   % MOD are same precedence  
if we supposed this equation --> 10%4*8 
solution should be 10%4 = 2  ---> 2*8 =16 so 16 is correct, based on % and * are same precedence, we should evaluate the equation from left to right.

**Comment by jiggzson** [comment]
Interesting. I stand corrected. It appears the original values were indeed correct. When consulted Wolfram Alpha ([https://www.wolframalpha.com/input/?i=10%254*8](https://www.wolframalpha.com/input/?i=10%254*8), I got 10. My mistake 😆. Can you update the tests to reflect the correct values and update your PR? I'll go ahead and close it as soon as that's done. Thanks.

**Comment by MuhammadAbdelsalam** [comment]
Hi jiggzosn, I can't understand why test cases failed? test cases are valid and i tried in my local and it's true
var x = nerdamer('10%4*8');
console.log(x.toString());

**Comment by jiggzson** [comment]
@MuhammadAbdelsalam, thank you for your contribution.
