### ISSUE TITLE
 no-count limit

### ISSUE THREAD

**Issue by coder-racer** [jiggzson/nerdamer#507]
What? 
![image](https://user-images.githubusercontent.com/33505785/70178431-7ba6e800-1706-11ea-8c07-7c1861906b56.png)
![image](https://user-images.githubusercontent.com/33505785/70178472-8a8d9a80-1706-11ea-9236-8510f0a3202a.png)

**Comment by jiggzson** [comment]
Check your version. You need to download a version that supports limits. Both the demo and the dev version give the correct output.

https://nerdamer.com/demo.html?eq=limit(x^x-1,x,0)
https://nerdamer.com/demo.html?eq=limit((x^2+2x-3-1)/(x^6+4),x,0)
