### ISSUE TITLE
roots() function gives invalid array length error

### ISSUE THREAD

**Issue by cdmiller** [jiggzson/nerdamer#510]
nerdamer( 'roots((-11/10+x)^2+1)' ) reports a range error, yet this seems like a perfectly good polynomial.

I'm getting a range error for this particular function, not others that I have tried.  Have verified that https://nerdamer.com/demo.html shows the same error.

Call stack is:
Algebra.js:1539 Uncaught RangeError: Invalid array length
    at rpSolve (Algebra.js:1539)
    at calcroots (Algebra.js:1742)
    at get_roots (Algebra.js:949)
    at Object.proots (Algebra.js:998)
    at roots (Algebra.js:1770)
    at Parser.callfunction (nerdamer.core.js:5341)
    at Parser.parseRPN (nerdamer.core.js:5970)
    at Parser.parse (nerdamer.core.js:6150)
    at nerdamer.core.js:10432
    at block (nerdamer.core.js:842)

My goal is to plot roots of various functions, I just happened to try y = "(-h+x)^2*a+k", with {a: 1, h: -10, k: 1}

**Comment by jiggzson** [comment]
@cdmiller, the polynomial does not have real roots. If you use solve it should return all the roots. Please do verify since I'm on mobile so I can't confirm any of this.

**Comment by cdmiller** [comment]
OK thanks, switching to solve did the trick. I was alarmed by the RangeError with the roots() expression, and will let you decide that is the proper result or not.

**Comment by jiggzson** [comment]
@cdmiller, no problem. Glad that helped. `roots` is one of those functions I've been meaning to remove since I started it but never finished it. I'll remove it with the next update. Sorry for the confusion.
