### ISSUE TITLE
evaluate x^1/n issue for x<0, n:3

### ISSUE THREAD

**Issue by cdmiller** [jiggzson/nerdamer#512]
I am getting some incorrect results for certain formulas x to the negative power with x < 0, with Nerdamer in javascript, trying to plot 'x^(1/n)' [a.k.a nthroot(x,n) ]

Example:

nerdamer( "(x)^(1/n)" ).evaluate( {x:-0.5,n:3}, "numer").text();
> "-0.6299605249474367"

nerdamer( "(-0.5)^(1/3)" ).evaluate( {}, "numer").text();
> "-0.7937005259840998"

The first result is incorrect.  Using the Demo to enter 
x:-05
n:3
(x)^(1/n)  [decimal,evaluate]
gives:
−0.7937005259840998413580726515934164868179186760119618918159347873550326102418454

**Comment by Saikedo** [comment]
Interesting. I never use .evaluate() with parameters so I am not sure what is happening there but it seems like you can do the following and it works just fine.

`nerdamer( "(x)^(1/n)", {x:-0.5,n:3}).evaluate().text();`

**Comment by cdmiller** [comment]
Those particular values give a correct result, but unfortunately other negative values of x have two problems (1) throwing an exception like "Uncaught Error: Invalid integer: NaN", and hanging in almost endless loops, where when I pause the Javascript debugger it is pause in the debugger then it is in Nerdamer's PrimeFactors() called by pow(), calculating prime factors to some huge integer.

I am trying to plot various simply functions over a plot of data points. Here are some specific tests:

nerdamer( "(x)^(1/n)" ).evaluate( {x:-0.5,n:3}, "numer").text();
"-0.6299605249474367" // wrong, should be -0.793..

nerdamer( "(x)^(1/n)", {x:-0.5,n:3}, "numer").text()
"-0.6299605249474367"	// wrong, should be -0.793..

nerdamer( "(x)^(1/n)", {x:-0.5,n:3}).evaluate().text()
"-0.7937005259840998"'  // right

nerdamer("x^n^(-1)",{x: -24.160787001838543, n: 1.3})
nerdamer.core.js:10842 Uncaught Error: Invalid integer: NaN
    at parseStringValue (nerdamer.core.js:10842)
    at parseValue (nerdamer.core.js:10842)
    at new Integer (nerdamer.core.js:10842)
    at Function../node_modules/nerdamer/nerdamer.core.js.Frac.quick (nerdamer.core.js:2541)
    at Function../node_modules/nerdamer/nerdamer.core.js.Frac.simple (nerdamer.core.js:2553)
    at new Frac (nerdamer.core.js:2518)
    at testPow (nerdamer.core.js:7498)
    at Parser.pow (nerdamer.core.js:8567)
    at Parser.pow (nerdamer.core.js:8490)
    at Parser.parseRPN (nerdamer.core.js:5959)

nerdamer("x^n^(-1)",{x: -24.160787001838543, n: 1.3},"numer").text()
"-134.23420495293774" // ??? not sure

I'm not clear on the difference between these forms of evaluating function, but it seems all have problems.  

MathJS.nthRoot(a,n) just refuses to evaluate these, giving "Error: Root must be odd when a is negative."

**Comment by jiggzson** [comment]
> I'm not clear on the difference between these forms of evaluating function, but it seems all have problems.

@cdmiller, agreed. The results should be consistent. The main difference between these two forms is that
```javascript
nerdamer( "(x)^(1/n)" ).evaluate( {x:-0.5,n:3}, "numer").text();
```
make substitutions on the first pass while

```javascript
nerdamer( "(x)^(1/n)", {x:-0.5,n:3}).evaluate().text();
```
first builds the expression therefore making it nerdamer friendly and then parses it again. The second for basically parses the expression twice. Unless you're making high number of calls you probably wouldn't notice the difference but I never explicitly tested this. 

I'll take a look at this and fix this. Thanks for reporting this.

**Comment by jiggzson** [comment]
Disregard. Only partially fixed.

**Comment by jiggzson** [comment]
Done.
