### ISSUE TITLE
Integral of trig functions divided by x gives weird results.

### ISSUE THREAD

**Issue by Saikedo** [jiggzson/nerdamer#518]
I just realized that following integrals fail in a weird way. For example.

`nerdamer("integrate(sin(x)/x)").text()` gives me `"Si(x)"`
`nerdamer("integrate(cos(x)/x)").text()` gives me `"Ci(x)"`

This is kinda different from the rest of the cases where integration fails. I noticed that some integrals return results where integration fails and we always have the word `integrate` in it. For example

`nerdamer("integrate(tan(x)/x)").evaluate().text()` gives me something like 

`"-integrate(integrate(x^(-2),x)*tan(x),x)+integrate(x^(-2),x)*log(sec(x))+log(sec(x))*x^(-1)"` and I parse the result and I see the word `integrate` in the answer and I throw an error saying that integration failed. For cases like sin(x)/x and cos(x)/x however it seems like some parsing issue is taking place.

**Comment by Happypig375** [comment]
They __are__ the correct answers.
Check out: http://mathworld.wolfram.com/SineIntegral.html
http://mathworld.wolfram.com/CosineIntegral.html

**Comment by jiggzson** [comment]
@Saikedo, as @Happypig375 pointed out, these are trigonometric integrals. [See here](https://en.wikipedia.org/wiki/Trigonometric_integral). So far I've only implemented the parts that I need but I hope to finalize it at some point.

If for any reason you'd rather not support trigonometric integrals in your application, you can always just check if it has any of the unsupported functions using the `containsFunction` method. This method is part of the `Symbol` class which is internal to nerdamer and therefore undocumented. 

Would something like the following work?

```javascript
var x = nerdamer('integrate(cos(x)/x+3,x)');
var contains = function(ans, fns) {
    for(var i=0; i<fns.length; i++) 
        if(ans.symbol.containsFunction(fns[i]))
            return true;
    return false;
};
console.log(contains(x, ['Si', 'Ci']));
```
