### ISSUE TITLE
retval.equals is not a function

### ISSUE THREAD

**Issue by q2apro** [jiggzson/nerdamer#519]
Trying to solve with nerdamer-1.1.2:

```
var sol = nerdamer.solveEquations('x^3+x^2+2*x=6');
console.log(sol.toString());
```

Same with:
```
var sol = nerdamer.solveEquations('x^3+x^2+5=4');
console.log(sol.toString());
```

Throws:

> Algebra.js:2136 Uncaught TypeError: retval.equals is not a function
>    at Object.factor (Algebra.js:2136)
>    at Function.solve [as solveEquations] (Solve.js:1196)
>    at <anonymous>:1:20
>factor	@	Algebra.js:2136
>solve	@	Solve.js:1196
>(anonymous)	@	VM3546:1

Both have solutions.

Bug?

**Comment by Happypig375** [comment]
`solveEquations` currently only understands a system of linear equations. For quadratics, cubics or above, use `solve` instead.

**Comment by q2apro** [comment]
`solve` seems not to accept inputs like:

```
var x = nerdamer('solve(x^3+x^2+5=4, x)');
console.log(x.toString());
```

Error message:

> name: "ParseError"
> message: "retval.equals is not a function: 1"

**Comment by jiggzson** [comment]
@q2apro, it was indeed a bug. Fixed on `dev`

**Comment by jiggzson** [comment]
> solveEquations currently only understands a system of linear equations. For quadratics, cubics or above, use solve instead.

@Happypig375, you're right. I think originally this was the case but for some reason `solveEquations` seems to be interchangeable with `solve`. I can't remember if this was be design or coincidentally .

**Comment by q2apro** [comment]
@jiggzson I tried the dev version, same error message still. Example:

```
xnerdamer.solveEquations("x^3 + x^2 + 5 = 4").toString();
```

**Comment by jiggzson** [comment]
@q2apro, it should be fixed on `dev`. I introduced this bug when trying to solve for factors. This allows many more solutions to be found. We get this bug because `factor` does not convert `Equations` but hopefully we got them all. Please let me know if you find anything else.

**Comment by q2apro** [comment]
Great, seems to work now 👍 

Thanks for this awesome library, it's incredible. I still dig into all the features 😄

**Comment by jiggzson** [comment]
Awesome. You're welcome and thank you. Please let me know if you find anything else.

**Comment by q2apro** [comment]
There might be some bug reports coming over the next months.

I have just decided to use nerdamer for mainly the quick solving of equations as a helper tool at Germany's biggest math community.

Announcement: https://www.mathelounge.de/690418/projekt-rechenfreund-erweiterung-mathelounge-hilfsrechner

Thanks for this fantastic work, which makes people independent from Wolframalpha and alike 🍀

**Comment by jiggzson** [comment]
@q2apro, that's exciting news! Thank you for letting me know. I'm happy the library was able to contribute. I'm glad to help.

**Comment by q2apro** [comment]
Sorry for being completely offtopic, but: 

How did you come up with the name "Nerdamer" and what does it mean? ... From "nerd"? Would be interesting! 😃

**Comment by jiggzson** [comment]
> Sorry for being completely offtopic, but:
> 
> How did you come up with the name "Nerdamer" and what does it mean? ... From "nerd"? Would be interesting! 😃

Not a problem. Thanks for asking actually. It's probably not as interesting as you may think. Many moons ago, I was working on the learning system to help teach mechanics since I did a lot of tutoring at the time. I needed a symbolic system but there weren't any at the time. Mathjs didn't support symbolics yet so I decided to roll my own and kept going since. It was never really my intention to start the library. It kind of just happened. Nerdamer was the name of that learning system but once I abandoned the project I still had the domain name, artwork, etc. so just called the symbolic library nerdamer. 

The name itself is a play on nerd as you guessed. It was supposed to convey an affinity to being a nerd and the love for learning 😆. Not sure how successful that was.

**Comment by q2apro** [comment]
> Mathjs didn't support symbolics yet
That was the problem I faced that time too, still used it but always hoped for an alternative that can solve equations!

> It kind of just happened.
So valuable! Thanks a 1000 🤓 ❤
