### ISSUE TITLE
Correct results for equations such as sin(x)=0?

### ISSUE THREAD

**Issue by q2apro** [jiggzson/nerdamer#520]
I played around with nerdamer and found out that:

    nerdamer.solveEquations("sin(x)=0").toString();

returns:

> "-1074386247/17999356,-1223835259/14428106,-1223835259/21642159,-1223835259/27825633,-1389542324/63186437,-1400381026/17830205,-1908340923/27611081,-1908340923/55222162,-2*pi,-2474767273/46337817,-3*pi,-411557987/10077152,-411557987/16375372,-411557987/32750744,-411557987/4093843,-411557987/4517344,-411557987/5038576,-411557987/8187686,-4736199730/48631587,-497121195/7535171,-571845701/18202414,-571845701/36404828,-571845701/9101207,-6*pi,-732133415/19420442,-732133415/9710221,-742972117/15766358,-742972117/7883179,-892421129/10145231,-892421129/12350716,-9*pi,-pi,0,1389542324/63186437,2*pi,3*pi,411557987/16375372,411557987/32750744,571845701/36404828,6*pi,9*pi,pi"

IMHO it should return `0` and then pi, 2·pi, 3·pi etc.

Turning the "fraction results" above into decimals gives:

> x₁ = -59.69026042;  x₂ = -84.82300165;  x₃ = -56.54866776;  x₄ = -43.98229715;  x₅ = -21.99114858;  x₆ = -78.53981634;  x₇ = -69.11503838;  x₈ = -34.55751919;  x₉ = -6.283185307;  x₁₀ = -53.40707511;  x₁₁ = -9.424777961;  x₁₂ = -40.8407045;  x₁₃ = -25.13274123;  x₁₄ = -12.56637061;  x₁₅ = -100.5309649;  x₁₆ = -91.10618695;  x₁₇ = -81.68140899;  x₁₈ = -50.26548246;  x₁₉ = -97.38937226;  x₂₀ = -65.97344573;  x₂₁ = -31.41592654;  x₂₂ = -15.70796327;  x₂₃ = -62.83185307;  x₂₄ = -18.84955592;  x₂₅ = -37.69911184;  x₂₆ = -75.39822369;  x₂₇ = -47.1238898;  x₂₈ = -94.24777961;  x₂₉ = -87.9645943;  x₃₀ = -72.25663103;  x₃₁ = -28.27433388;  x₃₂ = -3.141592654;  x₃₃ = 0;  x₃₄ = 21.99114858;  x₃₅ = 6.283185307;  x₃₆ = 9.424777961;  x₃₇ = 25.13274123;  x₃₈ = 12.56637061;  x₃₉ = 15.70796327;  x₄₀ = 18.84955592;  x₄₁ = 28.27433388;  x₄₂ = 3.141592654

And doing a check with result x₁:

DEG: sin(-59,69026042°) = -0,86330977462300366
RAD: sin(-59,69026042) = 1,79392846882736254E-9 ≈ 0 ✓

So obviously it's RADian.

Testing again:

sin(x₄₀) = sin(18,84955592) = -1,53875943161452949E-9 ≈ 0  ✓
sin(x₄₁) = sin(28,27433388) = 2,30813914568707076E-9  ≈ 0  ✓

All correct. I leave this post for documentation. But still I have two questions:

**1. Any way to change to DEGree?**
**2. Any way to limit the number of results?** For the particular case starting with x=0.

**Comment by jiggzson** [comment]
>Any way to limit the number of results? For the particular case starting with x=0.

You can possibly restrict it where to look around 0.

>Any way to change to DEGree?

Internally? No. There is a possibility to convert the solutions if that would work.


Given this information you could do something like
```javascript
//restrict solutions to be found between -10 and 10. 
//As the name implies, this range is always symmetric.
nerdamer.set('SOLVE_RADIUS', 10);
//solve and convert to radians
var x = nerdamer.solveEquations("sin(x)=0").map((x) => nerdamer.degrees(x).symbol);
```
I'll add to the documentation that trig functions are in radians.
