### ISSUE TITLE
Second argument provided to text does not match description in documentation

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#523]
```js
nerdamer("23/77").text('decimals', 0) // "0.29870129870129870129870"
nerdamer("23/77").text('decimals', 1) // "0.0"
nerdamer("23/77").text('decimals', 2) // "0.3"
nerdamer("23/77").text('decimals', 3) // "0.210"
nerdamer("23/77").text('decimals', 4) // "0.299"
nerdamer("23/77").text('decimals', 5) // "0.2987"
nerdamer("23/77").text('decimals', 6) // "0.29870"
nerdamer("23/77").text('decimals', 7) // "0.298701"
nerdamer("23/77").text('decimals', 8) // "0.2987013"
nerdamer("23/77").text('decimals', 9) // "0.298701210"
nerdamer("23/77").text('decimals', 10) // "0.298701299"
```
This looks like the second argument provided to `text` indicates the number of steps used to approximate the decimal. This does not match the documentation where it should indicate the number of decimal places shown.

**Comment by jiggzson** [comment]
@Happypig375, I think I managed to fix this. The second argument is supposed to be the nth place where the rounding should occur. I'll also clarify this in the docs.

**Comment by AlienKevin** [comment]
@jiggzson I think currently decimals are not rounded when they are nested within an expression. For instance,
```
nerdamer("1/3x").text("decimals", 3)
```
yields
```
"0.3333333333333333*x"
```
Is it possible to recursively round all numbers in an expression?
Also it would be nice if functions like `toTeX()` and `convertToLaTeX` can have options for specifying rounding.

**Comment by jiggzson** [comment]
@AlienKevin, the latest version on the dev branch does.

**Comment by AlienKevin** [comment]
@jiggzson That's excellent! Is it possible to extend the rounding option to `toTeX()` as currently I need to do
```
nerdamer(nerdamer("1/3x").text("decimals", 3)).toTeX()
```
to get rounding in LaTeX outputs.
