### ISSUE TITLE
Typos in Docs

### ISSUE THREAD

**Issue by q2apro** [jiggzson/nerdamer#524]
1. Some occurences of "SetContant". - missing "s"
https://nerdamer.com/functions/nerdamer.setConstant.html

2. "Throws an(d) error if no transform could be calculated." - remove "d"
https://nerdamer.com/functions/laplace.html

Please fix 😉

**Comment by jiggzson** [comment]
> Some occurences of "SetContant". - missing "s"
https://nerdamer.com/functions/nerdamer.setConstant.html

I'm confused. There is  no method `setConstants`. 

> "Throws an(d) error if no transform could be calculated." - remove "d"
https://nerdamer.com/functions/laplace.html

Thanks for pointing this out.

**Comment by q2apro** [comment]
And https://nerdamer.com/functions/abs.html is missing in the listing at https://nerdamer.com/documentation.html
