### ISSUE TITLE
Solving an equation with variable x works, but not with variable a (solveEquations)

### ISSUE THREAD

**Issue by q2apro** [jiggzson/nerdamer#525]
I tried to solve:

    sol = nerdamer.solveEquations('2*a^(2)+4*a*6=128');
    console.log(sol.toString());

which gives `""``. The same with:

     var sol = nerdamer('solve(2*a^(2)+4*a*6=128, a)');
     console.log(sol.toString());

What is the problem? The dev console does not throw an error.

But using `x` instead of `a` works:

    nerdamer.solveEquations('2*x^(2)+4*x*6=128').toString();
    nerdamer('solve(2*x^(2)+4*x*6=128, x)').toString()

**Comment by jiggzson** [comment]
@q2apro, fixed on the dev branch.
