### ISSUE TITLE
Matrix scalar multiplication does not work

### ISSUE THREAD

**Issue by FredericMrozinski** [jiggzson/nerdamer#538]
`matrix([1,2],[3,4])*2` gives the result `matrix([1,2],[3,4])` instead of `matrix([2,4],[6,8])` (at least in the website demo version). Likewise, `matrix([1,2],[3,4])^2` or `matrix([1,2],[3,4])^(-1)` does not alter the matrix, either.

(PS: Sorry for reporting so much, I just love Nerdamer and hope that I can contribute a little through that :-) )

**Comment by jiggzson** [comment]
@FredericMrozinski, I suspect that scalar operations with matrices was never completed. I'll complete those since this should be fairly easy. Also, you're not over-reporting at all. In fact, thank you for doing so. I really appreciate that.

**Comment by jiggzson** [comment]
@FredericMrozinski, fixed.
