### ISSUE TITLE
solving system of linear equations is broken

### ISSUE THREAD

**Issue by JanMP** [jiggzson/nerdamer#54]
nerdamer.solveEquations(['x+y=1', '2*x=6', '4*z+y=6']) throws "System must contain all linear equations!"

**Comment by jiggzson** [comment]
I suspect that it's related to the fact that we switched to BigNumbers and never adjusted the operators to take this into account. I'll take care of this. Thanks.

**Comment by jiggzson** [comment]
I imagine you took a swing at it and realized that it was quite a little nasty bug lol. I'm glad this was brought to my attention. In previous versions of nerdamer if I did this
```javascript
var symbol = new Symbol(n);
var symbol2 = new Symbol(symbol);
```
I'd get a clean "clone" for symbol2. This is no longer the case and one of the reasons this was such a nasty little bug to track. 

Thanks again.

**Comment by JanMP** [comment]
No, I haven't really got to dig into your code yet. I got enough work ahead of me with my own little project (which makes use of nerdamer quite a bit, don't think I would want to do it without it). You can check it out at http://mathe-coach-janmp.herokuapp.com

**Comment by jiggzson** [comment]
Awesome. It's always nice to see projects which use nerdamer. Glad it could help. It also helps me know what to focus on.
