### ISSUE TITLE
nerdamer cant get difficult indefinite integrals

### ISSUE THREAD

**Issue by MAGNETO903** [jiggzson/nerdamer#544]
I want to get antiderivatives of some functions:

function: `3*sin(2*x)*cos(x)^4`
expects: `-acos(x)^6`
returns: `(1/4)*(-3*cos(x)+cos(3*x))`

function:` 3*sin(2*x)*sin(x)^4`
expects: `sin(x)^6`
returns: `(1/2)*(-3*sin(x)+sin(3*x))`

**Comment by jiggzson** [comment]
Noted.

**Comment by jiggzson** [comment]
Moving to #334
