### ISSUE TITLE
cant build function

### ISSUE THREAD

**Issue by MAGNETO903** [jiggzson/nerdamer#545]
I tried 
`
var f  = nerdamer('acos((-x)^(1/6))').buildFunction();
`

but i get error:
`
TypeError: Cannot read property 'toString' of undefined
`

but if i try
`
var f =  nerdamer('acos((x)^(1/6))').buildFunction();
`
it's works

when in expression i have `-x`, nerdamer breaks

but if i set function `root`
`nerdamer.setFunction('root', ['n', 'x'], 'x^(1/n)');`

and try to build function:
` nerdamer('acos(root(6, -x))').buildFunction(); `

it's works too
what's wrong?

**Comment by MAGNETO903** [comment]
Also i found this:
I have a normal expression: `(4*x^2-9)^(1/4)`

I want to build js function, so i use `buildFunction()`

`var f2 = nerdamer("(4*x^2-9)^(1/4)").buildFunction();`

then I see the text of this function
`console.log(f2.toString())`

and I look:
`
function anonymous(x
) {
 return Math.pow(4*Math.pow(x,2)+-9,0.25);
}
`

because of `+-9` my function would not work.

**Comment by jiggzson** [comment]
@MAGNETO903, `buildFunction` is getting confused by the parentheses. The quickest fix is to add

```javascript
if(symbol.fname === '') {
    symbol = Symbol.unwrapPARENS(symbol);
}
```
at the top of the `ftext` function [here](https://github.com/jiggzson/nerdamer/blob/c9948d571f391cd97d0720d2196b2120f929fb73/nerdamer.core.js#L11152). I'll add it.

**Comment by MAGNETO903** [comment]
You mean at 11152 line?
`var ftext = function (symbol, xports) {`
`xports = xports || [];`
`...`
