### ISSUE TITLE
System of equations fail with Maximum call stack size exceeded

### ISSUE THREAD

**Issue by cur3n4** [jiggzson/nerdamer#546]
The equations are:

```
solveEquations([
   `y=x * 2`,
   `z=y + max (y * 0.1, 23)`,
   `j=y + max (y * 0.1, 23)`,
   `6694.895373 = j + z + (max(j * 0.280587, z * 0.280587, 176))`
])
```

Wolfram Alpha returns: 
x = 1334.36 and y = 2668.73 and z = 2935.6 and j = 2935.6

**Comment by jiggzson** [comment]
Interesting. I'll look into it.

**Comment by jiggzson** [comment]
@cur3n4, this one is fixed. I know if sat a while but I finally managed to get to it. Oddly enough, I thought this was going to be a lot harder than it really was. I don't get Wolfram Alpha's numbers instead I get
```
{ 
  j: 2935.601831019821,
  x: 1334.3644686453729,
  y: 2668.7289372907458,
  z: 2935.601831019821 
}
```
These numbers seem to also satisfy the system.
