### ISSUE TITLE
factor() not giving a correct answer.

### ISSUE THREAD

**Issue by vader-coder** [jiggzson/nerdamer#547]
When I use nerdamer in a script linked to an html page, I don't get the correct roots. 
`  console.log(nerdamer('factor(x^2-4*x+4)').toString());` returns `(-4*x+x^2+4)*factor` instead of `(x-2)(x-2)` or `(x-2)^2`.

**Comment by Happypig375** [comment]
Did you load `Algebra.js` in addition to `nerdamer.core.js`?
