### ISSUE TITLE
nerdamer.solveEquation quits working

### ISSUE THREAD

**Issue by JanMP** [jiggzson/nerdamer#55]
console.log(nerdamer.solveEquations("x+1=2", "x").toString())
console.log(nerdamer("x=1").text("fractions"))
console.log(nerdamer.solveEquations("x+1=2", "x").toString())

this logs an empty string for the third line

**Comment by jiggzson** [comment]
Interesting. At first glance it seems to be related to variable
substitution. I'll delve into this a bit more shortly.

**Comment by jiggzson** [comment]
As suspected this is related to variable substitution. The solution is to call clearVars at the beginning of the solve function (currently at line 95).
Basically replace this
```javascript
var solve = function(eqns, solve_for) {
       if(isArray(eqns)) return sys_solve.apply(undefined, arguments);
```
with this
```javascript
 var solve = function(eqns, solve_for) {
        nerdamer.clearVars();
        if(isArray(eqns)) return sys_solve.apply(undefined, arguments);
```
I'm currently working on something else but I'll be adding this fix with my  next commit. You'll have this in case you need this right away.

**Comment by JanMP** [comment]
It had caused some interesting bug in my app, The piece of code that was doing the nerdamer call that broke things also caused some problems in other parts and I rewrote it and now everything is working for me (atm, at least). So in hindsight it was actually helpful ;-P

**Comment by jiggzson** [comment]
Awesome. That's good to hear. It's funny how long this one went unnoticed. Good catch. Thanks.
