### ISSUE TITLE
Add advance root function (nth root and cubic root)

### ISSUE THREAD

**Issue by MAGNETO903** [jiggzson/nerdamer#550]
Add function (maybe `root(a, b)`) that return number `c` that `c^a=b`

`root(3, 8) // return 2`
`root(4, 16) // return 4`
`root(8, 3) // return 1.1472...`

And also add `cbrt(a)` that return number `b` that `b^3=a` (cubic root)

`cbrt(8) // return 2`
`cbrt(27) // return 3`
`cbrt(2) // return 1.2599...`

**Comment by Happypig375** [comment]
Are you looking for the real root or the principal root? They are different when complex numbers are in the picture.

**Comment by MAGNETO903** [comment]
I did not undertstand the differense between the real root and the principan root, but I am looking for function like `nthRoot()` in [mathjs](https://mathjs.org/) library
[nthRoot function](https://mathjs.org/docs/reference/functions/nthRoot.html)

**Comment by jiggzson** [comment]
I know that an `nthroot` function was started at some point but was never completed. I'll look into completing it. Adding a `cbrt` function might not be a bad idea as well.

**Comment by jiggzson** [comment]
Done.
