### ISSUE TITLE
Incorrect solution of rational equation

### ISSUE THREAD

**Issue by ElectrifyPro** [jiggzson/nerdamer#555]
`nerdamer('solve(1/x, x)').toString()` returns `[0]` when there should be no solutions.
`nerdamer('solve(1/x=0, x)').toString()` throws a parser error, even though these two (I believe) should behave the same

**Comment by jiggzson** [comment]
@ElectrifyPro, interesting. I agree, they both should return an empty solution set. Thanks for reporting this.
