### ISSUE TITLE
Nerdamer apparently fails to integrate "exp(log(x)) = x" and "exp(sin(x))*cos(x)".

### ISSUE THREAD

**Issue by MiltonCobo** [jiggzson/nerdamer#558]
The library doesn't recognize that "exp(2*log(x))" is equal to "x^2". Also the integral of "exp(sin(x))*cos(x)" is easily solve by making the substitution "u=sin(x)". This is important because this integrals appears frequently when solving simple linear ODEs.

**Comment by jiggzson** [comment]
Got it. Thanks.
