### ISSUE TITLE
exp(i + x pi) gives sin(π⋅x)⋅i+cos(π⋅x)

### ISSUE THREAD

**Issue by dromastyx** [jiggzson/nerdamer#560]
Hi, thanks for this great project. I think there might be an error with the exp function: exp(i + x pi) gives the same expression as exp(i pi x), which is sin(π⋅x)⋅i+cos(π⋅x). Then if we, for example, evaluate exp(i  + pi), we get -1, which I think is incorrect.

**Comment by jiggzson** [comment]
@dromastyx, you're right. I think this is related to a misinterpretation of Euler's identity within nerdamer. I'll take a look at it. Thanks for reporting.
