### ISSUE TITLE
Problems with fractional powers (when I build function)

### ISSUE THREAD

**Issue by MAGNETO903** [jiggzson/nerdamer#561]
I have a simple expression
`log(x)^(1/3)` (1)
which is equivalent
`cbrt(log(x))` (2)

I built expression (1)
`var f = nerdamer("log(x)^(1/3)").buildFunction()`
and then tried to use it
```
console.log(f(0)) // Infinity
console.log(f(0.2)) // NaN
console.log(f(0.99)) // NaN
```
it fails

But when I build expression (2)
`var f2 = nerdmamer("cbrt(log(x))").buildFunction()`
and tested
```
console.log(f2(0)) // -Infinity
console.log(f2(0.2)) // -1.17190230687955
console.log(f2(0.99)) // -0.2158043485359359
```
that's right

**Comment by MAGNETO903** [comment]
Thats occurs, because `Math.pow(n, x)` cant calculate when n<0 and x<1.
So, I can write my own `nthRoot(n, x)` and say nerdamer to user `nthRoot(n, x)` instead of `Math.pow()`

**Comment by jiggzson** [comment]
@MAGNETO903. yes you can. You can define your own function name `nthRoot` function but make sure you also define it's numeric equivalent within the `Math2` object. I'll try to provide an example soon.

**Comment by jiggzson** [comment]
@MAGNETO903, was your issue resolved?

**Comment by MAGNETO903** [comment]
no

**Comment by jiggzson** [comment]
@MAGNETO903, here's an interesting observation. You get the same issue when using Wolfram Alpha.

Here's[ `log(x)^(1/3)` ](https://www.wolframalpha.com/input/?i=log%28x%29%5E%281%2F3%29%2C+x%3D0.2) and here's [`cbrt(log(x))`](https://www.wolframalpha.com/input/?i=cbrt%28log%28x%29%29%2Cx%3D0.2). Wolfram Alpha gives a complex value for one and not the other.
