### ISSUE TITLE
"System does not have a distinct solution" when solving system of linear equations

### ISSUE THREAD

**Issue by CAG2Mark** [jiggzson/nerdamer#562]
`nerdamer.solveEquations(['x+y=1', '2*x=6', '4*z+y=6']);` outputs the following:
`[["x", 3], ["y", -2], ["z", 2]]`

When I add the equation 'y = (-1) * z' to the system, the solution should not change, as y is indeed equal to -z. However, when I run the following code:
`nerdamer.solveEquations(['x+y=1', '2*x=6', '4*z+y=6', 'y = (-1) * z']);`
I get the error:
`System does not have a distinct solution`

**Comment by jiggzson** [comment]
This one might be somewhat related to #546 but I'm not sure.

**Comment by CAG2Mark** [comment]
I don't know to be honest. But it would be useful if it was able to
recognise duplicate equations in a system of linear equations.
