### ISSUE TITLE
Simplify wrongly thinks sin(x)^2+cos(x)^2-1 = 1

### ISSUE THREAD

**Issue by thunderkid** [jiggzson/nerdamer#567]
Run `simplify(sin(x)^2+cos(x)^2-1)`. It gives `1` instead of `0`.
But run it on `simplify(sin(x)^2+cos(x)^2)` and it correctly returns `1`.
However, `simplify(1-1)` correctly gives `0`.
I'm running version 1.1.5 and also checked on the demo website. Same results.

**Comment by jiggzson** [comment]
Got it. I'll take care of this. Thanks for reporting.
