### ISSUE TITLE
Limit to infinity fails

### ISSUE THREAD

**Issue by MatheNerd92** [jiggzson/nerdamer#572]
HI, 
first of all thanks for your library. It is great!  I think I found a mistake. 
`Nerdamer('limit(e^(-x),x,Infinity)');
//0`

But this one gives 
`Nerdamer('limit(e^(-x)+2,x,Infinity)');
//Infinity`

**Comment by Meowcolm024** [comment]
I found the same problem.

**Comment by jiggzson** [comment]
@Meowcolm024, the library currently doesn't know how to get this limit and should have returned it as a limit. I'll leave this open and work on a solution to these types.

**Comment by jiggzson** [comment]
@MatheNerd92, @Meowcolm024 both limits should now be fixed.
