### ISSUE TITLE
`log(1/sqrt(2))` get wrong output

### ISSUE THREAD

**Issue by DylanXie123** [jiggzson/nerdamer#573]
I find a bug when I test some math eqautions.
`1/sqrt(2)==0.7071` and `log(0.7071)==-0.3552`,
but when I type `log(1/sqrt(2))`, I get `0.3552` instead of `-0.3552`
![Image](https://s1.ax1x.com/2020/10/13/04e3sU.jpg)

**Comment by jiggzson** [comment]
Got it. Will fix.
