### ISSUE TITLE
I'd like to sort result of nerdamer in power order, not alphabetical

### ISSUE THREAD

**Issue by michalmicpaw** [jiggzson/nerdamer#578]
Hi.

What should I change, to sort result of **nerdamer(str).evaluate().toTeX()**, to be ordered in **power** order?

I.E.

**1/3*x^3+1/2x+x^2** => **1/3*x^3+x^2+1/2*x**?

Where should I dig?

**Comment by jiggzson** [comment]
Your issue seems to be related to the fact that you call evaluate. When you just call `toTeX` it does order it in the form you prefer. Not sure why this happens when evaluate is called.
