### ISSUE TITLE
Expression doesn't get invalidated correctly. 

### ISSUE THREAD

**Issue by iamprayush** [jiggzson/nerdamer#583]
Parsing expressions like `+` or `(+)` should yield errors but they don't.
I tried running `console.log(nerdamer('+'))` and no errors were thrown, whereas if I did the same with any other operator, errors were thrown as expected.

**Comment by jiggzson** [comment]
@iamprayush, agreed. This should be easy enough to fix. I'll probably have it throw something like `UnexpectedOperatorError`.
