### ISSUE TITLE
Is it possible for `nerdamer.convertFromLaTeX(TeX)` to support LaTex matrix?

### ISSUE THREAD

**Issue by DylanXie123** [jiggzson/nerdamer#584]
I want to parse LaTex matrix with nerdamer, but I find `nerdamer.convertFromLaTeX(TeX)` throw error when parsing
```latex
  \begin{matrix}
   1 & 2 \\
   7 & 8
  \end{matrix}
```
example code:
```js
let expStr = '\\begin{matrix}1 & 2 \\ 7 & 8\\end{matrix}';
let expression = nerdamer.convertFromLaTeX(expStr);
```
this gives
```bash
ParseError: & is not a valid variable name: 19: undefined
```

**Comment by jiggzson** [comment]
@DylanXie123, I don't think it should be too difficult. I'll look into it.

**Comment by jiggzson** [comment]
@DylanXie123,

Correct me if I'm wrong but shouldn't it be?

```javascript
let expStr = '\\begin{matrix}1 & 2 \\\\ 7 & 8\\end{matrix}';
let expression = nerdamer.convertFromLaTeX(expStr);
```

**Comment by DylanXie123** [comment]
@jiggzson I think you are right.

**Comment by jiggzson** [comment]
@DylanXie123. I added an update on the `dev` branch. Let me know of that's what you had in mind.

**Comment by DylanXie123** [comment]
@jiggzson That's exactly what I want, thanks!
