### ISSUE TITLE
Incorrect solve output for some polynomial equations

### ISSUE THREAD

**Issue by jaypaik** [jiggzson/nerdamer#588]
Hi!

I'm seeing differences in solutions between `nerdamer` and [Wolfram Alpha](https://www.wolframalpha.com/input/?i=solve+d%2Fdx+10-110%2F%2820-100%2F%2810%2Bx%29%29-x) for this particular call:
```javascript
nerdamer("diff(10-110/(20-100/(10+x))-x, x)").solveFor("x").toString()
// "-10,(1/4)*j-10,(-1/4)*j-10"
```
```javascript
// Wolfram Alpha (linked above)
// -5 - sqrt(55/2), -5 + sqrt(55/2)
```

When taking the output of `diff` and solving it via [Wolfram Alpha](https://www.wolframalpha.com/input/?i=solve+-1%2B11000*%28-100*%2810%2Bx%29%5E%28-1%29%2B20%29%5E%28-2%29*%2810%2Bx%29%5E%28-2%29), it seems to produce the correct results, so it seems the bug is in the `solve` function. 
```javascript
nerdamer("diff(10-110/(20-100/(10+x))-x, x)").toString()
// "-1+11000*(-100*(10+x)^(-1)+20)^(-2)*(10+x)^(-2)"
// Wolfram Alpha's solution: -5 - sqrt(55/2), -5 + sqrt(55/2)
```

Am I using this wrong / is there some setting to produce the correct numbers here? Thanks for taking a look!

**Comment by jiggzson** [comment]
@jaypaik, thanks for bring this to my attention.

> Am I using this wrong / is there some setting to produce the correct numbers here? Thanks for taking a look!

A quick investigation seems to point at a bug in `expand`. I'll have to take a closer look to see exactly what's happening.

`expand(-(-100*(10+x)^(-1)+20)^2*(10+x)^2+11000)`
 gives
 `-16000000*(10+x)^(-2)*x^2-1600000000*(10+x)^(-2)-29000-320000000*(10+x)^(-2)*x-400*x^2-8000*x`
 but should give
 `-(10000*x^2)/(x^2+20*x+100)-(200000*x)/(x^2+20*x+100)-1000000/(x^2+20*x+100)+(4000*x^2)/(x+10)+(80000*x)/(x+10)+400000/(x+10)-400*x^2-8000*x-29000`

**Comment by jiggzson** [comment]
@jaypaik. Fixed. Quite an interesting issue by the way. It was a lot more involved than I initially thought. It actually ended up exposing three bugs.

**Comment by jaypaik** [comment]
Wow, that does seem like a pretty involved fix, and I see you had to deal with what seems like floating point precision issues too. Thanks for the fix and actively maintaining this project to this day. Cheers!

**Comment by jiggzson** [comment]
> I see you had to deal with what seems like floating point precision issues too

Unfortunately you are correct. Someday I'll find the time and motivation to do a complete conversion to big numbers.

> Thanks for the fix and actively maintaining this project to this day. Cheers!

You're welcome and thanks.
