### ISSUE TITLE
Incorrect derivative

### ISSUE THREAD

**Issue by richbully** [jiggzson/nerdamer#590]
Hello! 

Just reporting an error with derivative.

Using the demo on your website returns the below:
![image](https://user-images.githubusercontent.com/11023398/107584443-5ba37a80-6c61-11eb-9b6e-7a776f7d3016.png)

The first part of the answer should be "3(x^0.5+x)^2" or equivalent? If you substitute x=4 into the result you should get 135 not 75.9

Cheers
Richard

**Comment by jiggzson** [comment]
@richbully, got it. Thanks.
