### ISSUE TITLE
Definite integral answer incorrect

### ISSUE THREAD

**Issue by richbully** [jiggzson/nerdamer#593]
Hello,

Please refer to the below image using your demo page.

The integration of z with respect to x correctly returns "z*x" but if you take the definitive integral between 0 and 1 you incorrectly get "1/2", should be 'z'.

Works correctly if you put a constant in though (i.e. bottom example)

![image](https://user-images.githubusercontent.com/11023398/110391860-f52d4300-80cc-11eb-9ba2-da5755453a01.png)

Kind Regards

**Comment by jiggzson** [comment]
@richbully, I see. It sees a variable and wrongly assumes it to be the variable of integration. Got it.
