### ISSUE TITLE
solveFor return empty array

### ISSUE THREAD

**Issue by gulyasmarton** [jiggzson/nerdamer#595]
Hello,

I have an ugly equation:

```
0=((2*0.87*x-2*sqrt(x^2(0.87^2-1)+4*4^2))/2)^2+((2*0.86*x-2*sqrt(x^2(0.86^2-1)+4*5^2))/2)^2-0.87*((2*0.87*x-2*sqrt(x^2(0.87^2-1)+4*4^2))/2)*((2*0.86*x-2*sqrt(x^2(0.86^2-1)+4*5^2))/2)-6^2
```
According to [WolframAlpha](https://www.wolframalpha.com/input/?i=solve+%28%282*0.87*x-2*sqrt%28x%5E2%280.87%5E2-1%29%2B4*4%5E2%29%29%2F2%29%5E2%2B%28%282*0.86*x-2*sqrt%28x%5E2%280.86%5E2-1%29%2B4*5%5E2%29%29%2F2%29%5E2-0.87*%28%282*0.87*x-2*sqrt%28x%5E2%280.87%5E2-1%29%2B4*4%5E2%29%29%2F2%29*%28%282*0.86*x-2*sqrt%28x%5E2%280.86%5E2-1%29%2B4*5%5E2%29%29%2F2%29-6%5E2) the result ~ 3.9 and 13.0

The nerdamer can parse the input string without an issue (output of toString() function):
```
0=(-43/25)*sqrt((-651/2500)*x^2+100)*x+(-87/400)*((43/25)*x-2*sqrt((-651/2500)*x^2+100))*((87/50)*x-2*sqrt((-2431/10000)*x^2+64))+(-87/50)*sqrt((-2431/10000)*x^2+64)*x+(993/1000)*x^2+128
```

<img src="https://render.githubusercontent.com/render/math?math=0%20%3D%20%7B%5Cleft(%5Cfrac%7B2%20%5Ccdot%20%5Cfrac%7B87%7D%7B100%7D%20%5Ccdot%20x%20-%202%20%5Ccdot%20%5Csqrt%7B%7Bx%7D%5E%7B2%7D%20%5Cleft(%7B%5Cfrac%7B87%7D%7B100%7D%7D%5E%7B2%7D%20-%201%5Cright)%20%2B%204%20%5Ccdot%20%7B4%7D%5E%7B2%7D%7D%7D%7B2%7D%5Cright)%7D%5E%7B2%7D%20%2B%20%7B%5Cleft(%5Cfrac%7B2%20%5Ccdot%20%5Cfrac%7B43%7D%7B50%7D%20%5Ccdot%20x%20-%202%20%5Ccdot%20%5Csqrt%7B%7Bx%7D%5E%7B2%7D%20%5Cleft(%7B%5Cfrac%7B43%7D%7B50%7D%7D%5E%7B2%7D%20-%201%5Cright)%20%2B%204%20%5Ccdot%20%7B5%7D%5E%7B2%7D%7D%7D%7B2%7D%5Cright)%7D%5E%7B2%7D%20-%20%5Cfrac%7B87%7D%7B100%7D%20%5Ccdot%20%5Cleft(%5Cfrac%7B2%20%5Ccdot%20%5Cfrac%7B87%7D%7B100%7D%20%5Ccdot%20x%20-%202%20%5Ccdot%20%5Csqrt%7B%7Bx%7D%5E%7B2%7D%20%5Cleft(%7B%5Cfrac%7B87%7D%7B100%7D%7D%5E%7B2%7D%20-%201%5Cright)%20%2B%204%20%5Ccdot%20%7B4%7D%5E%7B2%7D%7D%7D%7B2%7D%5Cright)%20%5Ccdot%20%5Cleft(%5Cfrac%7B2%20%5Ccdot%20%5Cfrac%7B43%7D%7B50%7D%20%5Ccdot%20x%20-%202%20%5Ccdot%20%5Csqrt%7B%7Bx%7D%5E%7B2%7D%20%5Cleft(%7B%5Cfrac%7B43%7D%7B50%7D%7D%5E%7B2%7D%20-%201%5Cright)%20%2B%204%20%5Ccdot%20%7B5%7D%5E%7B2%7D%7D%7D%7B2%7D%5Cright)%20-%20%7B6%7D%5E%7B2%7D">

But when I'm trying to solve it then I got an empty array as a result without any error message...
``` javascript
var d = nerdamer(eqString);
console.log(d.toString());
var solutions = d.solveFor('x');
console.log(solutions);
//output: []
```

I do something wrong?

**Comment by jiggzson** [comment]
> I have an ugly equation:

😆 It is a bit hairy looking but in a pet-like way.

>  I do something wrong?

Nope. So here's the thing. Under the hood, when all else fails, solve reverts to Newton's iterations and tries to solve it numerically. It first generates a few good starting points and then checks for zeroes around that point. In reality it should've tried something like bisection first since Newton sometimes overshoots the point because of how JS numbers behave. I've been putting it off for some time but this issue somewhat gave me a good case to work with.

This issue should be fixed on the `dev` branch. Let me know if you have any questions.
