### ISSUE TITLE
Fraction expansion

### ISSUE THREAD

**Issue by brosnanyuen** [jiggzson/nerdamer#6]
Evaluating (x+1)/(x^2 -i) gives x/(x^2 - i) + (1)/(x^2 +i) at http://nerdamer.com/demo
It doesn't like imaginary numbers.

**Comment by jiggzson** [comment]
The problem seems to be with the latex generator. It still fails in some instances. If you were to this for instance
```javascript
var x = nerdamer('(x+1)/(x^2-i)');
console.log(x.text());
```
You will get get
```javascript
//(-i+x^2)^(-1)*(1+x)
```
which is correct. I'll label this as a bug for the latex generator.
