### ISSUE TITLE
Trigonometric Functions

### ISSUE THREAD

**Issue by Ephraim-Bryski** [jiggzson/nerdamer#600]
`nerdamer('tan(b)=c').solveFor('b').toString()`
returns "atan(c)"

but

`nerdamer('sin(b)/cos(b)=c').solveFor('b').toString()`
returns ""

Is it generally not recommended to use nerdamer with trig functions? Is there a workaround?

**Comment by jiggzson** [comment]
@Ephraim-Bryski, I'm unable to verify but does calling simplify on your equation first work?

**Comment by Ephraim-Bryski** [comment]
Sorry for the late response. Simplify does work if done on the individual expressions. I see you have a commit to extend simplify to "Equation" would allow direct simplification of the equation instead. Thank you!

**Comment by jiggzson** [comment]
@Ephraim-Bryski, glad to help.
