### ISSUE TITLE
Test Truth of Equality

### ISSUE THREAD

**Issue by Ephraim-Bryski** [jiggzson/nerdamer#602]
I would like to test if an equality containing variables is necessarily true. For example
`a*b=b*a`      would return true, while
`a=b`             would return false (not necessarily true)

(Of course, exactly what it returns isn't important, just some way of distinguishing).

Is this possible to do currently? Could it be implemented in Nerdamer? Thank you!

**Comment by jiggzson** [comment]
@Ephraim-Bryski, would something like this work?

```javascript
console.log(nerdamer('a*b').eq('b*a')); // true
console.log(nerdamer('a-b').eq('b-a')); // false

nerdamer.setVar('x',3);
console.log(nerdamer('x+a').eq('a+3')); // true
```
You can find the remaining operations [here](https://nerdamer.com/documentation.html) under Expression > Equality.

**Comment by Ephraim-Bryski** [comment]
Thank you, that's exactly what I was looking for.
