### ISSUE TITLE
Variable names with subscript - Tex generation

### ISSUE THREAD

**Issue by szoshi** [jiggzson/nerdamer#603]
I am very new to the library so i might be missing something very obvious. I can declare a variable like a_ij but when I convert it to tex using toTex only the i is in the subscript with j on the same level as a. How do I convert larger subscripts or superscripts to tex correctly? Am I missing something? A parameter for e.g.?

Thanks in advance and apologies if this has been asked already...

**Comment by jiggzson** [comment]
@szoshi, no need to apologize. Fixed on the `dev` branch.

**Comment by szoshi** [comment]
Hi, great job. Just tested it. You can close this issue. Is there a forum somewhere or is opening an issue the best way to ask questions?

**Comment by jiggzson** [comment]
@szoshi, feel free to open an issue. It makes it easier for me to track. You can also ask general questions on the [site ](https://nerdamer.com)but I sometimes miss those.
