### ISSUE TITLE
Possible bug in subtract function?

### ISSUE THREAD

**Issue by szoshi** [jiggzson/nerdamer#606]
Hi, 
I have come across something which I cannot explain. Here is minimal code to reproduce it:
var a = nerdamer('2*x-y');
var b = nerdamer('2*x-y+4');
b.subtract(a).toTex() gives 4 but a.subtract(b).toTex() returns 0 and not -4. Is there another way to get the difference between two terms? I am working with the dev branch btw.
Thanks!

**Comment by szoshi** [comment]
Just verified that the demo on the webpage does the same. (2x-y) - (2x-y+4) gives 0.

**Comment by jiggzson** [comment]
@szoshi, fixed on `dev`. Thanks for bringing it to my attention.

**Comment by szoshi** [comment]
Tested. Works. Closing. Thanks!
