### ISSUE TITLE
Coeffs....complex numers?

### ISSUE THREAD

**Issue by szoshi** [jiggzson/nerdamer#609]
After working with coeffs and complex numbers separately, my next step was to combine them. If i have a complex valued polynomial, turns out nerdamer.coeffs fails. I am guessing the functionality is missing or am I doing something wrong?

**Comment by jiggzson** [comment]
@szoshi, this should be an easy fix.

**Comment by szoshi** [comment]
Hi, did you get a chance to work on this?

**Comment by jiggzson** [comment]
@szoshi, I haven't had a chance. It's still in queue.

**Comment by szoshi** [comment]
Hi, I just checked it today and it works as expected. i will report if I find something. While we are on the subject of complex numbers, I have noticed that the String or Tex representation of complex numbers is in the form b.i + a and not as a + b.i as is standard. Is there a way to change this?
