### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by danielsvane** [jiggzson/nerdamer#61]
I stumbled upon [this SO post](http://stackoverflow.com/questions/6438629/are-there-any-native-functions-to-perform-integration-or-derivatives-in-js), mentioning that there should be an integration branch.

Have you added symbolic integration, or is it only for polynomials? If not, I could try starting a basic implementation in the calculus add-on.

**Comment by jiggzson** [comment]
There used to be symbolic integration for univariate polynomials but that has since been removed from the dev branch. I'm hoping to add integration soon. I can re-add the basic implementation. I'll add it to the dev branch along with the fix for issue #60.

**Comment by danielsvane** [comment]
It would be nice if you add the basic implementation again, then I have something to start with.

**Comment by jiggzson** [comment]
Have you looked into [algebrite](http://algebrite.org/) by any chance. It already does integration and might suit your needs. The current state of the integration algorithm in nerdamer is very crude and I just wouldn't want to write any form of production code around it. Just a thought. If you still want me to add it after looking at algebrite, let me know.

**Comment by danielsvane** [comment]
Okay algebrite seems to solve my problem, no idea how I haven't found it myself. Thanks for your help! And thanks for this library, even though I'm not gonna use it :p
