### ISSUE TITLE
differentiation giving wrong result.

### ISSUE THREAD

**Issue by Anonymus0999** [jiggzson/nerdamer#610]
Unable to solve diff(sqrt(e^x + a),x)
This is giving output = e^x
There is also problem in integrate((sin(sqrt(x)+a) * e^sqrt(x)), x)
I think the problems are some how related to the **sqrt** part. Because if I try for sqrt(e^x) or sqrt(3^x) It results error:
![Screenshot 2021-05-21 030026](https://user-images.githubusercontent.com/84542849/119051416-c2fb6400-b9e0-11eb-8d5f-1d6a70c0e40b.png)
but sqrt(x^3) is okay. No error.

**Comment by jiggzson** [comment]
@Anonymus0999, I'll look into it. Thanks.
