### ISSUE TITLE
colorize text output

### ISSUE THREAD

**Issue by Porizm** [jiggzson/nerdamer#626]
Hello,

Is there a way to modify .toTex and colorize some variables?

for example x + 1 = 0
I want the tex output to be like

\textcolor{blue}{x} + 1 = 0

Thank you

**Comment by jiggzson** [comment]
@Porizm, not at the moment but I can certainly look into it.

**Comment by jiggzson** [comment]
@Porizm, not at the moment but I can certainly look into it.

**Comment by Porizm** [comment]
Thank you
