### ISSUE TITLE
Using solveEquations or solve with i alone on either side of = gives an error.

### ISSUE THREAD

**Issue by TimonDalton** [jiggzson/nerdamer#627]
This: 
`var sol = nerdamer.solveEquations(['x=i','x+y=3']);`
returns
`Error [NerdamerValueError]: i does not equal x`
while 
`var sol = nerdamer.solveEquations(['x - i=0','x+y=3']);`
is fine. 
This happens in any example where i is alone on one side of the equal sign.

**Comment by jiggzson** [comment]
@TimonDalton, thanks for reporting. I suspect I have to review the logic in [this](https://github.com/jiggzson/nerdamer/blob/926e12d27c639c94eadde4fa807843d4d98ba451/Solve.js#L100) line.
