### ISSUE TITLE
solveEquations returns empty array for equation system that has a solution

### ISSUE THREAD

**Issue by cihancimen** [jiggzson/nerdamer#636]
`nerdamer.solveEquations(["x=5", "0.6=1-(x/(10+y))"])` returns `[]`

However, nerdamer is able to solve if second equation is simplified a bit.
nerdamer.solveEquations(["x=5", "-0.4=-(x/(10+y))"]).toString() returns `x,5,y,2.5`

Any ideas on the issue here? 
It would be great to know if there is a workaround that doesn't involve manipulation of equations.

**Comment by jiggzson** [comment]
@cihancimen, I'll look into it. I suspect that the form of the equation is causing some problems.

**Comment by daniyalzade** [comment]
@jiggzson it'd be fantastic if you could release this change. It looks like a major one.

**Comment by jiggzson** [comment]
@sametaylak, @daniyalzade, I'll try to release it as soon as possible.
