### ISSUE TITLE
Add Types for nerdamer/all Algebra Extra Solve and Calculus 

### ISSUE THREAD

**Issue by JeremyMoeglich** [jiggzson/nerdamer#659]
Type definitions are currently only available for nerdamer core, adding type definitions for the other add-ons would be useful.

**Comment by peacememories** [comment]
This seems like it would make working with the library much easier, both in typescript as well as javascript (because of the autocompletion provided by the types). Why has this been closed?

**Comment by JeremyMoeglich** [comment]
There is currently a work in progress pull request that rewrites the entire library in typescript
