### ISSUE TITLE
Multiple minus operators yield wrong result

### ISSUE THREAD

**Issue by ljacqu** [jiggzson/nerdamer#76]
I just noticed that multiple `-` (and brackets) don't seem to get along in some cases. Here are two failing test cases.

```js
{
   given: '-(1)--(1-1--1)',
   expected: '0'  // current result: -2
},
{
   given: '-(-(1))-(--1)',
   expected: '0'  // current result: 2
}
```

**Comment by jiggzson** [comment]
Thank you. This was the motivation I needed to kick off version 0.7.x of nerdamer. I wasn't too fond of the way prefix operators are currently handled.

**Comment by jiggzson** [comment]
The latest version addresses this bug.

**Comment by ljacqu** [comment]
Verified successfully, thanks -> previously failing tests now work
