### ISSUE TITLE
Get results in a decimal form

### ISSUE THREAD

**Issue by DouglasdeMoura** [jiggzson/nerdamer#8]
Is it possible to make the LaTeX generator return the decimal value instead of the fraction?

`3/10 = 0.3 instead of 3/10`

I know that we will face a floating point issue (because the result will be 0.30000000000000004). Perhaps add a BigDecimal library to handle it?

**Comment by jiggzson** [comment]
Currently no. In the demo it's currently done by looking at the return and then converting it to a decimal. It's one of those things that got pushed to that magical place called tomorrow in the past.

**Comment by jiggzson** [comment]
The issue is addressed and fixed in version 0.6.0.
