### ISSUE TITLE
Get TeX string prior to evaluating?

### ISSUE THREAD

**Issue by gksander** [jiggzson/nerdamer#88]
Is there any way to parse a string to LaTeX using nerdamer *prior* to nerdamer evaluting the string? For example -- taking 'x*x' and returning 'x \cdot x' instead of 'x^2' ?

**Comment by jiggzson** [comment]
Currently no. It would be interesting to add this if there aren't any libraries that can do so. I did at some point have plans to incorporate [AsciiMath](http://asciimath.org) for this purpose. Have you looked into that library by any chance?

**Comment by gksander** [comment]
I use AsciiMath on a daily basis, but as an end user. The author of AsciiMath (David Lippman) is the author of another project called IMathAS (which is wonderful) that I use a lot. However, I believe that AsciiMath (AM) parses "calculator type" to MathML rather than TeX, so there might be some discrepancies there. For example, AM will read diff(x^2) as d <-> (x^2) since it's reading "iff" as "if and only if". So I could foresee one running into some issues there.

I'm currently using mathjs which has a parse() function which parses a string to an expression tree, and then you can call a toTex() method on that. This sort of works, but I'm not thrilled because it's building another expression tree and there are some differences between the recognized functions in mathjs and nerdamer. Here's my current progress on what I'm working on [https://gksander.github.io/AlgCalc/](https://gksander.github.io/AlgCalc/).

It'd be nice to have a function that could take user input and parse it out before evaluating, and aligning this with the nerdamer functions. (E.g., taking 'integrate(x^2)' and actually output "\int x^2 \, dx"). I'll dig around a little more for a library that is already doing something like this, but so far I haven't found much.

**Comment by jiggzson** [comment]
Ok. I see what you mean. You mean. Let me think about it some. It might not just be a matter of slightly modifying the LaTeX generator. It's difficult to say without playing around with it a bit.

**Comment by jiggzson** [comment]
I added the convertToLaTeX method. Let me know how it works since I haven't really tested is extensively. For the 'integrate' function make sure that the Calculus add-on is loaded. So for example

```javascript
require('./Calculus'); //If you're in a node environment of course
var x = nerdamer.convertToLaTeX('(x+x-1)/y+x^2+integrate(a+b,x)');
console.log(x);
```
will output

```LaTeX
\frac{x + x - 1}{y} + {x}^{2} + \int{a + b} dx
```
Good luck.

**Comment by gksander** [comment]
Wow -- this looks great! I appreciate it!

If I stumble upon any bugs, I'll submit a pull request.

And I must say -- I really appreciate the amount of documentation you have, the clarity of your code, and your responsiveness. I hope to make some PR's in the future and contribute to your great codebase.

**Comment by jiggzson** [comment]
Thanks @gksander. I appreciate it.

**Comment by gksander** [comment]
I'll go ahead and close this issue. Quick question first though: I've actually never studied the theory behind Computer Algebra Systems (only used them as an end user). *Is there any literature that you use/used to learn about CAS's?* I'd love to learn more about the theory behind Nerdamer (and CASs in general), and I think this would help me better contribute to your project.

**Comment by jiggzson** [comment]
Nerdamer breaks quite a few rules, mainly because of the challenges with doing math in JavaScript. Another way that nerdamer breaks convention is in the way symbols are represented internally. It deviates from the typical mathematical model and uses a grouping approach. Making the conversion isn't hard at all, it's just something to keep in mind. With that said, my favorite book is "Algorithms for Computer Algebra, Geddes, Keith O., Czapor, Stephen R., Labahn, George" ISBN 978-0-585-33247-5. It's pretty comprehensive. I'm not discounting other books or literature out there, I just personally find this one the easiest to read and understand.
