### ISSUE TITLE
npm issue

### ISSUE THREAD

**Issue by finya** [jiggzson/nerdamer#89]
Hello, i am using nerdamer in my serverside application.
When i try to use diff function i get error 

__nerdamer2.default.diff is not a function_

nerdamer.reserved() shows
_csc, sec, cot, erf, fact, mod, GCD, PI, E, cos, sin, tan, acos, asin, atan, exp, min, max, floor, ceiling, round, vector, matrix, parens, sqrt, log, abs, invert, transpose, dot_

version 0.5.7

import:
_import nerdamer from 'nerdamer'_

usage:
_let diff = nerdamer.diff(funcY)_

How can i use diff function in my case?

**Comment by jiggzson** [comment]
Hi @finya. Unfortunately the npm packages are grossly outdated. The last update was done by @brosnanyuen and I haven't had the time to figure out how to update them. To use the latest version of nerdamer you'd have the use the one on Github.

**Comment by finya** [comment]
@brosnanyuen could you help with this issue?

**Comment by jiggzson** [comment]
Hopefully it's fixed. If not please let me know. 

Thanks

**Comment by finya** [comment]
Works fine, thanks!
