### ISSUE TITLE
Auto-detect and register new functions

### ISSUE THREAD

**Issue by DouglasdeMoura** [jiggzson/nerdamer#9]
I believe that would be better if nerdamer could detect and register custom functions. Like this:

```javascript
if(/([a-z])\([a-z](.*)\)=/i.test(input)) {
  var fn = input.match(/[a-z]+\(/i)[0].replace('(', '');
  var exp = input.split('=')[1];
  var arguments = input.replace(fn, '').replace(exp, '').replace('=', '').replace('(', '').replace(')', '').split(',');
  nerdamer.setFunction(fn, arguments, exp);
}
```

It worked fine with the functions below:

* `hyp(a, b) = sqrt(a^2 + b^2)`
* `f(x) = x^2`

Sorry for not sending a pull request, I'm just an amateur.

**Comment by jiggzson** [comment]
No worries. We're all eternal students and I'm learning right along side you. I know it's not documented but I'm actually hoping to reserve the = sign for equations and use the := for assignment. At least that's the goal. I know I implemented something similar to this inside the demo but never ported it to the library itself. I'll take a look at it, or feel free to do so, and compare the two and let's add it to the library.

**Comment by DouglasdeMoura** [comment]
I've sent a pull request adding that feature. See at https://github.com/jiggzson/nerdamer/pull/12.
