### ISSUE TITLE
Symbol evaluate() method

### ISSUE THREAD

**Issue by gksander** [jiggzson/nerdamer#95]
I see that the Symbol prototype does not have an evaluate method, but the master nerdamer function has an option to evaluate by passing an object. Is there currently a way to evaluate a Symbol object in a similar way, by passing an object with variable-value pairs?

As an explicit example, if I get a Symbol object returned from the integrate function, is there currently a way to evaluate that Symbol at a numerical value?

**Comment by jiggzson** [comment]
The Symbol class is sort of a private class and was never meant to be exposed. The expression class was created for this purpose and is therefore the one that has been documented. If you must interact with the Symbol class directly then I guess **core.PARSER.parse** is what you'd be looking for. I've found that it's more efficient to convert to string and re-parse then to modify the existing object. So for example:
```javascript
var core = nerdamer.getCore();
var _ = core.PARSER;
var x = nerdamer('x^2-y+x').symbol;
console.log(_.parse(x, {x: 2}).toString());
```
Is this what you're looking for?

**Comment by gksander** [comment]
Right -- the Expression is the public interface. Yes, I believe your suggestion works! Actually, that was my first guess (use toString() and reparse) but I didn't know if that was the best option.  Thanks!
