### ISSUE TITLE
solveFor documentation has broken output

### ISSUE THREAD

**Issue by NaridaL** [jiggzson/nerdamer#97]
http://nerdamer.com/functions/nerdamer.solveFor.html

**Comment by NaridaL** [comment]
Other minor documentation issues:
http://nerdamer.com/functions/roots.html expression x description makes no sense.

http://nerdamer.com/functions/sum.html  "GCD"?

**Comment by jiggzson** [comment]
Seems like I had a copy/paste mishap :). I'll go ahead and take care of this. I'll also look into the solveFor issue. Thanks for reporting this @NaridaL .

**Comment by jiggzson** [comment]
I really should add tests from solveFor.

**Comment by jiggzson** [comment]
Fixed

**Comment by jiggzson** [comment]
Is this still an issue?

**Comment by NaridaL** [comment]
No, looks good.
